composable/chain.json
Remove previous version from compatible versions
=> Upgrade Composable to v6.3.6

osmosis/assetlist.json
=> Add WBTC to Osmosis

jackal/chain.json
Remove previous versions as compatible and replace with patch
=> Upgrade Jackal to v3.0.5

bitcanna/chain.json
=> Update Citizen Cosmos alias.json

evmos/chain.json
https://www.mintscan.io/evmos/proposals/265
https://www.mintscan.io/evmos/block/18295000
=> Upgrade Evmos to v16.0.0

kujira/chain.json
https://explorer.kjnodes.com/kujira/gov/534
https://explorer.kjnodes.com/kujira/blocks/16610000
=> Upgrade Kujira to v0.9.3

archway/chain.json
Remove previous versions from compatible
=> Upgrade Archway to v4.0.3

oraichain/chain.json
Add Blockval's Oraichain services (api, rpc, grpc & explorer)
=> Add Blockval Oraichain services

osmosis/chain.json
Add Chainscope to explorers list
=> Add Chainscope Osmosis Explorer

testnets/cosstestnet/assetlist.json, testnets/cosstestnet/chain.json
Hi, our new testnet is up and running, please help merge this pr. Thanks!
=> Add coss testnet

sge/chain.json
https://explorer.stavr.tech/Sge-Mainnet/gov/4
https://explorer.stavr.tech/Sge-Mainnet/block/1887954
=> Upgrade SGE to v1.3.0

nomic/chain.json
=> Upgrade Nomic to v7.0.1

quicksilver/chain.json
https://www.mintscan.io/quicksilver/proposals/28
https://www.mintscan.io/quicksilver/block/5493000
=> Upgrade Quicksilver to v1.4.6

sge/chain.json
https://ping.pub/sge/gov/5
https://ping.pub/sge/block/1911750
=> Upgarde SGE to v1.3.1

stride/chain.json
https://www.mintscan.io/stride/proposals/226
https://www.mintscan.io/stride/block/7244427
=> Upgrade Stride to v17

evmos/chain.json
RPC query fix https://github.com/evmos/evmos/releases/tag/v16.0.2
=> Upgrade Evmos to v16.0.2

jackal/chain.json
https://ping.pub/jackal/gov/11
https://ping.pub/jackal/block/6095000
=> Upgrade Jackal to v3.1.1

testnets/entrypointtestnet/chain.json
Reference: https://github.com/entrypoint-zone/testnets/tree/main/entrypoint-pubtest-2#testnet-details
=> Bump EntryPoint version to v1.2.0 and fix gas price

haqq/chain.json
https://ping.pub/haqq/gov/27
https://ping.pub/haqq/block/9451000
=> Upgrade Haqq to v1.7.0

terra2/chain.json
https://github.com/terra-money/core/releases/tag/v2.6.4
=> Patch Terra2 to v2.6.4

testnets/_IBC/osmosistestnet-sagatestnet.json
Update IBC config for osmosistestnet-sagatestnet
=> Update IBC config for osmosistestnet-sagatestnet

stride/chain.json
Remove the fees that aren't registered to its assetlist
=> Fix Stride Fees

neutron/chain.json
Not allowed to have fees that aren't registered.
=> Fix Neutron Fees

carbon/chain.json
https://scan.carbon.network/governance/proposal/338?net=main
https://scan.carbon.network/block/52699891?net=main
=> Upgrade Carbon to v2.37.0

sentinel/chain.json
Update Sentinel chain.json with Sentinel Growth DAO provider (RPC and API)
=> Add Sentinel Growth DAO RPC and API for Sentinel Chain

omniflixhub/chain.json
https://www.mintscan.io/omniflix/proposals/28
https://www.mintscan.io/omniflix/blocks/10428200
=> Upgrade Omniflixhub to v2.0.0

nolus/chain.json
https://explorer.nolus.io/pirin-1/gov/72
https://ping.pub/nolus/block/3659000
=> Upgrade Nolus to v0.5.0

juno/assetlist.json
Fix PLTN display unit,
was 'palantin', which was undefined. Now 'pltn'
=> Fix PLTN display unit

osmosis/assetlist.json
Fix Osmosis' $SAIL display unit to a valid unit
=> Fix Osmosis' $SAIL display unit

coreum/chain.json
=> Add #SoloNation Public Endpoints for Coreum

composable/chain.json
https://ping.pub/composable/gov/14
https://ping.pub/composable/block/3486739
=> Upgrade Composable to v6_4

sei/chain.json
https://www.mintscan.io/sei/proposals/49
https://www.mintscan.io/sei/block/53894102
=> Upgrade Sei to v3.6.1

carbon/assetlist.json, carbon/chain.json
- Add `milkTIA` from Osmosis
- Add `TIA` from Osmosis
- Update default Carbon network fee
=> Update Carbon gas costs and fee tokens

andromeda/chain.json
Removed Nodeist after they quit validating.
=> Remove Nodeist from Andromeda

bitcanna/chain.json
https://explorer.bitcanna.io/proposals/14
https://www.mintscan.io/bitcanna/block/12288420
=> Upgrade Bitcanna to "ganjarevolution"

qwoyn/chain.json
https://ping.pub/qwoyn/gov/15
https://ping.pub/qwoyn/block/3395000
=> Upgrade Qwoyn to v5.4.1

carbon/chain.json
https://github.com/Switcheo/carbon-bootstrap/releases/tag/v2.37.1
=> Patch Carbon for v2.37.1

osmosis/chain.json
Previous two versions were missing from version history.
=> Update missing recent version history for Osmosis

_IBC/doravota-sei.json
Channel requested by Doravota team, maintained by [CryptoCrew](https://ccvalidators.com)
=> Add `ibc` doravota-sei

dydx/chain.json
https://www.mintscan.io/dydx/proposals/7
https://www.mintscan.io/dydx/block/7147832
=> Upgrade Dydx to v3.0.0

teritori/chain.json
https://www.mintscan.io/teritori/proposals/38
https://www.mintscan.io/teritori/block/7199342
=> Upgrade Teritori to v2.0.0

stride/chain.json
https://www.mintscan.io/stride/proposals/229
https://www.mintscan.io/stride/block/7464647
=> Upgrade Stride to v18

assetlist.schema.json
Update assetlist.schema.json to add extended_description for optional long descriptions of assets.
=> Add Asset extended_description

shentu/chain.json
=> Add Panthea EU endpoints for Shentu

lumnetwork/chain.json
https://explorer.lum.network/proposals/97
https://www.mintscan.io/lum/block/11390000
=> Upgrade Lum Network to v1.6.4

persistence/chain.json
https://www.mintscan.io/persistence/proposals/68
https://www.mintscan.io/persistence/block/15242222
=> Upgrade Persistence to v10.4.0 and add v10.3.0 to version history

humans/chain.json
=> Add PPNV endpoints to Humans

juno/chain.json
https://www.mintscan.io/juno/proposals/333
https://www.mintscan.io/juno/block/13678871
=> Upgrade Juno to v19

_IBC/humans-osmosis.json
Adds humans.ai main IBC channels
=> Adds humans.ai IBC

quicksilver/chain.json
https://quicksilver.explorers.guru/proposal/30
https://quicksilver.explorers.guru/block/5848000
=> Upgrade Quicksilver to v1.4.7

osmosis/assetlist.json
Update Osmosis assetlist.json to match Osmosis' Assetlist Repo's assetlist.json (only did a few tokens here to make sure things don't break.
=> Update Osmosis assetlist.json 1

osmosis/assetlist.json
Update Osmosis assetlist.json 2
Added or updated just a few tokens (USDT, DAI, WETH, BUSD)
Mostly focused on re-ordering the assets to the order the Osmosis-labs assetlists repo uses (this will be useful for comparisons when copy and pasting the entire value into here later.
=> Update Osmosis assetlist.json 2

osmosis/assetlist.json
Clean up Osmosis' assetlist 
Some values were a bit useless, and it's preferred to have values consistent with the original asset, such as with a ics20 having a custom description of "TOKEN on Osmosis", which is much less informative than: "Token does functions xyz on chain Foo".
=> Clean up Osmosis' assetlist 

osmosis/assetlist.json
Update Osmosis assetlist.json 4
Adds many of the assets previously missing from this assetlist. Includes everything listed on osmosis-labs' assetlists repo, plus a few extra that are only registered here.
=> Update Osmosis assetlist.json 4

omniflixhub/chain.json
https://omniflix.explorers.guru/proposal/29
https://omniflix.explorers.guru/block/10678600
=> Upgrade Omniflix to v2.1

sommelier/chain.json
=> Upgrade to Sommelier v7

coreum/chain.json
Updated Coreum RPC and API
Updated Explorer
=> Update #SoloNation Public Node URLs

haqq/chain.json
https://haqq.exploreme.pro/proposals/28
https://haqq.exploreme.pro/blocks/9774000
=> Upgrade Haqq to v1.7.1

nolus/chain.json
https://ping.pub/nolus/gov/76
https://ping.pub/nolus/block/3958000
=> Upgrade Nolus to v5.0.1

dymension/chain.json
Adding load balanced end points from Agora Nodes
=> Add AgoraNodes Loadbalanced Endpoints for Dymension Mainnet

celestia/chain.json
=> Reverse Proxy/SSL/Port change

README.md
Update README.md to Describe Desired PR Titles
=> Update README.md to Describe Desired PR Titles

_IBC/odin-osmosis.json, odin/chain.json, osmosis/assetlist.json
- updated IBC clients in /_IBC/odin-osmosis
- added 2 tokens to /osmosis/assetlist - [MYRK, DOKI]
- set 'osmosis_unlisted' status for the above
- removed 'osmosis_unstable' status from existing Odin tokens
=> Update odin-osmosis IBC info,  add 2 + change 2 Odin tokens in Osmosis assets

gateway/assetlist.json
=> Add solana USDC to Gateway

haqq/chain.json
https://haqq.exploreme.pro/blocks/9862000
https://haqq.exploreme.pro/proposals/29
=> Upgrade Haqq to v1.7.2

_IBC/gateway-injective.json
made a typo in yesterday's PR. sorry
=> fix gateway-injective channel

sei/chain.json
update gas as per sucessful gov proposal  https://www.mintscan.io/sei/proposals/50
=> Update Sei Protocol gas

planq/chain.json
Software upgrade without props
=> Upgrade Planq to v1.1.0

nolus/chain.json
Upgrade height has already passed
=> Upgrade Nolus to v0.5.2

nibiru/chain.json
https://nibiru.explorers.guru/proposal/2
https://nibiru.explorers.guru/block/2753803
=> Upgrade Nibiru to v1.0.1

axelar/chain.json, bandchain/chain.json, chihuahua/chain.json, coreum/chain.json, decentr/chain.json, dymension/chain.json, impacthub/chain.json, kava/chain.json, kujira/chain.json, nolus/chain.json, passage/chain.json, provenance/chain.json, quasar/chain.json, quicksilver/chain.json, stargaze/chain.json, teritori/chain.json
Update add Inter Blockchain Services seeds
=> Update add Inter Blockchain Services seeds

pylons/chain.json
Need fee suggestions to pass Osmosis checks.
=> Add fee suggestions for Pylons.

assetlist.schema.json, bitsong/assetlist.json
Add Deprecated Asset property
Deprecate Bitsong::L DON, and remove it's images
=> Add Deprecated Asset property

umee/chain.json
UX Chain (Umee):
+ Adds missing releases
+ Updates the website link
+ Updates the chain display name
=> update UX Chain (Umee) to v6.3

_IBC/axelar-bitsong.json
Path requested by bitsong team, maintained by [CryptoCrew](https://ccvalidators.com)
=> Add `ibc` axelar-bitsong

passage/chain.json
https://ping.pub/passage/gov/12
https://ping.pub/passage/block/7080900
=> Upgrade Passage to v2.4.0

omniflixhub/chain.json
https://www.mintscan.io/omniflix/proposals/31
https://www.mintscan.io/omniflix/block/10872800
=> Upgrade Omniflix Hub to v3

bitcanna/chain.json
https://github.com/BitCannaGlobal/bcna/releases/tag/v3.0.2
=> Bitcanna CSDK Patch

source/assetlist.json
SRCX Bridged from BNB through Planq Network to Source.
=> Add SRCX to Source Assetlist

_IBC/oraichain-secretnetwork.json
add's new channel between secret & Oraichain
=> orai -- secret IBC channel

carbon/chain.json
https://scan.carbon.network/governance/proposal/340?net=main
https://scan.carbon.network/block/53991841?net=main
=> Upgrade Carbon to v2.38.0

haqq/chain.json
https://ping.pub/haqq/gov/30
https://ping.pub/haqq/block/9950000
=> Upgrade Haqq to v1.7.3

testnets/sourcetestnet/chain.json
=> Update Source Testnet

archway/chain.json
Updates to archway's price of gas based on the last update to the network's minimum price of gas https://www.mintscan.io/archway/proposals/36
=> Updates to archway's price of gas based on updated minimum price of gas

testnets/_IBC/injectivetestnet-xiontestnet.json, testnets/xiontestnet/assetlist.json, testnets/xiontestnet/chain.json
- Add INJ IBC
- Update versions list
- Update current version
- Remove deprecated endpoints
=> Update Xion testnet IBC, versions and endpoints

sei/chain.json
https://sei.explorers.guru/proposal/51
https://sei.explorers.guru/proposal/51
=> Upgrade Sei to v3.7.0

juno/assetlist.json
Add KELO Extended Description
pulled from CMC https://coinmarketcap.com/currencies/kleomedes/
=> Add KELO Extended Description

desmos/chain.json
https://ping.pub/desmos/gov/42
https://ping.pub/desmos/block/12745550
=> Upgrade Desmos to v7

neutron/chain.json
https://github.com/neutron-org/neutron/releases/tag/v2.0.3
=> Neutron v2.0.3 patch

_IBC/agoric-umee.json, _IBC/celestia-umee.json, _IBC/dydx-umee.json, _IBC/injective-umee.json, _IBC/noble-umee.json, _IBC/regen-umee.json, _IBC/secretnetwork-umee.json
Added new IBC channels connected to the UX Chain (Umee)
=> ibc: update UX Chain (Umee) IBC channels

cosmoshub/chain.json
https://github.com/cosmos/gaia/releases/tag/v14.2.0
=> Patch Cosmos Hub to v14.2.0

zetachain/chain.json
https://hub.zetachain.com/governance/proposal/21
=> Upgrade Zetachain to v14 and add version history

testnets/_IBC/axelartestnet-lavatestnet2.json, testnets/_IBC/lavatestnet2-osmosistestnet.json
update lava IBC channel for axelar and osmosis, after freez of old channel
=> update lavatestnet2 IBC channel

testnets/_non-cosmos/avalanchetestnet/assetlist.json
Register Avalanche Testnet USDC
=> Register Avalanche Testnet USDC

cifer/chain.json
=> Add RPC and Rest API Endpoints

source/chain.json
Small Security Update. Organized with Validators via Discord. All Validators currently running v3.0.1.
=> Upgrade Source v3.0.1

nibiru/chain.json
https://nibiru.explorers.guru/proposal/6
https://nibiru.explorers.guru/block/3539699
=> Upgrade Nibiru to v1.0.2

README.md, assetlist.schema.json, osmosis/assetlist.json
Add socials to assetlist schema
and Osmosis and readme to serve as an example
=> Add socials to assetlist schema

juno/chain.json
https://www.mintscan.io/juno/proposals/340
https://www.mintscan.io/juno/block/14556500
=> Upgrade Juno to v21

.github/workflows/utility/chain_registry.mjs, .github/workflows/utility/chain_registry_local.mjs, .github/workflows/utility/sync_images.mjs
Update chain_registry.mjs Code
=> Update chain_registry.mjs Code

_IBC/comdex-kujira.json
based on conversations with theBros| @crosnest
it came to our attention that the wrong client/connection was in here
=> Update comdex-kujira.json - fix connection/client-id

odin/chain.json
https://ping.pub/odin/gov/22
https://ping.pub/odin/block/13310888
=> Upgrade Odin to v0.7.11

jackal/chain.json
https://explorer.nodestake.org/jackal/gov/12
https://explorer.nodestake.org/jackal/block/6835000
=> Upgrade Jackal to v320

chain4energy/chain.json
Added Apeiron Nodes seed and rpc.
=> Add Apeiron Nodes rpc-seed endpoints on chain.json

quicksilver/chain.json
https://www.mintscan.io/quicksilver/proposals/31
https://www.mintscan.io/quicksilver/block/6365700
=> Upgrade Quicksilver to v1.5.0

lumnetwork/chain.json
https://www.mintscan.io/lum/proposals/101
https://www.mintscan.io/lum/block/11992000
=> Upgrade Lum Network to v1.6.5

odin/assetlist.json
- Updated ODIN description 
- Added DOKI socials 
- Added Myrk social
- Added o9w socials
=> Update ODIN assetlist with socials

akash/chain.json
https://www.mintscan.io/akash/proposals/249
https://www.mintscan.io/akash/block/15414427
=> Upgrade Akash to v0.32.0

genesisl1/chain.json
Hi!
GenesisL1 has changed since we've forked to a different codebase. This PR aims to update its configurations.
=> Updated genesisL1 chain configs

terra2/chain.json
https://ping.pub/terra/gov/4805
https://ping.pub/terra/block/9444000
=> Upgrade Terra2 to v2.10

osmosis/assetlist.json
Added SHARK to Osmosis 
It was already under Migaloo - just added info for Osmosis.
=> Added SHARK to Osmosis 

axelar/chain.json
https://www.mintscan.io/axelar/proposals/195
https://www.mintscan.io/axelar/block/11795700
=> Upgrade Axelar to v0.35

migaloo/chain.json
https://ping.pub/Migaloo/gov/24
https://ping.pub/Migaloo/block/5689150
=> Upgrade Migaloo to v4.1.3

bitsong/chain.json
https://ping.pub/bitsong/gov/34
https://ping.pub/bitsong/block/15947000
=> Upgrade Bitsong to v0.15.0

_IBC/cosmoshubtestnet-elystestnet.json, _IBC/elystestnet-nobletestnet.json, testnets/elystestnet/assetlist.json, testnets/elystestnet/chain.json
It update Elys chain definition to support different fee currencies in wallet providers.
=> Elys: Adds USDC and ATOM fee currencies

_IBC/noble-provenance.json
Adds ibc information for working channel between noble and provenance.
=> Add noble-provenance.json

oraichain/chain.json
Added seed, persistent peer and rpc from Morty's Nodes
=> Add Endpoints to Oraichain (Marty's Nodes)

bitsong/chain.json
Update chain.json with new binaries and versions, add cosmwasm
=> Update BitSong info

_IBC/axelar-provenance.json
Adds ibc information for working channel between axelar and provenance.
=> Add _IBC/axelar-provenance.json

quicksilver/chain.json
https://www.mintscan.io/quicksilver/proposals/32
https://www.mintscan.io/quicksilver/block/6452000
=> Upgrade Quicksilver to v1.5.1

persistence/chain.json
https://www.mintscan.io/persistence/proposals/84
https://www.mintscan.io/persistence/block/15860600
=> Upgrade Persistence to v11 and update chain history

sge/chain.json
https://explorer.tcnetwork.io/sge/proposal/6
https://explorer.stavr.tech/Sge-Mainnet/block/2867354
=> Upgrade SGE Network to v1.5.2

sei/chain.json
https://www.mintscan.io/sei/proposals/53
https://www.mintscan.io/sei/block/64851894
=> Upgrade Sei to v3.8.0

source/assetlist.json
Add extended_description and socials
=> Update Source Assetlist

testnets/_IBC/cosmoshubtestnet-kujiratestnet.json
```
{
"chain_id": "harpoon-4",
"channel_id": "channel-51",
"client_id": "07-tendermint-72",
"connection_hops": [
"connection-47"
],
"counterparty": {
"chain_id": "theta-testnet-001",
"channel_id": "channel-4004",
"client_id": "07-tendermint-3407",
"connection_id": "connection-3519",
"port_id": "transfer"
},
"ordering": "ORDER_UNORDERED",
"port_id": "transfer",
"state": "STATE_OPEN",
"version": "ics20-1"
}
```
=> channel correction

nibiru/chain.json
https://nibiru.explorers.guru/proposal/8
https://nibiru.explorers.guru/block/4088799
=> Upgrade Nibiru to v1.0.3

.github/workflows/utility/chain_registry.mjs
Add Chain_reg Function to Fetch Asset Property with Custom Set of Trace Types
=> Add Chain_reg Function to Fetch Asset Property with Custom Set of Trace Types

ununifi/chain.json
https://explorer.nodestake.org/ununifi/gov/26
https://explorer.nodestake.org/ununifi/block/9974824
=> Upgrade Ununifi to v4_0_2

testnets/_IBC/kujiratestnet-terra2testnet.json
Added new path for terra2-testnet to kujira-testnet
=> added harpoon-4 <> pisco-1

stride/chain.json
https://www.mintscan.io/stride/proposals/235
https://www.mintscan.io/stride/block/8269628
=> Upgrade Stride to v20

dydx/chain.json, juno/chain.json, nois/chain.json, nolus/chain.json, omniflixhub/chain.json, testnets/dydxtestnet/chain.json
add fixed_min_gas_price 
update minimums to 0.025
=> update nolus gas prices

qwoyn/assetlist.json
Changed the rather long description to extended_description.
=> Update QWOYN description

sge/chain.json
https://explorer.stavr.tech/Sge-Mainnet/gov/7
https://explorer.stavr.tech/Sge-Mainnet/block/2973740
=> Upgrade SGE to v1.5.3

composable/chain.json
https://ping.pub/composable/gov/16
https://ping.pub/composable/block/4446786
=> Upgrade Composable to v6_5_0

scorum/chain.json
=> Add website to Scorum

furya/assetlist.json, furya/chain.json
Following the addition of new validators on the network, some info needed to be updated.
What's updated:
- RPC and API Endpoints
- Peers
- Coingecko ID
- Explorer query URL
=> Update endpoint and other info for Furya

stride/chain.json
https://www.mintscan.io/stride/proposals/236
https://www.mintscan.io/stride/block/8370738
=> Upgrade Stride to v21

nibiru/chain.json
https://nibiru.explorers.guru/proposal/9
https://nibiru.explorers.guru/block/4447094
=> Upgrade Nibiru to v1.1.0

xpla/chain.json
https://www.mintscan.io/xpla/proposals/59
https://www.mintscan.io/xpla/block/8373900
=> Upgrade XPLA to v1_4

realio/chain.json
Proposal : https://explorer.realio.network/proposals/7
=> Upgrade Realio to v0.9.0

quicksilver/chain.json
https://www.mintscan.io/quicksilver/proposals/35
https://www.mintscan.io/quicksilver/block/6673000
=> Upgrade Quicksilver to v1.5.4

_non-cosmos/aptos/assetlist.json, _non-cosmos/arbitrum/assetlist.json, _non-cosmos/avalanche/assetlist.json, _non-cosmos/binancesmartchain/assetlist.json, _non-cosmos/bitcoin/assetlist.json, _non-cosmos/composablepolkadot/assetlist.json, _non-cosmos/ethereum/assetlist.json, _non-cosmos/fantom/assetlist.json, _non-cosmos/filecoin/assetlist.json, _non-cosmos/kusama/assetlist.json, _non-cosmos/moonbeam/assetlist.json, _non-cosmos/picasso/assetlist.json, _non-cosmos/polkadot/assetlist.json, _non-cosmos/polygon/assetlist.json, _non-cosmos/solana/assetlist.json, _non-cosmos/statemine/assetlist.json, _non-cosmos/stellar/assetlist.json, _non-cosmos/sui/assetlist.json, _non-cosmos/xrpl/assetlist.json, assetlist.schema.json
Add More `type_asset` Asset Types
'bitcoin-like', 'evm-base', and 'svm-base'
=> Add More `type_asset` Asset Types

gateway/assetlist.json
Correct $W Base Denom
from address to actual token factory denom
=> Correct $W Base Denom

_non-cosmos/solana/assetlist.json
Add Wormhole Token $W CoinGecko ID
under solana
=> Add Wormhole Token $W CoinGecko ID

impacthub/chain.json
https://ping.pub/ixo/gov/447
https://ping.pub/ixo/block/5508000
=> Upgrade Impacthub to v3

_IBC/dhealth-osmosis.json, dhealth/chain.json
- Update token fees
- Add IBC data
=> Update dHealth chain

composable/chain.json
https://ping.pub/composable/gov/18
https://ping.pub/composable/block/4576500
=> Upgrade Composable to v6_5_3

nibiru/chain.json
https://nibiru.explorers.guru/proposal/10
https://nibiru.explorers.guru/block/4804662
=> Upgrade Nibiru to v1.2.0

_IBC/neutron-secretnetwork.json
This adds another channel to support Secret SNIP20 tokens over the wasm.secret1tqmms5awftpuhalcv5h5mg76fa0tkdz4jv9ex4 channel
=> Update neutron-secretnetwork.json 

dydx/chain.json
https://www.mintscan.io/dydx/proposals/46
https://www.mintscan.io/dydx/block/12791712
=> Upgrade DYDX to v4.0.0

conscious/chain.json
=> Update conscious website.

saga/assetlist.json, saga/chain.json
See keplr for fee settings: https://github.com/chainapsis/keplr-chain-registry/pull/563/files
=> Add initial settings for Saga

saga/assetlist.json
https://www.coingecko.com/en/coins/saga this token's ID is actually saga-2
=> fix(saga): change coingecko id

testnets/galacticatestnet/chain.json
their old one had a major issue
=> galactica has a new chain id

saga/assetlist.json, saga/chain.json
Add Saga chain description and extended description for the $SAGA token
=> Add Saga chain description

archway/chain.json
https://github.com/archway-network/archway/releases/tag/v6.0.3
=> Patch Archway to v6.0.3

bandchain/chain.json
Add more information for BandChain such as version, gas, lock_duration.
=> Add version info for BandChain

cosmoshub/chain.json
https://github.com/cosmos/gaia/releases/tag/v15.2.0
=> Patch Cosmos Hub to v15.2.0

_IBC/planq-source.json
=> Update Expired IBC Client Planq<>Source

testnets/mantrachaintestnet/assetlist.json, testnets/mantrachaintestnet/chain.json
This PR updates the details of the MANTRA Chain Testnet following the Hongbai Release.
=> chore: update MANTRA Chain Testnet details for Hongbai release

loop/assetlist.json
=> Fix Loop's POA Asset Image

neutron/assetlist.json
Define Traces for xASTRO on Neutron
Liquid Staking ASTRO
=> Define Traces for xASTRO on Neutron

unification/assetlist.json
Adding an extended description and Socials for the Unification FUND asset
=> Add extended description and Socials for Unification

.github/workflows/utility/validate_data.mjs, chimba/chain.json, saga/chain.json, terra/assetlist.json, testnets/chimbatestnet/chain.json
Add Staking Denom Validation
Caught a few cases where the staking denom was not registered properly (saga and chimba)
=> Add Staking Denom Validation

osmosis/assetlist.json
Remove Duplicate Image for Levana
=> Remove Duplicate Image for Levana

_non-cosmos/ethereum/assetlist.json
Add Description for $PEPE. Pulled from Etherscan
and keyword that it's "meme"
=> Add Description for $PEPE

celestia/assetlist.json
Add Description for Celestia
and extended description
=> Add Description for Celestia

likecoin/chain.json
=> Update domain name of Citizenweb3 for Likecoin

bitcanna/chain.json
=> Update domain name of Citizenweb3 for Bitcanna

injective/assetlist.json
=> Update HAVA Registration

testnets/osmosistestnet/assetlist.json
Update Osmosis Testnet Assetlist
based on generation from Osmosis Labs' assetlists repo
=> Update Osmosis Testnet Assetlist

testnets/_IBC/axelartestnet-xiontestnet.json, testnets/_IBC/injectivetestnet-xiontestnet.json, testnets/_IBC/nobletestnet-xiontestnet.json, testnets/_IBC/osmosistestnet-xiontestnet.json, testnets/xiontestnet/assetlist.json, testnets/xiontestnet/chain.json
- IBC denoms changed
- Connections, channels and clients changed
- Versions deployed on xiontestnet up to v0.3.9
=> Update xiontestnet daemon versions and IBC info

evmos/assetlist.json
- add socials links
- add extended description
=> Extend NeokingdomDAO metadata

conscious/assetlist.json, conscious/chain.json
The url `https://rest.consciousdao.com` is not in use
=> Add socials for CVN

acrechain/assetlist.json, aioz/assetlist.json, arkh/assetlist.json, bitcanna/assetlist.json, bluzelle/assetlist.json, canto/assetlist.json, cifer/assetlist.json, coreum/assetlist.json, cudos/assetlist.json, neutron/assetlist.json, osmosis/assetlist.json, rizon/assetlist.json, secretnetwork/assetlist.json
Add Socials Info for many Assets
=> Add Socials Info for many Assets

_IBC/axelar-shido.json, shido/chain.json
=> shido axlear IBC connection

_non-cosmos/ethereum/assetlist.json
=> Fix Staked Frax traces

_IBC/injective-neutron.json
typo
verify with CLI:
```
$ injectived q ibc channel client-state transfer channel-177 --output json | jq .client_id
"07-tendermint-233"
```
=> Fix client ID of Injective <> Neutron IBC connection

lava/chain.json
=> Update Lavanetwork endpoints , add IBS one

persistence/chain.json
https://www.mintscan.io/persistence/proposals/90
https://www.mintscan.io/persistence/block/16250000
=> Upgrade Persistence to v11.9.0

haqq/chain.json
https://haqq.explorers.guru/proposal/31
https://haqq.explorers.guru/block/10881000
=> Upgrade Haqq to v1.7.4

dydx/chain.json
https://www.mintscan.io/dydx/proposals/53
https://www.mintscan.io/dydx/block/14404200
=> Upgrade DYDX to v4.1.0

kujira/chain.json
https://ping.pub/kujira/gov/618
https://ping.pub/kujira/block/18700000
=> Upgrade Kujira to v1.0.2

odin/chain.json
https://ping.pub/odin/gov/24
https://ping.pub/odin/block/14129800
=> Upgrade Odin to v0.7.12

terra2/assetlist.json
=> Added native USDt to assetlist on Terra

juno/chain.json
https://www.mintscan.io/juno/proposals/347
https://www.mintscan.io/juno/block/15873890
=> Upgrade Juno to v22

sei/chain.json
https://sei.explorers.guru/proposal/54
https://sei.explorers.guru/block/73290488
=> Upgrade Sei to v3.9.0

terra2/chain.json
https://ping.pub/terra/gov/4807
https://ping.pub/terra/block/10136000
=> Upgrade Terra2 to v11

omniflixhub/chain.json
https://www.mintscan.io/omniflix/proposals/36
https://www.mintscan.io/omniflix/block/11914000
=> Upgrade Omniflix Hub to v4

quicksilver/chain.json
https://www.mintscan.io/quicksilver/proposals/37
https://www.mintscan.io/quicksilver/block/6926000
=> Update quicksilver-2 to v1.5.5

akash/chain.json
https://www.mintscan.io/akash/proposals/256
=> Upgrade Akash to v0.34

andromeda/chain.json
https://andromeda.explorers.guru/proposal/5
https://andromeda.explorers.guru/block/2363000
=> Upgrade Andromeda to v0.1.1

_non-cosmos/0l/assetlist.json, osmosis/assetlist.json
=> Correct uLibra to microlibra

_IBC/dhealth-osmosis.json
Some information:
Osmosis assetlists ref: https://github.com/osmosis-labs/assetlists/pull/1521
We are an on-reviewed asset with no pool created yet.
=> fix: update dhealth-osmosis ibc data

desmos/chain.json
https://ping.pub/desmos/gov/48
https://ping.pub/desmos/block/13775361
=> Upgrade Desmos to v7.1.0

composable/assetlist.json
Fix Composable PICA trace
was referencing itself before
=> Fix Composable PICA trace

desmos/chain.json
=> Removed endpoints

uptick/chain.json
update uptick chain cosmoswasm Version config
=> update uptick chain cosmoswasm Version

seda/chain.json
Add SEDA RPC , API and seed for Inter Blockchain Services
=> Add Inter Blockchain Services Endpoints for SEDA

osmosis/assetlist.json
Add OSMO, ION Descriptions and extended Descriptions
=> Add OSMO, ION Descriptions

althea/assetlist.json, althea/chain.json
Fix Althea Images References
was mistakenly pointing to Osmosis' repo before (copy-paste error)
=> Fix Althea Images References

nim/chain.json
Added git_repo and genesis_url to codebase on Nim chain.json
=> Update Nim Network

dymension/chain.json
Adds mintscan explorer for dymension
=> Add mintscan explorer for dymension

bitcanna/chain.json
https://www.mintscan.io/bitcanna/proposals/15
https://www.mintscan.io/bitcanna/block/13846420
=> Upgrade Bitcanna to ganjarevolutionburn

carbon/chain.json
https://ping.pub/carbon/gov/353
https://ping.pub/carbon/block/57169241
=> Upgrade Carbon to 2.41.0 and update chain history

seda/chain.json
Added public Bro_n_Bro endpoints for seda
=> Public Bro_n_Bro endpoints for seda

osmosis/assetlist.json
Updated to include socials and meet requirements of osmosis-labs/assetlists repo
=> Update assetlist.json for bOSMO

althea/chain.json
=> Remove Duplicate Althea 🔥STAVR🔥 Endpoint

_non-cosmos/penumbra/assetlist.json
https://github.com/prax-wallet/registry/blob/main/input/penumbra-testnet-deimos-8.json#L43-L68
see also https://github.com/prax-wallet/registry/?tab=readme-ov-file#prax-chain-registry for context on the prax registry
=> align UM metadata with penumbra chain

_template/chain.json, chain.schema.json, nibiru/chain.json, testnets/nibirudevnet/chain.json, testnets/nibirudevnet2/chain.json, testnets/nibirutestnet/chain.json, testnets/nibirutestnet2/chain.json
Add WSS to template and to nibiru
=> feat: wss + nibiru

nibiru/chain.json
https://nibiru.explorers.guru/proposal/12
=> Upgrade Nibiru to v1.3.0

coreum/assetlist.json, coreum/chain.json, testnets/coreumtestnet/assetlist.json, testnets/coreumtestnet/chain.json
* Update Coreum mainnet to v3.0.3
* Update Coreum testnet to v3.0.3
* Add testnet upgrade history
=> Update Coreum registry

nolus/chain.json
=> Nolus v0.5.3 Upgrade

nolus/chain.json, omniflixhub/chain.json
fix version name as per github version tag
=> Fix Omniflix Version Name

cosmoshub/chain.json
https://www.mintscan.io/cosmos/proposals/914
https://www.mintscan.io/cosmos/block/20440500
=> Upgrade Cosmos Hub to v16

osmosis/chain.json, osmosis/versions.json
Osmosis v25 Upgrade
https://www.mintscan.io/osmosis/proposals/782
on Wednesday, May 15th, UTC 15:00 countdown: https://www.mintscan.io/osmosis/block/15753500
=> Osmosis v25 Upgrade

_IBC/juno-neutron.json
Channels requested by the Neutron team, maintained by [CryptoCrew](https://ccvalidators.com)
=> Add `ibc` juno-neutron

dhealth/assetlist.json
Ref: https://github.com/osmosis-labs/assetlists/pull/1582
=> docs: add extended description & socials to dhealth

lumnetwork/chain.json
https://www.mintscan.io/lum/proposals/106
https://www.mintscan.io/lum/block/12969000
=> Upgrade Lum Network to v1.6.6

_IBC/neutron-pryzm.json
Channels requested by the Neutron team, maintained by [CryptoCrew](https://ccvalidators.com)
=> Add `ibc` neutron-pryzm

composable/assetlist.json
Fix Picasso PEPE Trace
didn't have the right letter casing
=> Fix Picasso PEPE Trace

_IBC/composable-solana.json, composable/assetlist.json
Adding info as a prerequisite to verifying assets on the Osmosis assets lists
=> Adding additional info to picasso assetlist

.github/workflows/utility/validate_data.mjs, _non-cosmos/arbitrum/assetlist.json, _non-cosmos/comex/assetlist.json, _non-cosmos/forex/assetlist.json, _non-cosmos/neo/assetlist.json, _non-cosmos/zilliqa/assetlist.json, carbon/assetlist.json, composable/assetlist.json, gravitybridge/assetlist.json, juno/assetlist.json, kujira/assetlist.json, noble/assetlist.json, osmosis/assetlist.json, stafihub/assetlist.json, stride/assetlist.json, teritori/assetlist.json, terra2/assetlist.json, testnets/_non-cosmos/avalanchetestnet/assetlist.json, testnets/_non-cosmos/binancesmartchaintestnet/assetlist.json, testnets/_non-cosmos/moonbeamtestnet/assetlist.json, testnets/_non-cosmos/polygontestnet/assetlist.json, testnets/entrypointtestnet/assetlist.json, testnets/junotestnet/assetlist.json, testnets/nobletestnet/assetlist.json
Add Check for valid Asset Pointer References
under traces and image_sync
there were several corrections required.
Check for self references to avoid infinite loops
=> Add Check for valid Asset Pointer References

osmosis/versions.json
fixing broken JSON, how did this pass?
=> Fix Broken Osmosis::versions.json

migaloo/assetlist.json
=> Add $WIND to Migaloo Assetlist 

carbon/chain.json
https://scan.carbon.network/governance/proposal/356?net=main
https://scan.carbon.network/block/57636191?net=main
=> Upgrade Carbon to v2.43.0 and update history

osmosis/assetlist.json, terra2/assetlist.json
Closes https://github.com/cosmos/chain-registry/pull/4674
Not giving credit to deter airdrop hunters.
=> Fix spelling typos

.github/workflows/validate_versionsjson.yml, versions.schema.json
-Add Versions Schema Validation YML on PR
-prevent additional properties on the schema
=> Add Versions Schema Validation YML on PR

osmosis/assetlist.json
Corrects the file name in the URLs.
=> fix: Osmosis' COCA Image URL

neutron/chain.json
https://governance.neutron.org/proposals/37
https://www.mintscan.io/neutron/block/10525000
=> Upgrade Neutron to v3.0.5

testnets/mantrachaintestnet/assetlist.json
Fix Testnet Mantrachain $OM
was additional-mintage, but should be test-mintage
=> Fix Testnet Mantrachain $OM

sei/chain.json
https://www.mintscan.io/sei/proposals/55
https://www.mintscan.io/sei/block/79123881
=> Upgrade Sei to v5.5.2

stargaze/assetlist.json
Here are the denom_traces for confirmation
CDT: https://rest.cosmos.directory/stargaze/ibc/apps/transfer/v1/denom_traces/B0263C28B6F44651F4596413B41FDB749EA010BD1220816DAC0ABF9947C1E806
MBRN: https://rest.cosmos.directory/stargaze/ibc/apps/transfer/v1/denom_traces/E94BB144B818CB8061F43E202BEA1E9273B87D6326C8C6F4E6AE71C62FD37854
This should fix the errors from PR #4718
=>  Add CDT & MBRN ics20s to Stargaze

osmosis/assetlist.json
Registering allUSDT - v3 transmuter pool
https://celatone.osmosis.zone/osmosis-1/contracts/osmo1em6xs47hd82806f5cxgyufguxrrc7l0aqx7nzzptjuqgswczk8csavdxek
Logo to use standard USDT logo until alloyed logo designed.
=> Add allUSDT

cosmoshub/chain.json
Add GetBlock's public endpoints to the list
=> Add GetBlock RPC to Cosmoshub

README.md, _template/assetlist.json, _template/chain.json
Update Schema Templates to help with convention for new submissions
-removes the legacy property logo_URIs
-adds a value into the empty coingecko_id property
=> Update Schema Templates

nibiru/chain.json
=> fix: Nibiru wss

chihuahua/chain.json
https://www.mintscan.io/chihuahua/proposals/75
https://www.mintscan.io/chihuahua/block/12900000
=> Upgrade Chihuahua to v7

osmosis/assetlist.json
Update Osmosis Assetlist, a batch generated from Osmosis-Labs' assetlists
=> Bulk Update Osmosis Assetlist

quicksilver/assetlist.json
Add Noble USDC via Dydx (USDC rewards) as asset on Quicksilver
=> add noble usdc via dydx (dydx rewards) as asset on Quicksilver

lumnetwork/chain.json
https://www.mintscan.io/lum/proposals/107
=> Upgrade Lum Network to v1.6.7

althea/assetlist.json
Fix Althea Assetlist Schema
add `$schema` property to Althea assetlist.json
=> Fix Althea Assetlist Schema

composable/assetlist.json
$WHINE from Solana via Picasso IBC
=> Register $WHINE on Composable's Assetlist

agoric/chain.json, agoric/versions.json
https://ping.pub/agoric/gov/74
=> Update agoric/chain.json for agoric-upgrade-15

sei/chain.json
Added evm-json rpc section and providers to Sei mainnet APIs
@JeremyParish69 or @dylanschultzie please review
=> Adds evm-rpc section + nodes to Sei

dymension/chain.json
From discord announcement: https://ptb.discord.com/channels/956961633165529098/1202591036174499881/1208446420999209041
=> Add fixed_min_gas_price to dymension

dydx/chain.json
https://www.mintscan.io/dydx/proposals/59
https://www.mintscan.io/dydx/block/17560000
=> Upgrade DYDX to v5.0.0

zetachain/chain.json
https://zetachain.explorers.guru/proposal/23
https://zetachain.explorers.guru/block/3388200
=> Upgrade Zetachain to v17

stride/chain.json
Update STRD fees on Stride
as per https://github.com/chainapsis/keplr-chain-registry/blob/9a7d37ecd076df83743951277bd38ef18396b84a/cosmos/stride.json#L137
=> Update STRD fees on Stride

gitopia/chain.json, neutron/chain.json
=> Quokka Stake: added Neutron, removed Gitopia

sge/chain.json
https://explorer.tcnetwork.io/sge/proposal/9
https://explorer.tcnetwork.io/sge/block/3976350
=> Upgrade SGE Network to v1.7.0

akash/chain.json
https://www.mintscan.io/akash/proposals/257
https://www.mintscan.io/akash/block/16708237
=> Upgrade Akash to v0.36.0

haqq/chain.json
https://haqq.explorers.guru/proposal/34
https://haqq.explorers.guru/block/11567000
=> Upgrade Haqq to v1.7.6

chihuahua/assetlist.json
=> add ampGASH IBC

_IBC/noble-shido.json
noble-shido transfer through IBC
=> add shido-noble ibc

testnets/archwaytestnet/chain.json
Closese https://github.com/cosmos/chain-registry/issues/4805
=> Update Archway Testnet RPC

osmosis/assetlist.json
Remove Socials for allUSDT 
Shouldn't be Osmosis--should inherit from USDT
=> Remove Socials for allUSDT

_non-cosmos/ethereum/assetlist.json
=> Add Tether Socials

movement/assetlist.json
fix: Movement $MOVE image URI
was looking at the wrong directory before
=> fix: Movement $MOVE image URI

testnets/celestiatestnet3/chain.json
add peer, api, rpc, grpc, explorer for Celestia Testnet (mocha-4)
=> add services CrypTech team

osmosis/assetlist.json
=> Update Osmosis Assetlist

assetlist.schema.json, chain.schema.json
Add Image Properties to assetlist and chainlist schema: monochrome (boolean), background_color_hex (hex{6,8] | "none")
=> Add Image Properties: Monochrome, Background Hex

_non-cosmos/solana/assetlist.json, chihuahua/assetlist.json, injective/assetlist.json, osmosis/assetlist.json, realio/assetlist.json, sge/assetlist.json
socials, extend_description, and image theme data for several assets
WHINE, BADDOG, SGE, RIO, SHITMOS, NINJA
=> Add additional metadata for several assets

bitcanna/chain.json
=> Update chain list with curate data

akash/chain.json
update fixed_min_gas_price
This is a fix discovered out of of https://github.com/akash-network/support/issues/231
=> Update fixed min gas price on Akash chain

testnets/celestiatestnet/chain.json
=> feat: change status of blockspacerace to killed

osmosis/assetlist.json
Update Osmosis Assetlist for USDT Variants' Images
=> Update Osmosis Assetlist for USDT Variants' Images

_non-cosmos/composablepolkadot/assetlist.json
Update Composable Polkadot Assetlist
Correct the traces to use "Polkadot Parachain", and not "Polkadot Relay"
=> Update Composable Polkadot Assetlist Traces

realio/chain.json
Proposal : https://explorer.realio.network/proposals/9
Block height : https://explorer.genznodes.dev/realio/block/7526754
additional
- edit seed and peers genznodes
- correcting binary
cc @jiujiteiro
=> Upgrade Realio to v0.9.3

testnets/sunrisetestnet/chain.json
Add new node 
persistent_peers and endpoints
=> Add Sunrise testnet new node

_non-cosmos/arbitrum/assetlist.json, _non-cosmos/base/assetlist.json, _non-cosmos/polygon/assetlist.json, axelar/assetlist.json, carbon/assetlist.json
Register WETHs on Arbitrum, Polygon, Base, and all those bridged to Axelar
=> Register WETHs on Arbitrum, Polygon, Base, and Axelar 

cosmoshub/chain.json
=> update cosmos hub mainnet info

bandchain/chain.json, gitopia/chain.json, nibiru/chain.json, planq/chain.json, self/chain.json, sentinel/chain.json, sge/chain.json, source/chain.json
Dear Team,
Please review our update data.
Best Regards
=> Update data Roomit Validator

testnets/archwaytestnet/assetlist.json
- Add images 
- Add logo URIS
- Add socials
=> Add images and logo uris for Archway testnet

humans/chain.json
Replacing the server, replacing information about the service provider PPNV Service
=> Update information about the service provider PPNV Service

_non-cosmos/picasso/assetlist.json
Add PICA Coingecko_id in Picasso assetlist
=> Add PICA Coingecko_id

stargaze/chain.json
Previous commit was mistakenly discarded.
=> Upgrade Stargaze to v14

_non-cosmos/ethereum/assetlist.json
Remove mention of CENTER for USDC
=> Update USDC Description

_IBC/neutaro-osmosis.json
=> Add neutaro-osmosis ibc path

_IBC/noble-shido.json
update IBC channel information between shido-noble
=> update channel of shido-noble IBC

_IBC/firmachain-osmosis.json
https://www.mintscan.io/osmosis/tx/022B127D87B60D274C2470BEBB54CDFAE64800C6B3E2B4097099B4B4AAA2F22C?height=17857913&sector=logs
```sh
$ rly tx link firmachain-osmosis
2024-07-12T17:11:44.675246Z	info	Clients created	{"src_client_id": "07-tendermint-1", "src_chain_id": "colosseum-1", "dst_client_id": "07-tendermint-3236", "dst_chain_id": "osmosis-1"}
2024-07-12T17:11:44.675367Z	info	Starting event processor for connection handshake	{"src_chain_id": "colosseum-1", "src_client_id": "07-tendermint-1", "dst_chain_id": "osmosis-1", "dst_client_id": "07-tendermint-3236"}
2024-07-12T17:11:44.723964Z	info	Chain is not yet in sync	{"chain_name": "firmachain", "chain_id": "colosseum-1", "latest_queried_block": 13295016, "latest_height": 13295036}
2024-07-12T17:11:45.720148Z	info	Chain is in sync …
```
=> Create ibc channel firmachain-osmosis.json

meme/assetlist.json, planq/assetlist.json
https://rest.cosmos.directory/planq/ibc/apps/transfer/v1/denom_traces/747FF58D3F211497581252CEBE11D7E785FC1E53AC5C29497A361E3830F1AF4A
https://rest.cosmos.directory/meme/ibc/apps/transfer/v1/denom_traces/FACC1CE598366EA01D86CF1CBE05F1A6C7511F673E91DEFF04342ED8DEFE3A60
=> Add meme on planq and plq on meme network

archway/chain.json
Added RPC provider address for LuckyFriday (aka GlobalStake)
=> Update chain.json to include RPC Provider Address for LuckyFriday

empowerchain/chain.json
Update Empowerchain Chain Logo
using the MPWR token logo
=> Update Empowerchain Chain Logo

axelar/chain.json
Update Axelar Chain Logo
Specifying the circular logo as an optional chain logo.
=> Update Axelar Chain Logo

pryzm/assetlist.json, pryzm/chain.json, pryzm/versions.json
This PR intends to add a few more metadata around PRYZM chain, like fee currencies and software versions.
=> Update Pryzm chain info

_IBC/axelar-pryzm.json, _IBC/celestia-pryzm.json, _IBC/cosmoshub-pryzm.json, _IBC/injective-pryzm.json, _IBC/noble-pryzm.json, _IBC/osmosis-pryzm.json, _IBC/pryzm-terra2.json
This PR intends to add the ICA channels between Pryzm and other chains to the list of IBC channels.
=> Add ICA channels for Pryzm IBC connections

osmosis/assetlist.json
Register Alloyed ETH $allETH to Osmosis Assetlist
=> Register Alloyed ETH $allETH to Osmosis Assetlist

noble/assetlist.json
Extend USDY Registration
Socials and extended description
=> Extend USDY Registration

osmosis/assetlist.json
Correct allETH to 18 exponent. Was mistakenly left at 8 before
=> Correct allETH to 18 exponent

_non-cosmos/arbitrum/assetlist.json, _non-cosmos/avalanche/assetlist.json, _non-cosmos/base/assetlist.json, _non-cosmos/ethereum/assetlist.json, _non-cosmos/optimism/assetlist.json, _non-cosmos/polygon/assetlist.json
Add USDC variants
mintages and bridged versions on Arbitrum, Base, Optimism, Polygon, and Avalanche
=> Add USDC variants

_non-cosmos/arbitrum/assetlist.json, _non-cosmos/base/assetlist.json, _non-cosmos/optimism/assetlist.json
Fix ETH/WETH Registrations on L2s
Arbitrum, Optimism, Base
=> Fix ETH/WETH Registrations on L2s

_non-cosmos/base/assetlist.json
Fix Base USDC.base denom
has an extra space at the end
=> Fix Base USDC.base denom

bitcanna/chain.json
=> Remove Bitcanna Peer

osmosis/assetlist.json
=> Register $allSOL to Osmosis

_non-cosmos/arbitrum/assetlist.json, _non-cosmos/avalanche/assetlist.json, _non-cosmos/binancesmartchain/assetlist.json, _non-cosmos/polygon/assetlist.json
Register USDT and Bridged USDT Variants
on Arbitrum, Avalanche, Polygon, and Binance Smart Chain
=> Register USDT and Bridged USDT Variants

noble/assetlist.json
=> Add USDY Coingecko ID

nim/assetlist.json
=> Add coingecko_id

likecoin/chain.json
https://x.com/mintscanio/status/1803324836980334650
=> Remove mintscan from likecoin

terpnetwork/chain.json
Seems like a leading space was accidentally committed here
=> Remove leading space from URL

_IBC/bandchain-stride.json, _IBC/pryzm-stride.json
=> Add IBC connections between Stride and Pryzm+Bandchain

sentinel/chain.json
=> Add rpc & api endpoint for Sentinel

dydx/chain.json
https://www.mintscan.io/dydx/proposals/125
https://www.mintscan.io/dydx/block/21142000
=> Upgrade DYDX to v5.1.0

_non-cosmos/ethereum/chain.json
Update Ethereum Chain_id from "0x1" to "1"
=> Update Ethereum Chain_id

sentinel/chain.json
Updated Trinity Stake RPC and API domain for Sentinel chain
=> Sentinel: updated Trinity Stake RPC and API domain

_IBC/archway-osmosis.json
Add icahost and icqhost support to IBC archway osmosis channels
=> Add icahost and icqhost support to IBC archway osmosis channels

_IBC/lava-osmosis.json
Register lava-osmosis.json IBC Connection
=> Register lava-osmosis.json IBC Connection

osmosis/assetlist.json
Register Penumbra to Osmosis Assetlist
as an ICS20 asset
=> Register Penumbra to Osmosis Assetlist

osmosis/assetlist.json
Register Tron and tron::USDT on Osmosis Assetlist
=> Register Tron and USDT on Osmosis Assetlist

osmosis/assetlist.json
Fix Tron Registration on Osmosis
Correcting Bridge Name to Nitro
=> Fix Tron Registration on Osmosis

osmosis/assetlist.json
fixes https://github.com/cosmos/chain-registry/issues/5088
please confirm the correct address field is deleted
=> deduplicate osmosis assetlist tron usdt address field

gateway/chain.json, noble/chain.json
Remove Noble and Gateway Staking since it doesn't exist.
=> Remove Noble and Gateway Staking 

osmosis/assetlist.json
Update Provider Nitro to Router on Osmosis Tron assets
=> Update Provider Nitro to Router

osmosis/assetlist.json
=> Fix Osmosis' Penumbra $UM Decimals

osmosis/assetlist.json
=> Add Cosmo token to Osmosis

acrechain/chain.json, chain.schema.json, doravota/chain.json, okexchain/chain.json, panacea/chain.json, testnets/deardogetestnet/chain.json, testnets/doravotatestnet/chain.json, testnets/doravotatestnet2/chain.json
Improve Chain Codebase Objects' Versioning
added (or improved): language, consensus, cosmwasm, ibc, sdk.
Each can now have a repo, version, and tag
and many have a type (language, consensus, sdk)
=> Improve Chain Codebase Objects' Versioning

andromeda/chain.json
Update date AviaOne BlockChains Service 🟢
=> Update AvioOne Endpoints Andromeda

bitcanna/chain.json
=> Update AvioOne Endpoints Bitcanna

gravitybridge/chain.json
=> Update AvioOne Endpoints Gravity Bridge

kichain/chain.json
=> Update AvioOne Endpoints Ki

provenance/chain.json
=> Update AvioOne Endpoints Provenance

routerchain/chain.json
- add node_home
- correct slip44
- fix chain_id
- genznodes seed node
cc @Iamshashvat
=> Update chain.json routerchain

testnets/mantrachaintestnet/chain.json
- For Hongbai testnet (testnet from MANTRA Finance), an issue has been noticed with wallet integration in the frontend, this PR propose to resolve it with updating the variable `bech32_prefix`
=> Update bech32_prefix to fix wallet error in the frontend

routerchain/chain.json
-  Proposal: https://router.explorers.guru/proposal/169
-  Add evm-http-jsonrpc
=> Upgrade Router to v2.1.6

lava/chain.json, testnets/symphonytestnet/chain.json
- coin name was originally set to the testnet name.  amended to coin
- coin originally did not have alias.  added
=> Symphony Testnet: amend coin name and alias

axelar/assetlist.json, osmosis/assetlist.json
=> Register allOP and OP.axl

dydx/chain.json
https://www.mintscan.io/dydx/proposals/130
https://www.mintscan.io/dydx/block/22170000
@reversesigh please see 🙏
=> Upgrade DYDX to v5.2.0

ibc_data.schema.json, testnets/_IBC/osmosistestnet-symphonytestnet.json
Add IBC Channel Validation
must start with "channel-"
fix osmosistestnet-symphonytestnet.json
=> Add IBC Channel Validation

haqq/assetlist.json
Update Deen Gold stablecoin to Trace to Gold
=> Update Deen Gold stablecoin to Trace to Gold

kujira/assetlist.json
Added several LP items for new BOW pairs and renamed a couple assets to match the `.origin` canon.
=> Update Kujira assetlist with new LPs

fxcore/chain.json
proposal: https://pundiscan.io/fxcore/proposals/63
block: https://pundiscan.io/fxcore/block/16838000
=> Upgrade fxcore to v7.5.0

versions.schema.json
Update versions.schema.json, add replacement properties
language, ibc, cosmwasm, sdk, consensus and move binaries to defs
=> Update versions.schema.json, add replacement properties

agoric/versions.json, fix_sdk_version.py, lava/versions.json, osmosis/versions.json, pryzm/versions.json, versions.schema.json
Update Versions Files with latest Data into the replacement properties
=> Update Versions Files with latest Data

injective/assetlist.json
Register Injective USDT via Peggy
=> Register Injective USDT via Peggy

injective/assetlist.json
Correct decimals and include cw20 info
=> Update drugs asset info

_IBC/doravota-noble.json
New channels requested by Dora team, maintained by [CryptoCrew](https://ccvalidators.com)
=> Add IBC `doravota-noble`

testnets/celestiatestnet2/chain.json
This Celestia testnet got upgraded to https://github.com/celestiaorg/celestia-app/releases/tag/v2.0.0 recently so I updated the list of versions to reference it. Also the existing explorer link was broken so I replaced it with Celenium.
Tagging @jcstein for review
=> feat: update arabica-11

_IBC/injective-secretnetwork.json
```
$ hermes --config config.toml query  connection end --chain injective-1 --connection connection-101 
```
outputs
```
2024-08-25T14:58:47.655057Z  INFO ThreadId(01) running Hermes v1.10.1+7a67ac51 SUCCESS ConnectionEnd {
state: Open,
client_id: ClientId(
"07-tendermint-126",
),
counterparty: Counterparty {
client_id: ClientId(
"07-tendermint-49",
),
connection_id: Some(
ConnectionId(
"connection-30",
),
),
prefix: ibc,
},
versions: [
Version {
identifier: "1",
features: [
"ORDER_ORDERED",
"ORDER_UNORDERED",
],
},
],
delay_period: 0ns,
}
```
=> Fix client/connections for Injective <> Secret channels

stride/assetlist.json
Updated the token - stISLM from Stride network added CoinGeckoID
=> Updated the token - stISLM added CoinGeckoID

_IBC/lorenzo-osmosis.json
Register IBC between Lorenzo and Osmosis.
=> Add IBC `lorenzo-osmosis`

lorenzo/assetlist.json
Update `description` and `extended description` fields of stBTC.
=> Update Lorenzo `assetlist.json`

testnets/celestiatestnet3/chain.json
Tagging @jcstein @JeremyParish69  for review
=> feat: update mocha-4

lorenzo/assetlist.json
=> Add Lorenzo $stBTC Socials

lorenzo/assetlist.json
Update stBTC as a BTC Liquid Stake in Trace
=> Update stBTC Trace for BTC Liquid Stake

oraichain/assetlist.json
Update the Name of Oraichain's TON Bridge
to Oraichain Labs TON Bridge
=> Update the Name of Oraichain's TON Bridge

sentinel/chain.json
Updated Sentinel Growth Dao RPC and API domain
=> Updated Sentinel Growth Dao RPC and API domain

nibiru/assetlist.json, testnets/nibirudevnet/assetlist.json, testnets/nibirudevnet2/assetlist.json, testnets/nibirudevnet3/assetlist.json, testnets/nibirudevnet4/assetlist.json, testnets/nibirutestnet/assetlist.json, testnets/nibirutestnet2/assetlist.json
=> chore: fix evm denoms for Nibiru

osmosis/assetlist.json
Adds the Alloyed TON token to Osmosis.
@JeremyParish69 we're missing the allTON logos here - requested creation
=> Add allTON

osmosis/assetlist.json
=> Update CosmoUSD asset

unification/chain.json
- Updates for latest chain upgrade (5-pike, v1.10.x)
- Correct Cosmos & Consensus versions in older releases
- Add latest version to versions array
- Update explorer information
=> Update Unification (FUND) Chain

quasar/chain.json
=> Fix Quasar Versions

testnets/dhealthtestnet/chain.json
- Add grpc endpoint
- Add seeds & persistent_peers
=> Update dHealth Testnet

oraichain/assetlist.json, osmosis/assetlist.json
Add ORAI socials; Extended Description for TON.orai and Osmosis TON alloy
=> Add ORAI socials; Extended Description for TON.orai and TON alloy

osmosis/assetlist.json
Update assetlist.json- add extended description for nRide token
=> Update assetlist.json- add extended description for nRide token

testnets/lavatestnet/chain.json
updates the rpc entry with the new rpc endpoints
=> update lava testnet rpc entry

testnets/kimatestnet/chain.json
Updated Fee information to list assets to Osmosis testnet.
=> update fee information

_non-cosmos/polygon/assetlist.json
Update $MATIC to $POL
to reflect recent upgrade
=> Update $MATIC to $POL

testnets/_IBC/junotestnet-symphonytestnet.json
old channel expired.  new one had to be put up
=> symphony testnet: update juno channel

oraichain/assetlist.json, oraichain/chain.json
Update ORAI Logo Image Theme data
=> Update ORAI Logo Image Theme data

shido/chain.json
update persistent peers and change the IBC version
=> chore:update persistent peers and change the IBC version

assetlist.schema.json, composable/assetlist.json
Add IBC-Bridge Trace Type for the bridges that use IBC methods, but don't connect with Cosmos chains
=> Add IBC-Bridge Trace Type

thorchain/images/rune.svg
Upload Square RUNE Logo
previous one was not square
=> Upload Square RUNE Logo

neutron/chain.json
added dRPC endpoints to the list of RPCs
=> Add Neutron RPC "dRPC"

axelar/chain.json
added dRPC to the list of RPCs
https://drpc.org/chainlist/axelar
=> Add Axelar RPC "dRPC"

.github/workflows/utility/validate_data.mjs, akash/assetlist.json, archway/assetlist.json, carbon/assetlist.json, composable/assetlist.json, injective/assetlist.json, neutron/assetlist.json, oraichain/assetlist.json, osmosis/assetlist.json, sei/assetlist.json, terra2/assetlist.json, testnets/osmosistestnet/assetlist.json
Add Validation Check for IBC Denom Accuracy
uses path to determine the expected IBC denom (base denom), and throws an error if there is a mismatch.
=> Add Validation Check for IBC Denom Accuracy

oraichain/chain.json
added Oraichain explorer and RPC information provided by IM Dev
=> Add ORAI Explorer imORAI

cronos/chain.json
added dRPC endpoints to the list
=> Add dRPC Endpoint to Cronos

dymension/chain.json
Added dRPCs RPC endpoint to the list of Dymension RPCs
=> Add dRPC Endpoint to Dymension

evmos/chain.json
Added dRPCs Evmos RPC Endpoint to the list
=> Add dRPC Endpoint to Evmos

haqq/chain.json
Added dRPCs RPC Endpoint to the list
=> Add dRPC Endpoint to Haqq

kava/chain.json
Added dRPCs Kava RPC Endpoint to the list
=> Add dRPC Endpoint to Kava

osmosis/chain.json
Added dRPCs Osmosis RPC to the RPC endpoint list
=> Add dRPC Endpoint to Osmosis

zetachain/chain.json
Added dRPCs ZetaChain RPC endpoint to the list.
=> Add dRPC Endpoint to ZetaChain

README.md, _template/assetlist.json, _template/chain.json
Update Readme Examples and Template Files
=> Update Readme Examples and Template Files

pryzm/chain.json, pryzm/versions.json
This PR adds the new version of Pryzm to the list of versions.
=> Update Pryzm with v0.19

_non-cosmos/internetcomputer/assetlist.json, osmosis/assetlist.json
Register ckBTC to Osmosis
it was already registered under Internet Computer
=> Register ckBTC to Osmosis

testnets/unificationtestnet/chain.json, unification/chain.json
Added `wss`  to `apis` array for Unification:
- MainNet
- TestNet
=> Unification (FUND) - add websockets to APIs

testnets/_non-cosmos/bitcointestnet/assetlist.json
Register Bitcoin Testnet
Just an assetlist for now
=> Register Bitcoin Testnet

sei/chain.json
also fix v5.7.5 wrong height/prop #
=> Upgrade sei to v5.8.0

blockx/chain.json
add explorer & rpc & api for blockx network
=> add explorer & rpc & api for blockx network

osmosis/assetlist.json
adding socials for bernesechain
=> Update assetlist.json - adding socials for bernesechain

_IBC/akash-doravota.json, _IBC/coreum-doravota.json, _IBC/doravota-dydx.json, _IBC/doravota-injective.json, _IBC/doravota-nolus.json, _IBC/doravota-sei.json, testnets/doravotatestnet2/chain.json
=> update doravota ibc relayer and remove vota-vk

_non-cosmos/optimism/assetlist.json
Register Optimism Bridged USDT
=> Register Optimism Bridged USDT

assetlist.schema.json, kimanetwork/assetlist.json, testnets/kimanetworktestnet/assetlist.json
Update Properties of Socials
before, additional properties were allowed--now set to false.
website and twitter/X were already there.
adds: discord, telegram, github, medium, reddit.
does NOT add: linkedin, fb, insta, tiktok, google+, myspace, notion.
=> Update Properties of Socials

testnets/stridetestnet/assetlist.json
Added the following assets to stride's testnet:
* ibc/TIA
* stTIA
* ibc/dv4tnt
* stDV4TNT
=> added stride testnet stdydx and sttia

injective/assetlist.json
Update denom of DRUGS. Tokens has been reminted prior to distrobution due to an issue with the token factory type used and decimals changed from 9 to 6
=> Update injective assetlist.json

axelar/assetlist.json
Register Axelar USDT variants from ARB, OP, POL
=> Register Axelar USDT variants from ARB, OP, POL

axelar/assetlist.json
Register Bitcoin L2s on Axelar
=> Register Bitcoin L2s on Axelar, FBTC, LBTC, cbBTC

agoric/chain.json, agoric/versions.json
https://ping.pub/agoric/gov/78
=> Set agoric to version agoric-upgrade-17

_non-cosmos/bitcoincash/assetlist.json, _non-cosmos/dogecoin/assetlist.json, _non-cosmos/litecoin/assetlist.json
Add Socials for BCH, LTC, DOGE
=> Add Socials for BCH, LTC, DOGE

testnets/cosmosicsprovidertestnet/chain.json
Testnet upgraded from `v20.0.0-rc0` to `v20.0.0`
=> Update ICS testnet to Gaia v20.0.0

cudos/chain.json
Update v9.9.9 will close the chain following a merger into the ASI Alliance chain
=> update for Cudos v9.9.9 release

noble/chain.json
Add some endpoint for noble network which provider by OWALLET
+ Rpc
+ Rest API (lcd)
+ grpc
=> Add owallet public endpoints for Noble network

atomone/assetlist.json
=> Register AtomOne Socials

.github/workflows/utility/validate_data.mjs
Add Validate Check for Unique base denoms within an Assetlist
=> Add Validate Check for Unique base denoms within an Assetlist

bluzelle/assetlist.json
Add BeeZee Extended Description
=> Add BeeZee Extended Description

beezee/assetlist.json
Update BeeZee $BZE Description
=> Update BeeZee $BZE Description

neutaro/assetlist.json
We've added the extended description, website and twitter. Also added Timpis website in the extended description because I wasn't sure if I can have more than one website.
=> Update Neutaro in assetlist.json

testnets/nilliontestnet/chain.json
https://docs.nodex.one/networks/testnet/nillion
https://services.kjnodes.com/testnet/nillion
=> Update Nillion Testnet

omniflixhub/assetlist.json, osmosis/assetlist.json
Correct Symbol for SPICE on Osmosis
Also corrected order for Omniflix assetlist
=> Correct Symbol for SPICE on Osmosis

akash/chain.json
Added Bro_n_Bro endpoints for akash.
=> Add Bro_n_Bro endpoints for akash

axelar/assetlist.json
=> Add axlWETH CoinGecko ID

dungeon/chain.json
=> Add Dungeon Chain Fee Rates

dungeon/chain.json
Register Dungeon Slip44 as 118
=> Register Dungeon Slip44

stargaze/assetlist.json
Added an object for shitmos support on stargaze.
=> add shitmos object to assetlist.json in chain-registry/stargaze

.github/workflows/utility/chain_registry.mjs, .github/workflows/utility/chain_registry_local.mjs, .github/workflows/utility/validate_data.mjs
Add validation that chain_name value matchs Directory name
=> Add validation that chain_name value matchs Directory name

_IBC/kimanetwork-osmosis.json, kimanetwork/chain.json
Recently there are some problem to drive internal relayer so we wanna update IBC information with new setup as we discussed already.
=> Update Kima mainnet IBC information

_non-cosmos/statemine/assetlist.json
Add Missing Trace for Statemine USDT
=> Add Missing Trace for Statemine USDT

jackal/chain.json
We are going to shutdown Jackal's public endpoints
=> 🚀 WHEN MOON 🌕 WHEN LAMBO 🔥 Remove RPC, API and Explorer endpoints from Jackal 

synternet/chain.json
=> Add Slip44 for Synternet

.github/workflows/utility/validate_data.mjs, blockx/chain.json, chimba/chain.json, synternet/chain.json, terpnetwork/chain.json, testnets/babylontestnet/chain.json, testnets/babylontestnet1/chain.json, testnets/blockxtestnet/chain.json, testnets/chimbatestnet/chain.json, testnets/fiammatestnet/chain.json, testnets/metanovaversetestnet/chain.json, testnets/ulastestnet/chain.json
Instead of the JSON Schema, it's in the Node JS file, because there are a few conditions for the requirement, and not just blanket requirement for all.
Assumes 118 for all chains where it was missing.
=> Add SLIP44 Requirement Validation

dydx/chain.json
As per https://www.mintscan.io/dydx/proposals/173
@reversesigh pls see
=> Upgrade dydx chain to v7.0

_IBC/passage-picasso, _IBC/passage-picasso.json
SUCCESS Channel {
ordering: Unordered,
a_side: ChannelSide {
chain: BaseChainHandle {
chain_id: ChainId {
id: "centauri-1",
version: 1,
},
runtime_sender: Sender { .. },
},
client_id: ClientId(
"07-tendermint-225",
),
connection_id: ConnectionId(
"connection-118",
),
port_id: PortId(
"transfer",
),
channel_id: Some(
ChannelId(
"channel-80",
),
),
version: None,
},
b_side: ChannelSide {
chain: BaseChainHandle {
chain_id: ChainId {
id: "passage-2",
version: 2,
},
runtime_sender: Sender { .. },
},
client_id: ClientId(
"07-tendermint-8",
),
connection_id: ConnectionId(
"connection-8",
),
port_id: PortId(
"transfer",
),
channel_id: Some(
ChannelId(
"channel-7",
),
),
version: None,
},
connection_delay: 0ns,
}
=> Create passage-picasso IBC configuration

bitcanna/chain.json
=> Upgrade Bitcanna v4.0.1

osmosis/assetlist.json
Update Osmosis assetlist.json in bulk from generated file from Osmosis Labs
=> Bulk Update Osmosis assetlist.json

axelar/assetlist.json, cosmoshub/assetlist.json, juno/assetlist.json, kava/assetlist.json, noble/assetlist.json, stargaze/assetlist.json
CrowdP is the token of Crowdpunk DAO. Crowdpunk is a visual representation of an AI Agent functioning as a Rating Agency for interchain projects. In particular Stargaze and Omniflix are used to distribute the Interchain Impact Rating (IIR) and provide video content.
=> add crowdp on axelar, cosmos hub, juno, kava, noble, stargaze

archway/chain.json, comdex/chain.json, coreum/chain.json, juno/chain.json, osmosis/chain.json, pryzm/chain.json, quasar/chain.json, saga/chain.json, shentu/chain.json, stargaze/chain.json, teritori/chain.json
This PR aims to add Chainroot resources and endpoints to chain-registry
=> feat: add Chainroot resources and info

_IBC/dungeon-migaloo.json, _IBC/dungeon-terra2.json, migaloo/assetlist.json, terra2/assetlist.json
Add DGN IBC:
Terra:
ibc/B2AA4C3CD19954859C3B537EC0705640AFC01075F52993D9AC5E73F07F0386CC
Migaloo:
ibc/D24B4564BCD51D3D02D9987D92571EAC5915676A9BD6D9B0C1D0254CB8A5EA34
Register IBC Channels:
dungeon channel-6 <> migaloo channel-142
dungeon channel-7 <> terra2 channel-582
=> Add DGN to Terra, Migaloo; Register IBC Channels

routerchain/chain.json, routerchain/versions.json
Proposal: https://router.explorers.guru/proposal/197
=> Router upgrade to v2.2.4

osmosis/assetlist.json
Register Ripple $XRP Alloy to Osmosis
=> Register Ripple $XRP Alloy to Osmosis

_IBC/axelar-xion.json, _IBC/injective-xion.json, _IBC/noble-xion.json, _IBC/osmosis-xion.json
=> Add `xion` initial ibc paths

xion/assetlist.json, xion/chain.json
@JeremyParish69 Is this enough for asset verification on Osmosis?
=> expand description of xion network

archway/chain.json, archway/versions.json
=> update archway mainnet

_IBC/dhealth-osmosis.json
According to: https://ping.pub/osmosis/gov/866
=> Update dHealth IBC client_id

osmosis/assetlist.json
Register Internet Computer $ICP on Osmosis
Bridged via Omnity Network
=> Register Internet Computer $ICP on Osmosis

testnets/elystestnet/assetlist.json, testnets/elystestnet/chain.json
Elys testnet chain was upgraded to ICS chain.
=> Update Elys testnet

impacthub/assetlist.json, impacthub/chain.json, impacthub/versions.json
- Improved the description
- Updated the references to Interchain stack versions
- Removed the entry for mintscan explorer
=> Updates post chain upgrade

osmosis/chain.json, osmosis/versions.json
=> Update Osmosis to Version v28

elys/chain.json
=> Add Quasar grpc, rpc, api

fetchhub/assetlist.json
We want to add the social media links for our project to the chain registry.
=> Add socials to MOBIX

elys/chain.json, elys/versions.json
add new versions of Elys Network
=> chore: add elys versions

realio/chain.json, realio/versions.json
https://explorer.genznodes.dev/realio/gov/14
=> Update Realio to v1.0.2

bitcanna/chain.json
=> Updated BitCanna chain.json

dungeon/chain.json
=> Update Quasar 🤖🧬🧠 api,rpc chain.json

elys/assetlist.json
**Added asset definitions for Akash (AKT), Celestia (TIA), Xion (XION), and Saga (SAGA) to asselist.json.**
This commit includes:
* Trace information for IBC channels.
* References to logo and image URLs.
* Denom units and aliases for each asset.
This update enhances the asset registry by providing comprehensive information for these new assets.
=> Update Elys assetlist.json

cosmoshub/assetlist.json
Update dungeon ibc cosmoshub assetlist.json
=> Update dungeon ibc cosmoshub assetlist.json

atomone/chain.json
Add AviaOne's 
-Rpc
-Api
-Grpc
-Seed
-Peers
-explorer
=> Update AtomOne chain.json

atomone/chain.json
=> Add Citizen Web3 endpoints to AtomOne

terra2/assetlist.json
Update assetlist.json:
ampWHALE/WHALE ampLPs from Eris Protocol
bWHALE/WHALE ampLPs from Eris Protocol
=> Add ampLP denoms to Terra 2.0

README.md
Update README.md to recommend SLIP-0173 Registration
minor cleanup
=> Update README.md to recommend SLIP-0173 Registration

atomone/chain.json
=> Update peers on AtomOne chain.json

agoric/chain.json, agoric/versions.json
https://ping.pub/agoric/gov/83/
=> set agoric to version `agoric-upgrade-18`

osmosis/assetlist.json
=> Update Osmosis Assetlist (batch 12)

fetchhub/chain.json
=> Updated fetchhub chain.json adding seed node

provenance/assetlist.json
Add configuration for USDC from Noble over IBC.  
See example TX here: https://www.mintscan.io/noble/tx/7615A42B06F7B279F81B92D6C6CE847FB2642FA4427E94F40256F58EFE09A4E8?sector=message
=> Update assetlist.json to add USDC from Noble

testnets/_IBC/axelartestnet-manifesttestnet.json
Add a ibc config file to for the axelar testnet to manifest testnet ibc channel
=> add axelartestnet to manifesttestnet ibc config file

milkyway/assetlist.json, milkyway/chain.json, milkyway/versions.json
This PR updates the MilkyWay chain config to include the new version as well as the support for USDC
=> chore: update MilkyWay

testnets/xiontestnet/chain.json, testnets/xiontestnet/versions.json, testnets/xiontestnet2/chain.json, testnets/xiontestnet2/versions.json, xion/assetlist.json, xion/chain.json, xion/versions.json
- add bech32_config for all xion chains
- add codebase info for all xion chains
- add seed and peers for xiontesnet2
- set xiontestnet2 to live
=> Set xiontestnet2 to live

testnets/prysmdevnet/chain.json
=> prysmdevnet update chain.json

.github/workflows/check_coingecko_data.yml, .github/workflows/utility/chain_registry.mjs, .github/workflows/utility/check_coingecko_data.mjs, .github/workflows/utility/state/coingecko.json, _non-cosmos/ethereum/assetlist.json, carbon/assetlist.json, chihuahua/assetlist.json, chronicnetwork/assetlist.json, coss/assetlist.json, crescent/assetlist.json, dungeon/assetlist.json, finschia/assetlist.json, injective/assetlist.json, juno/assetlist.json, migaloo/assetlist.json, oraichain/assetlist.json, point/assetlist.json, shareledger/assetlist.json, sifchain/assetlist.json, terra2/assetlist.json
Add Workflow to update current state of CoinGecko IDs
this will allow PR validation to check whether new coingecko id entries are valid, while also not complaining and failing checks whenever old coingecko IDs (that were valid on CoinGecko at one time) are removed from CoinGecko.
and code to bulk remove any coingecko IDs that are no longer invalid.
Also there is some manual clean up of coingecko ids and a few token names to align better with coingecko.
=> Add Workflow to update current state of CoinGecko IDs and remove invalid coingecko IDs 

shido/chain.json
added new evm RPC for shidochain
=> chore:added new evm RPC of shidochain

terra/chain.json
1. Add terra rpc api endpoint
2. Add terra lcd api endpoint
3. Add terra grpc endpoint
=> Add terra APIs in chain

.github/workflows/utility/chain_registry.mjs, .github/workflows/utility/coingecko_data.mjs, .github/workflows/utility/state/coingecko.json, .github/workflows/utility/update_coingecko_data.mjs, .github/workflows/utility/validate_data.mjs, testnets/_non-cosmos/ethereumtestnet/assetlist.json, testnets/desmostestnet/assetlist.json, testnets/junotestnet/assetlist.json, testnets/kichaintestnet/assetlist.json
Add Coingecko PR Validation
Adds coingecko ID checks and reports which ones are missing from the API or which are suspected to be invalid. 
Adds some Testnet test-mintage traces
=> Add Coingecko PR Validation

.github/workflows/utility/validate_data.mjs, _non-cosmos/binancesmartchain/assetlist.json, testnets/elystestnet/assetlist.json, testnets/jackaltestnet/assetlist.json, testnets/ulastestnet/assetlist.json
=> Add Fixes to CGID Validation

osmosis/assetlist.json
Register 3 Alloys (DYDX, AIOZ, FET) to Osmosis Assetlist
=> Register 3 Alloys (DYDX, AIOZ, FET) to Osmosis Assetlist

.github/workflows/utility/chain_registry.mjs, .github/workflows/utility/coingecko_data.mjs, .github/workflows/utility/state/coingecko.json, .github/workflows/utility/update_coingecko_data.mjs, .github/workflows/utility/validate_data.mjs, acrechain/assetlist.json, andromeda1/assetlist.json, archway/assetlist.json, highbury/assetlist.json, odin1/assetlist.json, terra/assetlist.json
Update coingecko_id Validation Logic
preps for updating all related assets with the same coingecko_id, next PR...
=> Update coingecko_id Validation Logic

agoric/chain.json, agoric/versions.json
https://ping.pub/agoric/gov/86/
=> set agoric to version agoric-upgrade-18a

akash/chain.json
Deletes dead nodes and adds alive nodes for Akash Network
=> fix: update chain.json for Akash Network. (delete inactive nodes)

testnets/_non-cosmos/ethereumtestnet/assetlist.json
Register Ethereum Testnet (Sepoila) USDT
=> Register Ethereum Testnet (Sepoila) USDT

milkyway/chain.json
This PR updates `milkyway` gas prices
=> fix: update MilkyWay gas prices

nomic/chain.json
Update Nomic Fee Tokens (removing sat)
Removing sat(nBTC) just leaves NOM.
=> Update Nomic Fee Tokens (removing sat)

testnets/zenrocktestnet/chain.json
This PR bumps the gardia chain-id from `gardia-3` to `gardia-4`.
=> update gardia chain-id

stargaze/assetlist.json
This adds the necessary info for BIKE IBC'd from Mantrachain to Stargaze.
=> Added BIKE token to Stargaze assetlist.json

fxcore/assetlist.json, fxcore/chain.json
Hi, @JeremyParish69 
query gas price: https://fx-rest.functionx.io/cosmos/base/node/v1beta1/config
Ref: 
https://github.com/cosmos/chain-registry/pull/5974#issuecomment-2691368713
https://github.com/cosmos/chain-registry/pull/5983
=> Update fxcore min gas price

osmosis/assetlist.json
Fix Osmosis Alloys Images (DYDX, AIOZ, FET)
=> Fix Osmosis Alloys Images (DYDX, AIOZ, FET)

kopi/assetlist.json
added extended_description to XKP
=> added extended_description to XKP

stargaze/assetlist.json
New info includes: a proper description, an extended description, and socials.
=> revisions to HOOD token on assetlist.json

osmosis/assetlist.json
Adds the Hood object to the assetlist.json on osmosis chain subdirectory.
=> update assetlist.json for Hood token on Osmosis

testnets/_IBC/axelartestnet-manifesttestnet.json, testnets/_IBC/manifesttestnet-osmosistestnet.json, testnets/axelartestnet/assetlist.json, testnets/manifesttestnet/assetlist.json, testnets/osmosistestnet/assetlist.json
This pr updates the ibc channel info for manifest and its connected chains.
=> update ibc-channel info for manifest testnet

atomone/chain.json, atomone/versions.json, testnets/atomonetestnet/chain.json, testnets/atomonetestnet/versions.json
=> Upgrade Atomone version

_non-cosmos/polygon/assetlist.json
=> Update WMATIC to contain POL

osmosis/assetlist.json, stargaze/assetlist.json
Add T7S as an asset on Stargaze, from Osmosis.
=> create assetlist.json object for t7s on chain-registry/stargaze

axelar/chain.json, persistence/chain.json, testnets/axelartestnet/chain.json
Update QuantNode resources
Changed URLs for Axelar and Persistence, removed grpcweb for Axelar, added grpc for Persistence
Added Axelar Testnet resources Rest, Rpc, Grpc
=> Update QuantNode resources

_IBC/manifest-osmosis.json, manifest/assetlist.json, osmosis/assetlist.json
This pr adds the ibc config file for manifest -> osmosis and updates the asset lists of both chains with the native tokens
=> add: ibc assets and ibc connection manifest - osmosis

six/chain.json, six/versions.json, testnets/sixtestnet/chain.json, testnets/sixtestnet/versions.json
chore: change version compatible
chore: change RPC/API Path
=> Update Six and Sixtestnet--version compatible

_IBC/nillion-osmosis.json
Register nillion-osmosis.json IBC Connection
=> Register nillion-osmosis IBC Connection

nillion/chain.json
Updated nillion gas prices to reflect validators settings.
=> Update: nillion gas prices

dungeon/chain.json
updated gas-prices matching current keplr gas changes.
=> Update chain.json @Dungeon

testnets/babylontestnet/assetlist.json
The previous PR got merged, but we have a most up-to-date address.
=> fix: update ebaby cw20 address

akash/chain.json, kyve/chain.json
Updating based on
https://github.com/chainapsis/keplr-chain-registry/pull/1085
=> Kyve gas step update

fxcore/assetlist.json, migaloo/assetlist.json
- Update Twitter link from functionx_io to PundiAI in fxcore/assetlist.json
- Fix typo in migaloo/assetlist.json: change "despoited" to "deposited" in USDC description
=> Fix Twitter link for PundiAI and correct typo in Migaloo description

dungeon/chain.json
Fix Dungeon Chain Logo
needed an images array for full functionality on other apps
=> Fix Dungeon Chain Logo

osmosis/chain.json, osmosis/versions.json, testnets/osmosistestnet/chain.json, testnets/osmosistestnet/versions.json
Osmosis v29 Upgrade
Update Osmosis mainnet to v29
correct Osmosis Testnet to v29
=> Osmosis v29 Upgrade

_IBC/axelar-jackal.json
Reverting to other channels now that clients are open again.
=> Updating Jackal Axelar IBC Channels

akash/chain.json
=> Added Arcturian Tech

atomone/chain.json
AtomOne services:
- RPC
- API
- gRPC
- Explorer
=> Update chain.json (ChatinTools AtomOne Endpoints)

babylon/chain.json
Register Babylon Explorers
Mintscan and Node Guru
=> Register Babylon Explorers

osmosis/assetlist.json
Fix Reference to Image solvBTC.atom in Osmosis Assetlist
=> Fix Reference to Image solvBTC.atom in Osmosis Assetlist

assetlist.schema.json, osmosis/assetlist.json
=> Update Osmosis assetlist.json

.github/workflows/check_coingecko_data.yml
=> Fix Coingecko Data Action

agoric/chain.json, agoric/versions.json
https://ping.pub/agoric/gov/91
=> set agoric to version agoric-upgrade-19

allora/chain.json, chihuahua/chain.json, dydx/chain.json, empowerchain/chain.json, evmos/chain.json, gitopia/chain.json, humans/chain.json, juno/chain.json, lava/chain.json, loyal/chain.json, nillion/chain.json, nois/chain.json, omniflixhub/chain.json, quicksilver/chain.json, seda/chain.json, sei/chain.json, sge/chain.json, stargaze/chain.json, stride/chain.json, teritori/chain.json
Multiple seed and rpc cleanups across existing and past chains for services provided.
=> Add RHINO provider entries to various chain configurations

akash/chain.json, althea/chain.json, arkeo/chain.json, atomone/chain.json, axelar/chain.json, bitcanna/chain.json, celestia/chain.json, cosmoshub/chain.json, doravota/chain.json, dydx/chain.json, dymension/chain.json, fetchhub/chain.json, injective/chain.json, irisnet/chain.json, juno/chain.json, kava/chain.json, omniflixhub/chain.json, osmosis/chain.json, persistence/chain.json, regen/chain.json, stargaze/chain.json, testnets/celestiatestnet3/chain.json, testnets/dydxtestnet/chain.json, testnets/persistencetestnet2/chain.json, umee/chain.json, zetachain/chain.json
PR to add valopers.com explorers
=> Add valopers.com explorers

elys/chain.json, evmos/chain.json
1) elys endpoints: seed, peer, rpc, api, grpc
2) deleted deprecated evmos' support info
=> update endpoints by Pro-Nodes75

testnets/xplatestnet/chain.json, xpla/chain.json
XPLA used fixed gas prices.
You can check it here.
https://dimension-lcd.xpla.dev/ethermint/feemarket/v1/base_fee
=> fix: xpla gas prices

atomone/chain.json
add provider BonyNode rpc/api/grpc/explorer
=> Update chain.json add provider

.github/state/coingecko.json, .github/workflows/utility/coingecko_data.mjs, _non-cosmos/arbitrum/assetlist.json, haqq/assetlist.json, persistence/assetlist.json, secretnetwork/assetlist.json
Update Internal Coingecko Data Management + Remove some Invalid IDs
Cannot be inside the workflows directory, apparently, because a Github App doesn't have permissions to modify that directory (so cannot use an Action to update this)
=> Update Internal Coingecko Data Management + Remove some Invalid IDs

babylon/assetlist.json
Quick update to align name and symbol
=> fix(asset): update name and symbol for satUniBTC

initia/chain.json
Fix Initia Description
Had an invalid field before (extended_description)
=> Fix Initia Description

elys/chain.json
=> vNodesV domain update

omniflixhub/assetlist.json
I wasn't able to check if the IBC denom was correct by sending some test assets because keplr doesn't support this asset, and I couldn't make it work on dao dao either. fingers crossed that the sha256 hash calculation was constructed correctly.
=> Create json object for CCD on omniflixhub assetlist.json

cosmoshub/assetlist.json, osmosis/assetlist.json
WBTC - 8 exponent
ETH - 18 exponent
Tested transfers to confirm
=> Adjust exponent for eureka asset registrations

testnets/junotestnet/chain.json
Add Kleomedes REST/RPC endpoints and stake-hub link
=> Add Juno Endpoints & Explorer for Kleomedes

testnets/xplatestnet/chain.json
Please change the pretty name to differentiate XPLA and XPLA Testnet.
=> Update pretty name for xpla testnet

akash/chain.json
We have observed some behaviour on these nodes that impact the performance of some components. This PR removes a couple nodes from the list that are either offline or unreliable.
=> chore(akash): cleanup akash node list

.github/workflows/utility/validate_data.mjs
Update slip44 verification check.
Should pass even if 0
=> Update slip44 verification check

osmosis/assetlist.json
Update T7S Socials
as per TG dm. Old Twitter account doesn't exist
=> Update T7S Socials

sentinel/assetlist.json
=> Update dVPN symbol to P2P

kopi/assetlist.json
Register Kopi's website
as per their twitter
=> Register Kopi's website

testnets/manifestdevnet/chain.json, testnets/manifesttestnet/chain.json
Bump Manifest devnet & testnet gas price.
CC @chalabi2
=> fix: manifest testnet gas price

osmosis/assetlist.json
Add OPHIR to Osmosis Assetlist
=> Add Ophir To Osmosis

cosmoshub/assetlist.json
Add OPHIR to cosmoshub/assetlist as double-wrapped IBC denom
IBC Full Path
Migaloo [5] -> [642] Osmosis [0] -> [141] Cosmos Hub
=> Add OPHIR to cosmoshub/assetlist

osmosis/assetlist.json
adding X profile link to Stealth coin
=> Update Stealth socials

noble/chain.json
Updates atom gas price to be in line with the network wide minimum enforced by noble's global fee module.
=> update atom gas price for noble

_IBC/bitbadges-osmosis.json
This pull request adds the newly created BitBadges x Osmosis IBC connection to _IBC.
=> add bitbadges-osmosis connection

.github/workflows/utility/chain_registry.mjs
Update Validation Code to Better Find IBC files
=> Update Validation Code to Better Find IBC files

osmosis/assetlist.json
=> Register NAM to Osmosis

_IBC/akash-stargaze.json
adds akash<-> stargaze
sample: https://www.mintscan.io/akash/tx/9CC083D3B1730575F13214A059684E18ADC2287A758EBE185D1C0DE8B4D41E5E?height=22009219
=> ibc: add akash-stargaze route

testnets/_IBC/hippoprotocoltestnet-osmosistestnet.json
adds hippoprotocoltestnet <-> osmosistestnet
=> Add hippoprotocoltestnet ibc channels

osmosis/assetlist.json
Fix XRP.xrplevm Decimals on Osmosis
was incorrectly set to 0
=> Fix XRP.xrplevm Decimals on Osmosis

noble/assetlist.json
Update Noble USDN Metadata 
Add Extended Description and Coingecko ID
=> Update Noble USDN Metadata 

taketitan/assetlist.json, taketitan/chain.json, taketitan1/assetlist.json, taketitan1/chain.json
fixed take titan chain configurations as previous details was completely not aligned with running chain
=> fixed take titan chain configurations 

_IBC/bitbadges-noble.json
Adds BitBadges <-> Noble IBC connection
=> add bitbadges-noble connection

qubetics/assetlist.json
add coingecko id in qubetics mainnet chain
=> chore:add coin gecko id

pryzm/assetlist.json
Register PRYZM Socials and Coingekco ID
Details taken from Coingecko (and appear correct)
=> Register PRYZM Socials and Coingekco ID

_IBC/hippoprotocol-osmosis.json, hippoprotocol/chain.json
added missing grpc information, ibc channel between hippoprotocol <-> osmosis
=> Add hippoprotocol grpc, ibc channel

agoric/chain.json, agoric/versions.json
https://www.mintscan.io/agoric/proposals/99
=> set version to agoric-upgrade-21

_non-cosmos/picasso/assetlist.json
=> Rename Pica to Picasso (PICA)

routerchain/chain.json, routerchain/versions.json
=> Upgrade Routerchain to v2.2.8

pryzm/assetlist.json, pryzm/chain.json
This PR intends to
1. Add PRYZM Base LP and PRYZM / USDC LP tokens to the list of assets.
2. Add PRYZM token to the list of gas fees.
=> Update Pryzm list of assets

dydx/chain.json, dydx/versions.json
* proposal: https://www.mintscan.io/dydx/proposals/261
* upgrade height: https://www.mintscan.io/dydx/block/50240951
=> Update dydx to v8.2

pryzm/chain.json
This PR increases the AUUU gas fee on Pryzm chain.
=> Update Pryzm gas fee

terra2/assetlist.json
change the description of CAPA, SOLID and the name of CAPA
=> change the description of CAPA, SOLID and the name of CAPA

osmosis/assetlist.json
Register TRUMP and PENGU to Osmosis
the alloys
=> Register TRUMP and PENGU to Osmosis

osmosis/assetlist.json
Update Osmosis Assetlist 16
as per generated output.
=> Update Osmosis Assetlist (Bulk Update 16)

bandchain/chain.json, bandchain/versions.json
- update BandChain v3 info.
- update seeds and peers.
=> Update BandChain v3 info

_IBC/cosmoshub-intento.json, _IBC/intento-osmosis.json
=> Add `ibc` cosmoshub-intento

osmosis/chain.json
been live for quite some time, forgot to update here!
=> Add rpc/rest on Osmosis for High Stakes

chain4energy/chain.json
- Add/update POLCRYPTO endpoints:
- RPC:  https://rpc.polcrypto.pl
- REST: https://rest.polcrypto.pl
- gRPC: grpc.polcrypto.pl:443
- Explorer:
- url:         https://explorer.polcrypto.pl
- tx_page:     https://explorer.polcrypto.pl/tx/${txHash}
- account_page:https://explorer.polcrypto.pl/account/${accountAddress}
Notes:
- Ports normalized to HTTPS defaults (no :443 in URLs).
- Endpoints live and synced; CORS enabled on REST.
=> chain4energy: update POLCRYPTO endpoints (rpc/rest/grpc) + explorer URLs

chain.schema.json, union/chain.json, union/versions.json, versions.schema.json
CometBLS:  https://github.com/unionlabs/cometbls
Used on: Union
=> Add support for CometBLS consensus

atomone/chain.json, doravota/chain.json, union/chain.json
=> update chain union ruangnode

wardenprotocol/assetlist.json, wardenprotocol/chain.json, wardenprotocol/versions.json
=> Add Warden Protocol mainnet

atomone/assetlist.json
PHOTON is now listed on coingueko
https://www.coingecko.com/en/coins/photon-2
=> chore(atomone): add PHOTON coingueko_id
