terra/chain.json

Peers and genesis from https://github.com/terra-money/mainnet, and node config tested in cosmos omnibus https://github.com/ovrclk/cosmos-omnibus/pull/38

Add Terra config and peers

---

sifchain/chain.json

Sourced from https://github.com/Sifchain/networks/tree/master/betanet/sifchain-1

Add Sifchain

---

bitcanna/chain.json

adding peers and services endpoints

adding peers and services endpoints

---

bandchain/chain.json

Added peers and api and updated genesis and codebase.

Update Band config

---

provenance/chain.json

Adds chain registration information for the Provenance Blockchain mainnet.

Add provenance blockchain registration

---

secretnetwork/chain.json

Added PR to add Secret Network chain info

added secret network chain.json

---

comdex/chain.json

Updating comdex chain details.

---

starname/chain.json

Source: https://github.com/iov-one/starnamed#phase-1-of-2

Added more data to starname chain.json

---

comdex/chain.json

comdex | updating explorer details.

Comdex | Updating explorer details

---

thornode/chain.json

THORChain is a decentralised liquidity network built with CosmosSDK.
https://gitlab.com/thorchain/thornode

Add THORNode chain info

---

panacea/chain.json
stargaze/chain.json

add stargaze explorer

---

dig/assetlist.json
dig/chain.json

Hi, we are Notional and here is Dig Chain. Please review us!

Add Dig Chain

---

assetlist.schema.json
chain.schema.json

downgrade schemas

---

dig/assetlist.json
dig/chain.json

the old API and RPC endpoint of dig are not correct, so we change with new stable ones

add dig API and RPC endpoint

---

akash/chain.json
cosmoshub/chain.json
juno/chain.json
osmosis/chain.json
sentinel/chain.json
terra/chain.json

Add Strangelove Archive nodes to available RPCs

---

sifchain/assetlist.json

Minimum viable asset list for Sifchain.

Create `assetlist.json` for Sifchain

---

chihuahua/chain.json

https://twitter.com/ChihuahuaChain/status/1477947408562757632

Mintscan explorer for Chihuahua

---

desmos/chain.json

RPC and REST endpoints for Desmos network

---

injective/chain.json

Signed-off-by: Nikola Marcetic <n.marcetic86@gmail.com>
This PR updates [Injectiveprotocol](http://injectiveprotocol.com/) chain data.

Update Injective Chain Info

---

cosmoshub/chain.json

Update to vega.
Add key algos, fees, binaries & explorers.

Update Hub chain.json

---

stargaze/assetlist.json

added coingecko_id 
https://www.coingecko.com/en/coins/stargaze

Added stargaze coingecko_id 

---

chihuahua/assetlist.json

added coingecko_id as per [https://www.coingecko.com/en/coins/chihuahua-token](https://www.coingecko.com/en/coins/chihuahua-token)

Added chihuahua coingecko_id

---

cosmoshub/chain.json
osmosis/chain.json

change osmosis, delete cosmoshub chainapsis apis to prevent congestion.

Change / Delete chainapsis apis

---

cronos/assetlist.json
cronos/chain.json

Adding Cronos Chain to chain-registry.

Adding Cronos Chain

---

chihuahua/chain.json

https://github.com/ChihuahuaChain/mainnet/tree/main/UPGRADES/angryandy

Update Chihuahua to v1.1.1

---

README.md

Changing sample Keplr.app endpoints to blockapsis.com in the README.md file.

Update README.md (Modify Keplr endpoints)

---

osmosis/chain.json

https://github.com/osmosis-labs/osmosis/releases/tag/v6.1.0

[osmosis] 5.0.0 -> 6.1.0

---

terra/chain.json

https://github.com/terra-money/core/releases/tag/v0.5.14

terra 0.5.9 -> 0.5.14

---

terra/chain.json

https://github.com/terra-money/core/releases/tag/v0.5.16

[terra] v0.5.15 -> v0.5.16

---

gravitybridge/assetlist.json

Updating chain_id to gravity-bridge-3, as it should agree with chain.json

Update to grave-bridge-3

---

osmosis/chain.json

https://github.com/osmosis-labs/osmosis/releases/tag/v6.4.0

[osmosis] v6.3.0 -> v6.4.0

---

terra/chain.json

https://github.com/terra-money/core/releases/tag/v0.5.17

[terra] v0.5.16 -> v0.5.17

---

akash/chain.json

update akash code version

---

osmosis/chain.json

https://github.com/osmosis-labs/osmosis/releases/tag/v7.0.3

[osmosis] v7.0.2 -> v7.0.3

---

arkh/chain.json

Update Arkh status

---

persistence/chain.json

Fix indentation

---

axelar/assetlist.json
axelar/chain.json

- Added Axelar mainnet chain and assets

add axelar

---

axelar/assetlist.json

update axelar assets

---

cosmoshub/chain.json

I goofed up ¯\_(ツ)_/¯
Thanks @philipjames44 and @boojamya

Fix missing comma Cosmos Hub

---

cosmoshub/chain.json

Update Cosmoshub version

---

crescent/assetlist.json
crescent/chain.json

Ref
- https://github.com/crescent-network/asset
- https://github.com/crescent-network/chain-registry
- https://github.com/crescent-network/crescent
- https://github.com/crescent-network/launch
- https://docs.crescent.network/introduction/what-is-crescent

Add Crescent Network assetlist, chain

---

cosmoshub/chain.json

Adds the goodest cosmoshub nodes. 
* zoomiez 
* will play fetch with protobufs

Add Pupmøs Public Nodes ❤️

---

provenance/chain.json

Updated the information for Provenance's chain.json

Provenance Update: Update Chain.json

---

echelon/assetlist.json
echelon/chain.json

Add Echelon (ECH)

---

assetmantle/assetlist.json
assetmantle/chain.json

Genesis and peers are from: https://github.com/AssetMantle/genesisTransactions/tree/main/mantle-1. Not sure if we want to list all peers?
The logo image is a Github avatar right now, but I can inline it in this repo if that's preferred. 
Rushed together for restake.app but happy to make any changes needed.

Add AssetMantle

---

README.md

Inspired by #289 , wanted to collect existing projects.

Update readme with web interfaces and apis

---

decentr/chain.json

Please @megaherz confirm informations :)

Accurate informations for Decentr

---

crescent/chain.json
juno/chain.json
sommelier/chain.json

Adds the goodest Crescent, Juno, and Sommelier nodes. 
* zoomiez
* can hear packets coming from miles away
* has yet catch own tail. but will never stop trying. success is imminent.

Add More Pupmøs Public Nodes ❤️ (CRE, JUNO, SOMM)

---

evmos/chain.json

Update evmos/chain.json with the data for mainnet relaunch

fix: update evmos

---

assetlist.schema.json

update assetlist schema

---

juno/assetlist.json

correct NETA base and first denom (exp:0) from 'uneta' to 'cw20:<contract address>'

correct NETA base denom

---

sommelier/assetlist.json

now it's correct ;)  --> sommelier

fix coingecko_id

---

assetmantle/assetlist.json

coingecko_id was updated on CG

---

fetchhub/chain.json

Version 10.3 is the new HIGHLY recommended version because of security vulnerabilities in the previous versions.

Update for v0.10.3

---

osmosis/chain.json

Update Osmosis version to 8.0.0

Update Osmosis version 8

---

stargaze/chain.json

Adds the goodest Stargaze nodez.
* Very fast response times when not looking for bacon on the floor
* Can smell upgrades coming from miles away
* Likes REST endpoints because you cannot have the zoomiez without the snooziez

Add Pupmøs nodes for Stargaze  ❤️

---

persistence/chain.json

current seeds are not reachable

Update persistence seeds

---

evmos/chain.json

- adding new provider for; grpc, rest, rpc.

Update evmos chain.json

---

rizon/chain.json

RIZON: update chain information

---

README.md
chain.schema.json
osmosis/chain.json

Add explorer acct page
resolves #82

Add block explorer account page

---

_non-cosmos/polkadot/assetlist.json
_non-cosmos/polkadot/images/dot.svg

-add dot.svg and an assetlist.json file

Add polkadot

---

_non-cosmos/moonbeam/assetlist.json

Add wrapped dot to moonbeam

---

umee/chain.json

update umee chain.json

---

echelon/chain.json

Update Echelon to v1.0.3

---

cosmoshub/chain.json
crescent/chain.json
juno/chain.json
sommelier/chain.json
stargaze/chain.json

Minor label tweaks as well as adding the seed nodes that we provide.

[PUPMØS] Node updates.

---

juno/assetlist.json

logo URIs to point to chain reg.
display denom to be a valid denom unit

Fix DLA listing

---

assetmantle/chain.json
axelar/chain.json
umee/chain.json

Notional update endpoints: 
- add Notional endpoints to axelar
- add Notional endpoints to umee
- remove Notional endpoints to assetmantle (ref https://github.com/notional-labs/cosmosia/issues/70)

Notional update endpoints: add axelar and umee; remove assetmantle

---

rizon/assetlist.json

https://www.coingecko.com/en/coins/rizon

add coingecko_id for $ATOLO

---

gravitybridge/assetlist.json

https://www.coingecko.com/en/coins/graviton

add coingecko_id for $GRAV

---

axelar/assetlist.json

misc. erc20s: ape, axs, ... uni, xcn, from Ethereum + DOT & WGLMR from Moonbeam

Add Axelar assets

---

echelon/chain.json

Adds two new explorers for Echelon and v1.1.4 Release

Update to v1.1.4 Echelon Release and added new explorers

---

testnets/theta/chain.json

Hi! I have updated the following fields:
- `recommended_version`
- `compatible_versions`
- `binaries`
- `seeds`
- `persistent_peers`
They now match the [playbook](https://github.com/hyphacoop/cosmos-ansible/blob/main/examples/inventory-theta.yml) we use to join the testnet.
Closes #551.

Update Theta testnet metadata

---

juno/chain.json

[PUPMØS] Juno seed Id

---

akash/chain.json

- update seeds, peers, nodes;
- bump akash from 0.14.1 to 0.16.3 as it's currently latest version where we've got the [consensus](https://discord.com/channels/747885925232672829/751246770885099533/1002623974318014485).

akash: update chain and nodes, peers

---

microtick/chain.json

due to chain halt
https://explorer.microtick.zone/proposals/20

set microtick chain status to killed

---

README.md
chain.schema.json
osmosis/chain.json

to chain schema, readme, and osmosis
closes #126

Add staking metadata

---

cerberus/chain.json

Change the seed node from Blockpane node to Polkachu node

Blockpane no longer support Cerberus

---

regen/chain.json

Update regen to `v4.0.0` and add missing properties and explorers.

update regen chain.json

---

README.md
bostrom/chain.json
emoney/chain.json

Hi,
We've created our own version of a directory like ping.pub for the community. We've also released support for e-Money and Bostrom, so we'd like to be added to their blockchain explorer list too.
Thanks team!

Adds ATOMScan directory and 2 more chains

---

odin/chain.json

- update github repo
- add ping explorer

update odind version

---

crescent/assetlist.json

fix cre img urls

---

kava/assetlist.json

Fix Kava lend coingecko id
Closes https://github.com/cosmos/chain-registry/issues/606

Fix Kava lend coingecko id

---

agoric/chain.json
bandchain/chain.json
cerberus/chain.json
crescent/chain.json
juno/chain.json
oraichain/chain.json
persistence/chain.json
sifchain/chain.json
testnets/saagetestnet/chain.json

to keep consistent, updating all URLs to include same template string syntax.

fix: explorer template strings

---

sentinel/chain.json

Added RPC for Sentinel chain

---

emoney/assetlist.json
emoney/chain.json
oraichain/assetlist.json

Bulk update denoms

---

bandchain/chain.json
chronicnetwork/chain.json
cryptoorgchain/chain.json
fetchhub/chain.json
irisnet/chain.json
konstellation/chain.json
lumenx/chain.json
odin/chain.json
omniflixhub/chain.json
panacea/chain.json
provenance/chain.json
regen/chain.json
rizon/chain.json
terra2/chain.json
umee/chain.json

-BandChain -> Band Protocol
-Crypto.org -> Crypto.org Chain
-Chronic -> Chronic Chain
-Fetch Hub -> Fetch.ai
-IRISnet iaa -> iris
-Konstellation Network -> Konstellation
-Lumen Network -> LumenX
-OdinChain -> Odin Protocol
-OmniFlix Hub -> OmniFlix
-Panacea -> Medibloc
-Provenance Blockchain -> Provenance
-Regen Network -> Regen
-RIZON -> Rizon
-Terra2 -> Terra 2.0
-umee -> Umee
to a name more 'proper', and to better match the SLIP173 registration. (Using Pretty_Name as a pk to search for SLIP-0173 registration)

Bulk Pretty Name corrections

---

bitcanna/chain.json
cerberus/chain.json
desmos/chain.json
passage/chain.json
shentu/chain.json

And also added Panthea EU endpoints to Passage chain

Added mintscan explorer account urls

---

juno/chain.json

A new seed node was created for the last chain restart.

Update blockpane seed

---

README.md

We've now created a directory of all Cosmos chains from the registry, automatically updating every hour.

Adds ATOMScan Directory to the README.md

---

README.md
chain.schema.json

Simple change that adds network website to chain list. 
If accepted, will go through and add a bunch manually.

Add websites to schema

---

injective/assetlist.json
injective/chain.json

INJ exponent: 6 -> 18
uinj -> inj
inj -> INJ

fix inj asset

---

canto/chain.json

Update Canto chain_id

---

echelon/chain.json

Add ech.world RPC, API and gRPC servers for Echelon

Add ech.world RPC, API and gRPC servers for Echelon

---

cosmoshub/chain.json

Updated genesis path and bump to latest gaiad version.

Update cosmoshub chain.json

---

echelon/chain.json

Add ech.world json-rpc addresses and modify provider name

Add ech.world json-rpc addresses and modify provider name

---

chain.schema.json
osmosis/chain.json

Fix historical versions matrix

---

_IBC/crescent-stargaze.json

chain-id : crescent-1
client_id : 07-tendermint-24
conneciton_id : connection-27
channel_id : channel-21
chain-id : stargaze-1
client_id : 07-tendermint-180
conneciton_id : connection-114
channel_id : channel-51

Add crescent<->stargaze

---

agoric/assetlist.json

Updates the Agoric token name to better represent what it is

fix: update Agoric token name

---

axelar/assetlist.json

replaces #432 
pending addition of traces...

add axlwmatic to Axelar assetlist

---

bitsong/chain.json
emoney/chain.json
sentinel/chain.json

I maintain 3 nodes serving RPC/API on sentinel, emoney and bitsong. Also I have one more cosmoshub node, will make a PR for it later as I still need to set up the nginx proxying and DNS.

feat: add freak12techno public nodes on bitsong, sentinel and emoney

---

bitcanna/chain.json

https://github.com/BitCannaGlobal/bcna/releases/tag/v1.4.2

Update software version

---

akash/chain.json
cheqd/chain.json
cosmoshub/chain.json
evmos/chain.json
juno/chain.json
kujira/chain.json
osmosis/chain.json
passage/chain.json
secretnetwork/chain.json
terra2/chain.json

Add Lavenderfive Endpoints

---

evmos/chain.json

Upgrade evmos to v8.1.0

---

akash/chain.json
cheqd/chain.json
cosmoshub/chain.json
evmos/chain.json
juno/chain.json
kujira/chain.json
osmosis/chain.json
passage/chain.json
secretnetwork/chain.json
terra2/chain.json

Add LavenderFive gRPC endpoints

---

ethos/chain.json
evmos/chain.json
logos/chain.json
mythos/chain.json

Add:
```
"key_algos": [
"ethsecp256k1"
],
```

Update key_algos for evmos, mythos, logos, ethos

---

bitcanna/chain.json
bitsong/chain.json
canto/chain.json
cerberus/chain.json
comdex/chain.json
desmos/chain.json
dig/chain.json
galaxy/chain.json
idep/chain.json
impacthub/chain.json
kichain/chain.json
konstellation/chain.json
lumnetwork/chain.json
odin/chain.json
omniflixhub/chain.json
stride/chain.json
vidulum/chain.json

Add Lavender.Five support for public endpoints

---

akash/chain.json
assetmantle/chain.json
bitcanna/chain.json
canto/chain.json
chihuahua/chain.json
comdex/chain.json
cosmoshub/chain.json
evmos/chain.json
fetchhub/chain.json
galaxy/chain.json
gravitybridge/chain.json
impacthub/chain.json
injective/chain.json
juno/chain.json
kava/chain.json
kichain/chain.json
konstellation/chain.json
kujira/chain.json
meme/chain.json
osmosis/chain.json
passage/chain.json
sifchain/chain.json
sommelier/chain.json
stargaze/chain.json
terra2/chain.json
umee/chain.json

Update networks with seeds/version/genesis

---

evmos/chain.json

new `low_gas_price` to reflect global minimum gas price

update evmos gas price and binary version

---

_IBC/osmosis-rebus.json

Added osmosis-rebus IBC

---

rebus/chain.json

Added missing RPC and API endpoints

Updated rebuschain rest and rpc endpoints

---

chihuahua/chain.json
firmachain/chain.json

Add public endpoints for Chihuahua and Firmachain

---

_IBC/agoric-gravitybridge.json

This is the json file containing the path metadata for the new IBC path between Agoric and Gravity Bridge.

Add agoric-gravitybridge.json

---

_IBC/gravitybridge-persistence.json
gravitybridge/assetlist.json

pstake traces

---

teritori/assetlist.json
teritori/chain.json
teritori/images/tori.svg

- initial declaration
- add SVG provided by team
- merge infos from Lavenderfive
Signed-off-by: dpierret <dapie@cros-nest.com>

Add teritori informations for chain-registry

---

juno/chain.json

update junod version, add Interbloc apis

---

axelar/assetlist.json

fix: update AXL coingecko id

---

panacea/chain.json

update the version of the Panacea chain

---

testnets/bitcannadev/chain.json

Update peers 
Provide a new name to differentiate from devnet-6.
Thanks 🙏

new peers & seeds

---

cosmoshub/chain.json

Architect Nodes Cosmoshub RPC/API

Architect Nodes Cosmoshub RPC/API

---

likecoin/chain.json

https://github.com/likecoin/likecoin-chain/releases/tag/v3.1.0

update liked version

---

sommelier/chain.json

Update Sommelier with dragonberry patch

---

akash/chain.json
bitsong/chain.json
canto/chain.json
cerberus/chain.json
chihuahua/chain.json
comdex/chain.json
evmos/chain.json
juno/chain.json
konstellation/chain.json
kujira/chain.json
omniflixhub/chain.json
rebus/chain.json
secretnetwork/chain.json
terra2/chain.json
umee/chain.json

Add missing fees for networks

---

meme/chain.json
rebus/chain.json
teritori/chain.json

* Added Brochain services to Rebus
* Added Brochain services to Teritori
* Corrected explorer links for Rebus

Added Brochain services

---

cosmoshub/chain.json
evmos/chain.json
juno/chain.json
osmosis/chain.json

Add Stakin's gRPC, RPC, and REST endpoints to chain.json of:
- Evmos
- Cosmoshub
- Juno
- Osmosis

Add Stakin endpoints to evmos,cosmoshub,juno,osmosis chain.json

---

cronos/chain.json
evmos/chain.json
juno/chain.json

- Add seeds from Jerry's Pool
- Add RPC from IcyCRO

Add seeds and RPCs from Jerry's Pool and IcyCRO

---

cosmoshub/chain.json

Add RPC and seeds for IcyCRO.org

Add seed and RPC for IcyCRO

---

bitsong/chain.json
evmos/chain.json

Added EVMOS/Bitsong API and RPC endpoints

Added EVMOS/Bitsong API and RPC endpoints

---

osmosis/chain.json
teritori/chain.json

Add New ibs.team endpoints

---

axelar/chain.json

Submitting our 3 Axelar RPC endpoints

Add Stakin endpoints to Axelar chain.json

---

jackal/chain.json

Add LavenderFive public Jackal endpoints

---

_IBC/osmosis-teritori.json

Create osmosis-teritori ibc json

---

okexchain/assetlist.json

fix: update okexchain `coingecko_id`

---

akash/chain.json

https://github.com/ovrclk/akash/releases/tag/v0.16.8

Upgrade Akash to 0.16.8

---

sifchain/chain.json

ref https://www.mintscan.io/sifchain/proposals/132

bump sifchain

---

chihuahua/chain.json
fetchhub/chain.json
jackal/chain.json
kujira/chain.json
persistence/chain.json
rebus/chain.json
teritori/chain.json

Adds Kleoemedes REST/RPC nodes for:
* Chihuahua
* FetchHub
* Jackal
* Kujira
* Persistence
* Rebus
* Teritori

Add more Kleomedes REST/RPC nodes

---

_IBC/osmosis-secretnetwork.json

the channel-id is not 39, but 44. Also, the placement was mixed up.

Fix secret-osmo IBC connection

---

teritori/chain.json

Remove bad seed from teritori

---

teritori/chain.json

Have added port for the seed node

Add kjnodes seed node for Teritori

---

chihuahua/chain.json
meme/chain.json

New endpoints for Chihuahua and Meme.

[PUPMØS] New endpoints

---

akash/chain.json

https://www.mintscan.io/akash/proposals/27
https://www.mintscan.io/akash/blocks/8526250

bump akash to 0.18.0 & 0.18.1

---

comdex/chain.json

https://github.com/comdex-official/comdex/releases/tag/v5.0.0

Upgrade Comdex to v5.0.0

---

omniflixhub/chain.json

https://www.mintscan.io/omniflix/blocks/4175400

Upgrade Omniflixhub to v0.8.0

---

testnets/stargazetestnet/chain.json

Check the ID yourself at https://testnet-explorer.publicawesome.dev/stargaze

fix stargaze testnet chain id

---

cosmoshub/chain.json
crescent/chain.json
juno/chain.json
sommelier/chain.json
stargaze/chain.json
stride/chain.json
teritori/chain.json

Our updated RPC/API endpoints.

[PUPMØS] Updated endpoints

---

aioz/chain.json
chain.schema.json
dig/chain.json
ethos/chain.json
evmos/chain.json
imversed/chain.json
injective/chain.json
logos/chain.json
mythos/chain.json
testnets/evmostestnet/chain.json

Related to https://github.com/cosmos/relayer/pull/1048

Specifying extra-codecs to distinguish between ethermint and injective

---

cudos/chain.json

- Update daemon version to v1.0.1
- Add "daemon_name" variable
Requested by Andrew Meredith (Cudo Blockchain SRE)

Update Cudos chain.json

---

canto/chain.json
dig/chain.json
galaxy/chain.json
vidulum/chain.json

Delete Lavender.Five endpoints

---

juno/assetlist.json

- add seasy
- add stakeeasy-juno-derivative
- add stakeeasy-bjuno

add coingecko_id's for stakeeasy

---

impacthub/chain.json

https://www.mintscan.io/ixo/proposals/13

Upgrade IXO to v0.19

---

konstellation/chain.json

https://github.com/knstl/konstellation

Update Konstellation git repo

---

comdex/chain.json

https://www.mintscan.io/comdex/proposals/25

Upgrade Comdex to v6.0.0

---

canto/chain.json

Update canto info

---

desmos/chain.json

https://www.mintscan.io/desmos/proposals/19

Upgrade Desmos to v4

---

evmos/chain.json
gravitybridge/chain.json
stride/chain.json
terra2/chain.json
umee/chain.json

Add our seed nodes to Umee, Stride, Terra2, Evmos, Gravity.
add umee' PRC endpoint

add seed' info

---

osmosis/chain.json

add OSL apis for Osmosis

---

_IBC/acrechain-osmosis.json
_IBC/echelon-osmosis.json
_IBC/medasdigital-osmosis.json
_IBC/odin-osmosis.json
_IBC/osmosis-terra2.json

new file:   _IBC/acrechain-osmosis.json
new file:   _IBC/echelon-osmosis.json
new file:   _IBC/medasdigital-osmosis.json
new file:   _IBC/odin-osmosis.json
new file:   _IBC/osmosis-terra2.json

Add missing IBC files

---

cerberus/chain.json
konstellation/chain.json

Remove public L5N from Konstellation, Cerberus

---

axelar/chain.json
persistence/chain.json

Adding missing QuantNode RPC endpoint for Axelar and Persistence

QuantNode RPCs

---

assetlist.schema.json
gravitybridge/assetlist.json

added: gweth, gwbtc, gdai, gusdc, gusdt

Add gravitybridge assets

---

chain.schema.json

allow for multiple up directories for schema reference

Fix chain schema validation for testnets schema

---

chain.schema.json

Add alt slip44s to chain schema
as array of numbers
closes #1077

Add alt slip44s array to chain schema

---

evmos/chain.json

proposal: https://www.mintscan.io/evmos/proposals/94
upgrade block: https://www.mintscan.io/evmos/blocks/9495000
upgrade time: `Tue Jan 03 2023 16:24:31 GMT-0000`

Upgrade EVMOS to v10.0.0

---

comdex/chain.json

proposal: https://www.mintscan.io/comdex/proposals/54
block: https://www.mintscan.io/comdex/blocks/5850600
estimated time: `Fri Jan 06 2023 06:02:46 GMT-0800 (Pacific Standard Time)`

Upgrade Comdex to v7.0.0

---

comdex/assetlist.json
sifchain/assetlist.json

was referencing exp:18 'rowan' as base denom. Now made it exp:0, and added 'rowan' exp:18 as display denom
-minor fromatting fix cmdx

Fix rowan base denom

---

secretnetwork/assetlist.json

Add type asset and address to Secretnetwork's snip20s
minor reformatting

Add type asset and address to snip20s

---

README.md
_IBC/genesisl1-osmosis.json
assetlist.schema.json
beezee/assetlist.json
crescent/assetlist.json
cudos/assetlist.json
decentr/assetlist.json
desmos/assetlist.json
gravitybridge/assetlist.json
ibc_data.schema.json
medasdigital/assetlist.json
provenance/assetlist.json
teritori/assetlist.json
tgrade/assetlist.json
vidulum/assetlist.json

-Remove empty arrays from various assetlist.json and reformat
-Add minContains: 1 to arrays
-small readme update to remove empty arrays
-fix genesisl1 ibc channel

Remove empty arrays in assetlists

---

osmosis/assetlist.json
stride/assetlist.json

Fix osmosis assetlist

---

testnets/terpnettestnet/chain.json

Updated peers & resources list for TerpNET's migrated test network (athena-3).
Thank you!

update Terp Network TestNET Resources

---

quicksilver/chain.json

Add quicksilver endpoints

---

_IBC/dyson-osmosis.json

This is the updated IBC info for dyson-osmosis

update dyson-osmosis IBC channel

---

lumnetwork/chain.json

block: https://www.mintscan.io/lum/blocks/5672000
proposal: https://www.mintscan.io/lum/proposals/34
estimated time: `Tue Jan 10 2023 08:04:05 GMT-0800 (Pacific Standard Time)`

Upgrade Lum to v1.3.0

---

kujira/chain.json

proposal: https://www.mintscan.io/kujira/proposals/81
block: 5196234
est: `2022-11-14 13:00:35`

Upgrade Kujira to v0.7.1

---

testnets/imversedtestnet/assetlist.json

{
"$schema": "../assetlist.schema.json",
"chain_name": "nyx",
"assets": [
{
"description": "NYM Token (NYM) is the Nym Network's native utility token, used as the primary means to incentivize mixnet node operators.",
"denom_units": [
{
"denom": "unym",
"exponent": 0
},
{
"denom": "NYM",
"exponent": 6
}
],
"base": "unym",
"name": "Nym",
"display": "nym",
"symbol": "NYM",
"logo_URIs": {
"png": "https://raw.githubusercontent.com/",
"svg": "https://raw.githubusercontent.com/"
},
"coingecko_id": "nym"
}
]
}

fix chain_name

---

_non-cosmos/binancesmartchain/assetlist.json

Add more BSC coins

---

omniflixhub/chain.json

add kingnodes omniflix services

---

_non-cosmos/avalanche/assetlist.json
axelar/assetlist.json

Add axlWAVAX and WAVAX Trace

---

testnets/_non-cosmos/avalanchetestnet/assetlist.json
testnets/_non-cosmos/binancesmartchaintestnet/assetlist.json
testnets/_non-cosmos/ethereumtestnet/assetlist.json
testnets/_non-cosmos/moonbeamtestnet/assetlist.json
testnets/_non-cosmos/polkadottestnet/assetlist.json
testnets/_non-cosmos/polygontestnet/assetlist.json
testnets/axelartestnet/assetlist.json
testnets/axelartestnet/chain.json

Add axelartestnet and L1 bridged testnets
ethereumtestnet, polygontestnet, avalanchetestnet, binancesmartchaintestnet, polkadottestnet

Add axelartestnet and L1 bridged testnets

---

testnets/_IBC/axelartestnet-osmosistestnet.json

registering some ibc connections for some testnets.
pending cosmoshubtestnet-osmosistestnet.json (foregoing for now)

Add testnet ibc folder

---

regen/chain.json

This pull request updates Regen to the latest version.

Update Regen to v5

---

injective/chain.json

Per the required mainnet INJ app.toml: https://github.com/InjectiveLabs/mainnet-config/blob/master/10001/app.toml#L11

Set minimum INJ gas price

---

injective/chain.json

proposal: https://www.mintscan.io/injective/proposals/198
block: 24204000
estimated time: `14:00 UTC on January 18th 2023`

Upgrade Injective to v1.9.0

---

injective/chain.json

Add Lavender.Five Injective support

---

gravitybridge/chain.json
lumnetwork/chain.json
provenance/chain.json

Add Inter Blockchain Services Endpoints

Add Inter Blockchain Services Endpoints

---

terra/chain.json

https://ping.pub/terra-luna/gov/11243

update gas prices as per proposal 11243

---

acrechain/assetlist.json
juno/assetlist.json

Fix HOPERS symbol and denom, fix arUSD exponent

Fix minor token Errors

---

canto/chain.json

Fees were way too low. Updates as per Canto FE

Update CANTO fee rates

---

quicksilver/assetlist.json

Add qSTARS trace

---

_IBC/osmosis-quicksilver.json

add osmosis-quicksilver ibc connection

Register osmosis-quicksilver ibc connection

---

stride/chain.json

Emergency upgrade, no associated proposal/etc.

Upgrade Stride to v5.1.1

---

decentr/chain.json
sentinel/chain.json

First of a couple of Pull Requests to update the cosmos chain registry with updated BadgerBite services node information.  This update includes decentr, and sentinel.

Add/Update some BadgerBite details

---

decentr/chain.json
sentinel/chain.json

Sorry about multiple PRs in rapid fire.  I forgot to remove the old non-working BadgerBite RPC endpoint from Sentinel.  Thanks for all the hard work you do!

Sorry, forgot to remove old BadgerBite RPC

---

juno/assetlist.json

https://www.coingecko.com/fr/pi%C3%A8ces/hopers

add coingecko id for hopers

---

cheqd/chain.json

proposal: https://ping.pub/cheqd/gov/12
block: 6427280
estimated time: `2023-01-30 02:16:24`

Upgrade Cheqd to v1.x

---

evmos/chain.json

ETA [2023-02-02 10:55:33](https://www.mintscan.io/evmos/proposals/112) GMT-5

update evmos for v11

---

bitsong/chain.json

proposal: https://www.mintscan.io/bitsong/proposals/15
block: https://www.mintscan.io/bitsong/blocks/9845000
est time: `Fri Feb 03 2023 07:08:01 GMT-0800`

Upgrade Bitsong to v0.13.0

---

impacthub/chain.json

The latest changes to chain ID ixo-4.

Changes to update the ixo version and to add Mintscan

---

_IBC/axelar-injective.json
_IBC/cosmoshub-injective.json
_IBC/injective-persistence.json

- axelar-injective
- cosmoshub-injective
- injective-persistence
Signed-off-by: Hwangjae Lee <meetrick@gmail.com>

Add injective paths

---

umee/chain.json

remove umee foundation node

---

assetmantle/chain.json
axelar/chain.json
cheqd/chain.json
chihuahua/chain.json
comdex/chain.json
cosmoshub/chain.json
desmos/chain.json
evmos/chain.json
jackal/chain.json
juno/chain.json
kujira/chain.json
mars/chain.json
osmosis/chain.json
passage/chain.json
secretnetwork/chain.json
sentinel/chain.json
stargaze/chain.json
stride/chain.json
teritori/chain.json
terra2/chain.json

Also edited existing endpoints

WhisperNode - Jackal, Terra2, Passage endpoints

---

evmos/chain.json

Upgrade Evmos to v11.0.2

---

chihuahua/chain.json

proposal: https://www.mintscan.io/chihuahua/proposals/44
block: 6039999
est time: `2023-02-09 05:41:47`

Upgrade Chihuahua to v4.2.0

---

bitsong/chain.json
sentinel/chain.json

https://github.com/cosmos/chain-registry/pull/1408 part 2

Rebranding freak12techno -> Quokka Stake on Bitsong

---

umee/chain.json

see [proposal](https://www.mintscan.io/umee/proposals/45)

update umeed version

---

emoney/chain.json

https://github.com/cosmos/chain-registry/pull/1408 part 3

Rebranding freak12techno -> Quokka Stake on e-Money

---

cosmoshub/chain.json

Upgrade to v8.0.0 and add darwin/arm64 distro

Update to gaia v8.0.0 chain.json

---

stride/assetlist.json

Fix stEVMOS base

---

cosmoshub/chain.json

Update chain.json Cosmos Hub to v8.0.1

---

juno/chain.json

Update JUNO to v12.0.0 in chain.json

Update JUNO to v12.0.0 in chain.json

---

akash/chain.json

Reverts cosmos/chain-registry#1458
@JeremyParish69 this upgrade never happened

Revert "Update chain.json Akash to v0.22.0"

---

carbon/chain.json

Correct folder name is $HOME/.carbon

Fixed folder name

---

sommelier/chain.json

proposal: https://www.mintscan.io/sommelier/proposals/36
block: 7766725
est time: `2023-02-22 09:00:48`

Upgrade Sommelier to v5.0.0

---

akash/chain.json

Update akash in chain.json 
New repository link and upgrade to v0.22.0

Update Akash repository link and v0.22.0

---

kava/chain.json

Update Kava to latest version v0.21.0

Update Kava to v0.21.0

---

persistence/assetlist.json

https://www.coingecko.com/en/coins/stkatom

add stkatom coin-gecko id

---

carbon/chain.json
stride/chain.json

Updated Stride version to v6 upgrade

Updated Stride version to v6 upgrade

---

teritori/chain.json

proposal: https://www.mintscan.io/teritori/proposals/7
block: 2147722
est time: 2023-02-23 07:59:45

Upgrade Teritori to v1.3.1

---

cosmoshub/chain.json

https://cosmos-rpc.rockrpc.net

Add RockawayX Infra RPC endpoint

---

8ball/chain.json
acrechain/chain.json
bluzelle/chain.json
canto/chain.json
cosmoshub/chain.json
juno/chain.json
osmosis/chain.json

Would like to register TC Network explorer for these porjects: Cosmos Hub, Osmosis, Juno Network, Acre chain, Canto, Bluzelle and 8Ball

Add TC Network explorer

---

axelar/chain.json

https://axelar-rpc.rockrpc.net/

Add RockawayX Infra RPC endpoint for Axelar main

---

comdex/chain.json

proposal: https://www.mintscan.io/comdex/proposals/102
block: 6548200
est time: `23rd Feb 2023 14:30 UTC`

Upgrade Comdex to v9.0.0

---

cosmoshub/chain.json

- Check every seeds and peers with `nc` to check for liveness (no peer ID check)
- Check every RPC and REST endpoints with http access
- Check every GRPC endpoints with `grpcurl`

update list of seed, peers, endpoints

---

nomic/chain.json

Example Links:
- https://nomic.zenscan.io/index.php
- https://nomic.zenscan.io/address.php?address=nomic1elsazn2x49jd8shuj2jjcas3tsqdplfequdear
- https://nomic.zenscan.io/transaction.php?hash=B6C19218602A10359D6A54A088004202ACC5E358108325F206EB2C74570D46E0

nomic: added Zenscan.io explorer

---

persistence/chain.json

Update Persistence to v7.0.0 in chain.json

---

secretnetwork/chain.json

proposal: https://www.mintscan.io/secret/proposals/142
block: 7719500
est time: `2023-03-01 05:56:03` PST

Upgrade Secret to v1.7

---

carbon/chain.json

..and updated blockhunters' api addresses

Update Carbon to v2.22.1

---

echelon/chain.json
kichain/chain.json
kujira/chain.json
lumenx/chain.json
odin/chain.json

Add missing Gas as per Osmosis Frontend

---

testnets/archwaytestnet/assetlist.json
testnets/archwaytestnet/chain.json

This PR adds Archways test network called constantine-1

add archwaytestnetwork

---

bandchain/chain.json
cudos/chain.json
microtick/chain.json
shentu/chain.json
stargaze/chain.json

Add missing fee tokens

---

lumenx/chain.json

There was a lot of changes in the lumenx project - we are upgrading info with the current information.

Updating basic info for lumenx project

---

bitcanna/chain.json

proposal: https://www.mintscan.io/bitcanna/proposals/10
block: 7585420
est time: `2023-03-10 10:24:00`

Upgrade Bitcanna to v1.6.1

---

umee/chain.json

Adding QauntNode endpoints for Umee

Adding QauntNode endpoints for Umee

---

cosmoshub/chain.json

Must wait till after the v9 release on 15th March

Updated Gaia version to v9.0.1

---

8ball/chain.json
bostrom/chain.json
chihuahua/chain.json
comdex/chain.json
jackal/chain.json
nyx/chain.json
provenance/chain.json
terra2/chain.json
tgrade/chain.json

Add "cosmwasm_enabled": true, for chain with it, so suggest chain features can know to allow the transfer of cw tokens

Add missing CW enabled info

---

osmosis/chain.json

Update Osmosis to v15 in osmosis/chain.json

Update Osmosis to v15 in chain.json

---

injective/chain.json

proposal: https://www.mintscan.io/injective/proposals/207
block: 28864000
est time: `Fri Mar 17 2023 16:34:10Z`

Upgrade Injective to v1.10

---

bitcanna/chain.json
bitsong/chain.json
desmos/chain.json
kichain/chain.json
lumnetwork/chain.json
shentu/chain.json

Nodes almost crashed because of the severe high amount of requests comming from/through 85.10.192.168 - looks like someone is seriously spamming with requests again

Removed our rpc and rest endpoints

---

quicksilver/chain.json

proposal: https://www.mintscan.io/quicksilver/proposals/7
block: 1115600
est time: `Mon Mar 20 2023 13:07:57Z`

Upgrade Quicksilver to v1.2.7

---

_IBC/agoric-kujira.json

`ChannelOpenConfirm` visible in Agoric [Tx A9CC6979D431F5B3D4B83C46F56C1AF6FB664A0106EACA44BBA96FFFB201C35B](https://bigdipper.live/agoric/transactions/A9CC6979D431F5B3D4B83C46F56C1AF6FB664A0106EACA44BBA96FFFB201C35B).

ibc: Add agoric-kujira

---

kujira/chain.json

proposal: https://www.mintscan.io/kujira/proposals/302
block: 9226200
est time: `2023-03-22 18:40:22`

Upgrade Kujira to v0.8.4

---

impacthub/chain.json

proposal: https://www.mintscan.io/ixo/proposals/403
block: 1345000
est time: `Thu Mar 23 2023 09:06:36`

Upgrade IXO to v0.20.0

---

kichain/chain.json

proposal: https://www.mintscan.io/ki-chain/proposals/5
block: 14340215
est time: `2023-03-23 12:16:02`

Upgrade Ki to v5.0.0

---

kujira/chain.json

Update Kujira to v0.8.4-mainnet in chain.json

Update Kujira to v0.8.4-mainnet in chain.json

---

stargaze/chain.json

[chain upgrade](https://www.mintscan.io/stargaze/proposals/143) @  Fri Mar 24 2023 ~15:40:07 UTC

update starsd version

---

quasar/assetlist.json
quasar/chain.json

Update Quasar to mainnet

---

decentr/chain.json
planq/chain.json

- Planq Network
- Decentr Network

initial: add sxlzptprjkt on chain-registry

---

cheqd/chain.json
quasar/chain.json

add and update urls for Cheqd and Quasar explorers

add: update Big Dipper explorer urls

---

_IBC/cosmoshub-noble.json
_IBC/crescent-noble.json
_IBC/juno-noble.json
_IBC/kujira-noble.json
_IBC/noble-osmosis.json
testnets/_IBC/nobletestnet-osmosistestnet.json

Paths have been opened for:
- Crescent
- Osmosis
- Kujira
- Juno
- Cosmoshub

Add IBC Path Data for `noble`

---

migaloo/chain.json

proposal: https://ping.pub/migaloo/gov/2
block: 656439
est time: `2023-03-29 17:43:14`

Upgrade Migaloo to v2.0.0

---

jackal/chain.json

Updating to match keplr chain registry.

Updating Jackal Gas Prices

---

evmos/chain.json

proposal: https://www.mintscan.io/evmos/proposals/136
block: 12252000
est time: `Wed Mar 29 2023 13:12:05`

Upgrade Evmos to v12

---

chain.schema.json

--Adds the following properties to the versions object: recommended_version, compatible_versions, cosmos_sdk_version, consensus, cosmwasm_version, cosmwasm_enabled, ibc_go_version, ics_enabled (binaries are already there)
--removes duplicate genesis property

Update chain.schema--Version data per Version

---

testnets/nobletestnet/chain.json
testnets/nolustestnet/chain.json
uptick/chain.json

uptick, nobletestnet, nolustestnet

Fix tendermint version to consensus

---

osmosis/assetlist.json

to avoid ambiguity of having 2 cw20 contracts

Add ASTRO to Osmosis assetlist

---

comdex/chain.json

Upgrade to v10.0.0 at block 7158500 pending approval of Prop 132 - https://www.mintscan.io/comdex/proposals/132

Upgrade Comdex to v10

---

migaloo/chain.json

Prop passed: https://explorer.silknodes.io/migaloo/gov/5

Update migaloo min gas price

---

assetlist.schema.json

Secret network recently had a migration

Added SNIP25 as a Token type

---

carbon/chain.json

proposal: https://ping.pub/carbon/gov/292
est time: `2023-04-15 05:58:25`

Upgrade Carbon to v2.25.0

---

regen/assetlist.json

Fix NCT display lowercase

---

juno/chain.json

proposal: https://www.mintscan.io/juno/proposals/282
est time: `2023-04-17 16:51:34Z`

Upgrade Juno to v14

---

omniflixhub/chain.json

Add OmniFlix gas

---

osmosis/chain.json

Fix low gas price to 0.0025 in osmosis

---

tgrade/chain.json

updated to newest version with cherry patch

Update tgrade chain.json

---

omniflixhub/chain.json

proposal: https://www.mintscan.io/omniflix/proposals/6
est time: `Tue Apr 19 2023 05:41:34Z`

Upgrade Omniflixhub to v0.10.0

---

testnets/_IBC/cosmoshubtestnet-osmosistestnet5.json

updated due to client expiration

ibc update cosmoshubtestnet-osmosistestnet5

---

juno/assetlist.json

fix LIGHT exponent

---

gravitybridge/chain.json

proposal: https://www.mintscan.io/gravity-bridge/proposals/172

Upgrade Gravity to v1.9.0

---

migaloo/assetlist.json

adds coingecko-id to $WHALE on migaloo chain

add coingecko-id to whale token

---

stride/chain.json

proposal: https://www.mintscan.io/stride/proposals/202
block: 3396933
est time: `2023-04-26 07:45:08`

Upgrade Stride to v9

---

arkh/chain.json

Testing running `arkhd init my-moniker`.

Fixing node_home for arkh.

---

assetmantle/chain.json

assetmantle: Add paranorm.pro REST and RPC endpoints

---

juno/assetlist.json

Fix Light decimal

---

lumenx/chain.json

...and remove version for which no release or tag was present

Update lumenx current version to latest release

---

testnets/akashtestnet/assetlist.json
testnets/akashtestnet/chain.json
testnets/nobletestnet/chain.json

Add Akash Testnet

---

.github/workflows/validate_assetlistjson.yml
.github/workflows/validate_chainjson.yml
.github/workflows/validate_ibcdatajson.yml
.github/workflows/validate_memokeysjson.yml
_IBC/8ball-osmosis.json
chain.schema.json
testnets/statesettestnet/assetlist.json
thorchain/chain.json

Fix Schema Validations

---

secretnetwork/chain.json

AutoStake secretnetwork services typo fix

---

aura/chain.json
cudos/chain.json

Add seed, rest, rpc, and gprc for Aura and Cudos for Lavender.Five Nodes

Add seed, rest, rpc, and gprc for Aura and Cudos

---

cosmoshub/chain.json

pls note: 
* fixed v9 upgrade name
* no upgrade name for v9.1.0 because no `SoftwareUpgradeProposal`

update gaiad version to v9.1.0

---

testnets/akashtestnet/chain.json
testnets/axelartestnet/chain.json
testnets/junotestnet/chain.json
testnets/kyvetestnet/chain.json
testnets/nobletestnet/chain.json
testnets/osmosistestnet5/chain.json

Mostly updating gas prices for various testnet chains
Fix akashtestnet apis

Update Testnet info

---

_IBC/noble-terra2.json

client: https://www.mintscan.io/noble/txs/079B7D515FD67463A9B53A890ED18CC7AB262CF9CEEA26F2B8EEF21015FB39EA?height=667650
connection: https://www.mintscan.io/noble/txs/4E68576D386223856E6FD618398CBBFCDDFBEFEF3FA7BAF649B4923F9E90ED14?height=667739
channel: 
https://www.mintscan.io/noble/txs/3E3E132FEC37536C521212AE393C8149E1EC10B7703F52529A1FCB51E9DA7917?height=667747

create path for noble-terra2

---

neutron/chain.json

Add RPC, REST, gRPC for Lavender.Five Nodes

Add Neutron APIs for Lavender.Five Nodes

---

_IBC/kujira-neutron.json

client: https://www.mintscan.io/kujira/txs/30ABB1B3FD2F027B6CD407F1A11A6CB163A677BB48E3BEBA7BB912DC9489D268?height=10713076
connection: https://www.mintscan.io/kujira/txs/30ABB1B3FD2F027B6CD407F1A11A6CB163A677BB48E3BEBA7BB912DC9489D268?height=10713076
channel: https://www.mintscan.io/kujira/txs/B53F1C710A688B4ED2A68FB5D1CB561BDF7DE6BAFD9596B6358E38E66B819244?height=10713362
ibctest: https://www.mintscan.io/neutron/txs/7AD9FF61C609769719EB64082814F0A4B8A5032D9C749D2E7D8999152AEEE0F5?height=19961

added path for kujira neutron

---

omniflixhub/chain.json

We will close omniflixhub server in the next week

Del staking-explorer REST API endpoint for omniflixhub

---

quicksilver/chain.json

Update quicksilver chain.json

---

quicksilver/chain.json

Upgrade Quicksilver to v1.2.10 pending approval of Prop 13 at height 1936600. https://www.mintscan.io/quicksilver/proposals/13

Upgrade Quicksilver to v1.2.10

---

testnets/cosmoshubtestnet/chain.json

Add Osmosis' Cosmoshubtestnet nodes

---

secretnetwork/chain.json

est time: `2023-05-16 15:02:51`

Upgrade Secret to v1.9

---

_IBC/aura-nois.json

IBC Channel Open Ack visible in Aura [Tx DE3235DE80904C1C160086FC1E93E49711176849102F883326377EE4C780C5BD](https://aurascan.io/transaction/DE3235DE80904C1C160086FC1E93E49711176849102F883326377EE4C780C5BD).

ibc: Add aura-nois

---

_IBC/stride-umee.json

Add Stride <> Umee IBC Connection info

Add Stride-Umee IBC Info

---

_IBC/axelar-odin.json

new path for axelar odin
[client Open](https://www.mintscan.io/axelar/txs/E7ED2A81E7F11BAC16A6FB4E212A96FF5371CD57DA2C8E2F9DEAFFCF5F3BB107?height=7460395)
[connection open](https://www.mintscan.io/axelar/txs/231BE1FC5AB9556A24C24902F6B8FBA3D8133EE6BAA5B981CA767796F5298391?height=7460403)
[channel open](https://www.mintscan.io/axelar/txs/29641FBA3927072C135E899058D13A769B80CD81DA574E02CD45CE4F126C3982?height=7460410)
[ibc test](https://www.mintscan.io/axelar/txs/C2BE7208CE8007EF3BD1B7827B8CE05F5CB4E73B2A82CE9D5B228D27001E9F0F?height=7460597)

add axelar odin path

---

.github/workflows/check-broken-links.yml

Check Broken Links

---

kujira/assetlist.json

Add coingecko ID to MNTA

---

bandchain/chain.json

Binary was updated https://github.com/bandprotocol/chain/releases/tag/v2.5.2

Update binary version.json

---

testnets/celestiatestnet2/chain.json

This updates `arabica-5` to `arabica-8` and updates RPC and `celestia-app` versions.

deps: update Celestia Arabica testnet chain configuaration

---

injective/chain.json

Upgrade Injective to v1.11

---

neutron/assetlist.json

https://www.coingecko.com/en/coins/neutron

Update Neutron coingecko id

---

juno/chain.json

est time: `2023-06-05 15:57:57`

Upgrade Juno to v15

---

axelar/assetlist.json

https://www.coingecko.com/en/coins/axelar-usdc

Update AXLUSDC coingecko id

---

nolus/chain.json

Upgrade Nolus to v0.4.0

---

teritori/chain.json

est time: `2023-06-07 14:07:20Z`
prop: https://www.mintscan.io/teritori/proposals/34

Upgrade Teritori to v1.4.0

---

juno/assetlist.json
juno/chain.json

Should https://www.mintscan.io/juno/proposals/297 pass, this PR should be merged in
- Increases min fee for Juno + steps
- adds IBC atom denom (channe-1) with the new fees as well.

June 7th - Increase Juno Fees (Proposal 297)

---

quicksilver/chain.json

Barberry https://github.com/ingenuity-build/quicksilver/releases/tag/v1.2.14

Fix Quicksilver to v1.2.14 for Barberry

---

stride/chain.json

Barberry https://github.com/Stride-Labs/stride/releases/tag/v9.2.1

Fix Stride to v9.2.1 for Barberry 

---

akash/chain.json

Huckleberry https://github.com/akash-network/node/releases/tag/v0.22.7

Fix Akash to 0.22.7 for Huckleberry

---

_IBC/jackal-kujira.json

Create new jackal <> kujira channel

---

likecoin/chain.json

update likecoin to v4.0.1

---

migaloo/chain.json

Barberry https://github.com/White-Whale-Defi-Platform/migaloo-chain/releases/tag/v2.0.4

Fix Migaloo to 2.0.4 for Barberry

---

stargaze/chain.json

This PR updates the min gas price required by the network. Also updates to the latest v10

update stargaze fee token to the min required

---

stargaze/chain.json

* [chain upgrade](https://www.mintscan.io/stargaze/proposals/172) at ~2023-06-08 17:27 UTC
* fixed v9 name

update starsd to v10

---

.github/workflows/validate_assetlistjson.yml
.github/workflows/validate_chainjson.yml
_template/assetlist.json
_template/chain.json

Thought this might be helpful, so people don't have to always re-write things.

Add template dir

---

agoric/chain.json

nodeasy rpc

---

composable/chain.json

Upgrade Comosable to v3.1.1

---

cosmoshub/chain.json

docs: Update comoshub for v10.0.0 release

---

lumenx/chain.json

Remove ChainTools offline rpc and rest

Update LumenX RPC/REST

---

_IBC/kava-kujira.json

https://github.com/DefiantLabs/svc-kujira-relay#kava

added kava

---

testnets/persistencetestnet2/assetlist.json
testnets/persistencetestnet2/chain.json

test-core-2 chain details added at testnets/persistencetestnet2

persistence test-core-2

---

gravitybridge/chain.json

Proposal: 183
Height: 7440250
https://www.mintscan.io/gravity-bridge/proposals/183
Expected Mon Jun 26 2023 09:29:58 GMT-0400 (Eastern Daylight Time)

Upgrade gravity to v1.10.0

---

stride/chain.json

Prop: 207
Height: 4291924
https://www.mintscan.io/stride/proposals/207
Estimated Target Date:
Tue Jun 27 2023 09:46:42 GMT-0400 (Eastern Daylight Time)

Upgrade Stride to v11

---

_IBC/evmos-kava.json

This is the json file containing the path metadata for the new IBC path between Evmos and Kava.

ibc: Add evmos-kava

---

omniflixhub/chain.json

Prop: 12
Height: 7339200
https://www.mintscan.io/omniflix/proposals/12
Estimated time Fri Jun 30 2023 09:50:12 GMT-0400 (Eastern Daylight Time)

Upgrade omniflixhub to v0.11.0

---

_IBC/osmosis-realio.json
_IBC/realio-osmosis.json

This PR adding IBC information between realio and osmosis. which will make this [osmosis-labs/assetlists PR](https://github.com/osmosis-labs/assetlists/pull/572) passed and ready to be merged.

Add IBC realio - osmosis

---

empowerchain/chain.json

- RPC: https://empower.rpc.liveraven.net
- REST API: https://empower.api.liveraven.net
- gRPC: https://empower.grpc.liveraven.net

Adding services for EmpowerChain

---

quasar/chain.json

as per https://github.com/osmosis-labs/assetlists/pull/609/files

Add quasar gas prices

---

archway/chain.json

source: https://github.com/chainapsis/keplr-chain-registry/pull/172/files

Add archway min fees

---

desmos/chain.json

Prop: 29
Height: 9259165
https://www.mintscan.io/desmos/proposals/29
Estimated Target Date:
Wed Jul 05 2023 10:01:55 GMT-0400 (Eastern Daylight Time)

Upgrade Desmos to v5.2.0

---

nolus/chain.json

Add sphincs.plus api endpoints.

Update chain.json - add api endpoints

---

testnets/celestiatestnet2/chain.json
testnets/celestiatestnet3/chain.json

update celestia mocha and arabica to mocha-3 and arabica-9

---

echelon/chain.json

mind heart soul and echelon joker => added
ech.world nodes will be shutdown => removed
ech.network and softpaws.xyz are no longer working => removed

Update Echelon chain.json

---

carbon/chain.json

Prop 305
Height 43691091
https://scan.carbon.network/governance/proposal/305?net=main
Est Time: around Monday, July 3, 2023 3:20 AM EST

Upgrade Carbon to v2.26.0

---

_IBC/osmosis-xpla.json

add : ibc osmosis-xpla

---

LICENSE
README.md

Adding CC-BY-4.0, with discussion from #2154.

Set LICENSE

---

dyson/assetlist.json

Hello, this adds new IBC denom metadata to Dyson.

Add OSMO, WBTC, and USDC to Dyson Protocol assetlist

---

lumnetwork/chain.json

Prop 81
Height 8481400
Estimated Upgrade Time Fri Jul 21 2023 11:24:00 GMT-0400 (Eastern Daylight Time)
https://www.mintscan.io/lum/proposals/81

Upgrade Lum Network to v1.5.1

---

xpla/chain.json

add axpla 3gas_price

---

kujira/chain.json

Added Rorcual RPC to the registry.

Update chain.json with up to date RPCs

---

_IBC/archway-axelar.json

- updated to the new IBC path for axelar

updated axerlar path

---

composable/chain.json

Prop 5
Height 792909
Est Time 7/28/2023, 4:52:04 PM EST
https://ping.pub/composable/gov/5

Upgrade Composable to v4

---

passage1/assetlist.json
passage1/chain.json

Discussion for reference: https://github.com/cosmos/chain-registry/pull/2577

Move passage-1 information to passage1

---

chain.schema.json
passage/chain.json

This is a fork from passage-1 to passage-2 with a new genesis.
Chain relaunch is on Monday July 31

Fork Passage to v2.0.0

---

chihuahua/chain.json

Update Chihuahua Gas

---

testnets/_IBC/akashtestnet-osmosistestnet.json
testnets/_IBC/axelartestnet-osmosistestnet.json
testnets/_IBC/axelartestnet-osmosistestnet4.json
testnets/_IBC/chain4energytestnet-osmosistestnet.json
testnets/_IBC/composabletestnet-osmosistestnet.json
testnets/_IBC/cosmoshubtestnet-osmosistestnet.json
testnets/_IBC/empowertestnet-osmosistestnet.json
testnets/_IBC/junotestnet-osmosistestnet.json
testnets/_IBC/junotestnet-osmosistestnet4.json
testnets/_IBC/kyvetestnet-osmosistestnet.json
testnets/_IBC/marstestnet-osmosistestnet.json
testnets/_IBC/marstestnet-osmosistestnet4.json
testnets/_IBC/nobletestnet-osmosistestnet.json
testnets/_IBC/nobletestnet-osmosistestnet4.json
testnets/_IBC/nolustestnet-osmosistestnet.json
testnets/_IBC/osmosistestnet-persistencetestnet2.json
testnets/_IBC/osmosistestnet-quicksilvertestnet.json
testnets/osmosistestnet/chain.json
testnets/osmosistestnet4/assetlist.json
testnets/osmosistestnet4/chain.json

osmosistestnet -> osmosistestnet4
osmosistestnet5 -> osmosistestnet
this is to keep the canonical testnet as 'osmosistestnet'

Switch Osmosistestnet chain names

---

kyve/chain.json

Prop 8
Height 2061100
https://www.mintscan.io/kyve/proposals/8
Estimated Time:  Aug 1st 2023, 07:04:02

Upgrade Kyve to v1.3.0

---

quicksilver/chain.json

Prop 18
Height 3052279
Estimated Time:  Jul 31st 2023, 12:57:27 EST
https://www.mintscan.io/quicksilver/proposals/18
Upgrade to v1.2.15, change consensus from tendermint to cometbft

Upgrade Quicksilver to v1.2.15

---

testnets/_IBC/akashtestnet-osmosistestnet.json
testnets/_IBC/akashtestnet-osmosistestnet5.json

akashtestnet had a reset, we had to re-create the path

Update `ibc` akashtestnet-osmosistestnet5

---

lumnetwork/chain.json

Prop 87
Height 8688700
Estimated Upgrade Time August 4th at 16:00 UTC
https://www.mintscan.io/lum/proposals/87

Update Lum Network to v1.5.2

---

_IBC/neutron-stargaze.json

channel created as per request by the neutron team
maintained by [cryptocrew](https://github.com/clemensgg)

Add `ibc` neutron-stargaze

---

mars/chain.json

update mars chain.json

---

_IBC/aura-cosmoshub.json

reference: https://docs.aura.network/validator/relayer

add Aura-cosmoshub and update Aura-axelar

---

bandchain/chain.json
cosmoshub/chain.json
fetchhub/chain.json
injective/chain.json
irisnet/chain.json
persistence/chain.json
provenance/chain.json
secretnetwork/chain.json
shentu/chain.json
terra2/chain.json

unicode in the name is the swiss flag 🇨🇭

Added rpc & rest from High Stakes CH

---

qwoyn/chain.json

Prop 4
Height 805404
Estimated Upgrade Time 8/8/2023, 10:26:16 PM EST
https://ping.pub/qwoyn/gov/4

Upgrade Qwoyn to v5.2.0

---

juno/chain.json

Prop 311
Height 9481382
Estimated Time 8/7/2023, 11:13:43 AM EST
https://ping.pub/juno/gov/311

Upgrade Juno to v16

---

archway/chain.json

Prop 7
Height 453000
Estimated Time:  Aug 3rd 2023, 09:50:17
https://www.mintscan.io/archway/proposals/7

Upgrade Archway to v2.0.0

---

_IBC/axelar-coreum.json
_IBC/coreum-cosmoshub.json
_IBC/coreum-gravitybridge.json

Added IBC connections for Coreum with Axelar, CosmosHub and GravityBridge

New IBC connections for Coreum

---

chihuahua/chain.json

Prop 51
Height 8711111
Estimated Time:  Aug 10th 2023, 08:59:39 EST
https://www.mintscan.io/chihuahua/proposals/51

Upgrade Chihuahua to v500

---

_IBC/cronos-kava.json

Channel requested by Kava team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` cronos-kava

---

cosmoshub/chain.json

Prop 804
Height 16596000
Estimated Time:  Aug 16th 2023, 09:34:15 EST
https://www.mintscan.io/cosmos/proposals/804

Upgrade Cosmos Hub to v11

---

secretnetwork/chain.json

https://www.mintscan.io/secret/proposals/260

Increase minimum gas for Secret to 0.1uscrt

---

stride/chain.json

Prop 211
Height 5044405
Estimated Time:  Aug 17th 2023, 09:05:29 EST
https://explorer.stavr.tech/stride/gov/211

Upgrade Stride to v13

---

omniflixhub/chain.json

Prop 15
Height 8054200
https://wallet.keplr.app/chains/omniflix/proposals/15
Estimated Time:  Aug 17th 2023, 10:12:32 EST

Upgrade Omniflix Hub to v0.12.x

---

quasar/chain.json

Prop 9
Height 2249500
Estimated Time:  Aug 17th 2023, 12:16:34 EST
https://www.mintscan.io/quasar/proposals/9

Upgrade Quasar to v1

---

sei/assetlist.json

coingecko id is sei-network.
see - https://www.coingecko.com/en/coins/sei

Update assetlist.json - coingeckoid = sei-network, not sei

---

_IBC/neutron-sei.json

Channel requested by Neutron, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` neutron-sei

---

carbon/chain.json

Prop 312
Height 46139891
around Wednesday, August 23, 2023 5:19 AM EST
https://scan.carbon.network/governance/proposal/312?net=main

Upgrade Carbon to v2.29.0

---

shentu/chain.json

Updates to current upgrade and adds some extra properties
adds recommended gas prices

Update Shentu chain.json

---

jackal/chain.json

Prop 9
Height 4074200
Estimated Time: 8/23/2023, 7:00:00 PM EST
https://ping.pub/jackal/gov/9

Upgrade Jackal to v3.0.0

---

rebus/chain.json

Prop 31
Height 9464700
Estimated Time: 8/25/2023, 1:37:38 PM EST
https://ping.pub/rebus/gov/31

Upgrade Rebus to v0.4.0

---

bitcanna/chain.json
testnets/bitcannadevnet/chain.json

Please update the Registry, Thanks 🙏

BitCanna testnet binary update

---

carbon/chain.json

Prop 313
Height 46228611
around Friday, August 25, 2023 4:58 AM EST
https://scan.carbon.network/governance/proposal/313?net=main

Upgrade Carbon to v2.30.0

---

carbon/chain.json

Prop 316
Height 46451861
around Wednesday, August 30, 2023 5:08 AM
https://scan.carbon.network/governance/proposal/316?net=main

Upgrade Carbon to v2.31.0

---

testnets/_IBC/cosmoshubtestnet-osmosistestnet.json

Update `ibc` cosmoshubtestnet-osmosistestnet

---

_IBC/kujira-stride.json

Made some mistakes on the Stride side, sorry!

Fix stride side connection for kuji <-> stride

---

stride/chain.json

Prop 214
Height 5223225
Estimated Upgrade Time 8/31 at 11:00 UTC
https://www.mintscan.io/stride/proposals/214

Upgrade Stride to v14

---

akash/chain.json

Prop 224
Height 12606074
Est Time 8/31/2023, 11:44:40 AM EST
https://ping.pub/akash/gov/224

Upgrade Akash to v0.24.0

---

stargaze/chain.json

proposal: https://www.mintscan.io/stargaze/proposals/212
block: `9796507`
eta: `30th August 15:00 UTC`

Stargaze v12 Upgrade

---

carbon/chain.json

Prop 317
Height 46538071
This version is already live and ready to go
https://scan.carbon.network/governance/proposal/317?net=main

Upgrade Carbon to v2.32.0

---

_IBC/evmos-kujira.json

👋 This PR adds the IBC metadata for Evmos <> Kujira. Please let me know if anything else is needed 🚀

Add Evmos-Kujira IBC metadata

---

_IBC/evmos-injective.json

Let's bridge Evmos and Injective!

Add Evmos-Injective IBC metadata

---

impacthub/chain.json

Prop 439
Height 2383000
Est Upgrade Time Tue Sep 05 2023 07:07:37 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/ixo/proposals/439

Upgrade Impact Hub to v2

---

testnets/celestiatestnet2/chain.json
testnets/celestiatestnet3/chain.json

This updates the chain-registry to reflect the latest versions for these networks:
https://docs.celestia.org/nodes/participate/
cc @Bidon15 @jrmanes

deps: update mocha-4 and arabica-10

---

testnets/terpnettestnet/chain.json

- Added THIOLX like Fee tokens.
- Added TERPX Like Stake tokens
- Added Key_algos
- Added slip44

Update TerpNetTestNet Fee

---

desmos/chain.json

Prop 31
Height 10170000
Fri Sep 08 2023 11:12:00 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/desmos/proposals/31

Upgrade Desmos to v6

---

_IBC/noble-stargaze.json

A path between noble and stargaze has been recently opened
transfer example: https://www.mintscan.io/stargaze/transactions/87EFB7ECA08078399856DA0E9BFA8327A1B98AC0B542808ACF09E2AF0D4ED302

add noble-stargaze IBC path

---

cosmoshub/chain.json

Prop 821
Height 16985500
2023-09-13 10:50:50 EST
https://dev.mintscan.io/cosmos/proposals/821

Upgrade Cosmoshub to v12

---

sei/chain.json

Prop 24
Height 25259000
Estimated Upgrade September 13th 
https://sei.explorers.guru/proposal/24
https://sei.explorers.guru/block/25259000

Upgrade Sei to v3.0.9

---

chihuahua/chain.json

Add slip44 and key algos as the other chains have

chore: update chihuahua chain info

---

testnets/neutrontestnet/chain.json

Replace Palvus node by Falcron

Update chain.json for Pion-1 Testnet

---

chronicnetwork/chain.json

update status to 'killed' & remove public endpoints

Update Chronic Network Status To 'Killed'

---

composable/chain.json

Prop 10
Height 1515288
https://explorer.nodestake.top/composable/gov/10

Upgrade Composable to v5

---

chain4energy/chain.json

Update chain.json add DOUBLETOP

---

qwoyn/chain.json

https://docs.cosmic-horizon.com/qwoyn-network/networks/mainnet/v5.2.0/initialize-node#very-important

Set minimum Qwoyn gas price

---

axelar/chain.json

Upgrade Axelar to v0.34.0

---

gitopia/chain.json

proposal: https://ping.pub/gitopia/gov/6
eta: : 9/15/2023, 2:35:57 PM EST
height: 6072000

gitopia v3 chain upgrade

---

testnets/seitestnet2/chain.json

the current explorer url is incorrect (mainnet, not testnet)

sei testnet2 explorers.guru

---

gitopia/chain.json

https://ping.pub/gitopia/gov/6
est time: `15/09/2023:17:37Z`

Upgrade Gitopia to v3

---

testnets/_IBC/impacthubtestnet-osmosistestnet.json
testnets/impacthubtestnet/chain.json

Update Impacthub Testnet to v2, already happened.
Also adding testnet ibc impacthubtestnet-osmosistestnet

Update Impacthub Testnet to v2

---

noble/chain.json

Prop (none?)
Height 2672000
Estimated Time:  Sep 20th 2023, 12:12:36 (EST)
https://www.mintscan.io/noble/blocks/2672000

Add Noble 3.0.0 and Upgrade to v3.1.0

---

testnets/rsprovidertestnet/assetlist.json
testnets/rsprovidertestnet/chain.json

Add the `provider` chain to the testnets folder:
https://github.com/cosmos/testnets/tree/master/replicated-security/provider

Add provider chain of Replicated Security Testnet 

---

archway/chain.json

https://www.mintscan.io/archway/proposals/21
est time: `Sep 25th 2023, 06:39:52Z`

Upgrade Archway to v4.0.2

---

shentu/chain.json

Release: https://github.com/shentufoundation/shentu/blob/master/CHANGELOG.md#v280---09-12-2023

Update shentu `bech32_prefix`

---

_IBC/neutron-noble.json

Channels requested by Neutron team, maintained by [CryptoCrew](https://ccvalidators.com)

Add 'ibc' neutron-noble

---

neutron/assetlist.json

to neutron-3
as per https://www.coingecko.com/en/coins/neutron

Update Neutron CGID

---

assetlist.schema.json
chain.schema.json

- Add image_sync property to `images`
- Update asset_pointer to a generic pointer (so we can point to chains, too)

Add image_sync property to image object

---

gitopia/chain.json

Prop 7
Height 6334048
Estimated Time: 9/21/2023, 4:36:28 PM EST
https://ping.pub/gitopia/block/6334048
https://ping.pub/gitopia/gov/7

Upgrade Gitopia to v3.2.0

---

persistence/chain.json

Prop 44
Height 13275500
Estimated Target Date: Thu Sep 21 2023 07:09:28 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/persistence/blocks/13275500 https://dev.mintscan.io/persistence/proposals/44

Upgrade Persistence to v9.2.0

---

carbon/chain.json

Prop 318
Height 47592681
around Monday, September 25, 2023 2:28 AM
https://scan.carbon.network/governance/proposal/318?net=main https://scan.carbon.network/block/47592681?net=main

Upgrade Carbon to v2.33.0

---

evmos/chain.json

Prop 196
Height 16105000
Estimated Target Date: Mon Sep 25 2023 12:28:30 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/evmos/proposals/196
https://dev.mintscan.io/evmos/blocks/16105000

Upgrade Evmos to v14.0.0

---

ununifi/chain.json

Change from `guu` to `ununifid`

Fix Ununifi binary name

---

akash/chain.json

Prop 231
Height 12992204
Estimated Target Date: Wed Sep 27 2023 12:22:21 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/akash/proposals/231
https://dev.mintscan.io/akash/blocks/12992204

Upgrade Akash to v0.26.0

---

sentinel/chain.json

- Change recommended version
- Fixes an issue for RPC servers where it wouldn't accept a payment in a different ibc denom

Update Sentinel chain.json

---

stride/chain.json

Prop 217
Height 5532355
Estimated Target Date: Thu Sep 21 2023 07:36:09 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/stride/proposals/217
https://dev.mintscan.io/stride/blocks/5532355

Upgrade Stride to v15

---

secretnetwork/chain.json

https://ping.pub/secret/gov/271
est time: `Tuesday, September 26, 2023, at ~2pm UTC`

Upgrade Secretnetwork to v1.11

---

.github/workflows/sync_images.yml
.github/workflows/utility/chain_registry.mjs
.github/workflows/utility/sync_images.mjs
package.json

- This NodeJS code so far just creates the `images` property based on what logo_URI's might already be defined, and can create new image objects with 'links' to other images.
- Also provides a general purpose set of functions to get and set from the Chain Registry via Node
- Adds script to run this upon manual workflow trigger

Add NodeJS Script to Sync Images (1/3)

---

chihuahua/chain.json

Prop 54
Height 9430000
Estimated Target Date: Thu Sep 28 2023 12:25:19 GMT-0400 (Eastern Daylight Time)
https://dev.mintscan.io/chihuahua/proposals/54
https://dev.mintscan.io/chihuahua/blocks/9430000

Upgrade Chihuahua to v503

---

gitopia/chain.json

Estimated Time: 9/29/2023, 6:48:50 PM
https://ping.pub/gitopia/gov/14
https://ping.pub/gitopia/block/6720000

Upgrade Gitopia to v3.3.0

---

_IBC/kava-sei.json

Requested by Kava team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` kava-sei

---

starname/chain.json

Entry points from Starname Servers

Update chain.json for Starname

---

README.md

It now includes https://github.com/gaia/chain-registry-query/

Update README to include Tooling section

---

haqq/chain.json

https://haqq.explorers.guru/proposal/18
Chain is already at upgrade height

Upgrade Haqq to v1.5.0

---

tenet/assetlist.json

https://www.coingecko.com/nl/coins/tenet
URL != ID

correct tenet coingecko id

---

juno/chain.json

https://github.com/CosmosContracts/juno/releases/tag/v17.1.1

Add Juno v17.1.1 patch to v17

---

kujira/chain.json

https://kujira.explorers.guru/proposal/483
https://kujira.explorers.guru/block/14783000

Upgrade Kujira to v0.9.0

---

migaloo/chain.json

Prop 13
Height 3574316
https://migaloo.explorers.guru/proposal/13
https://migaloo.explorers.guru/block/3574316

Upgrade Migaloo to v3.0.0 and fix old versions

---

carbon/chain.json

https://scan.carbon.network/governance/proposal/319?net=main
https://scan.carbon.network/block/48331411?net=main

Upgrade Carbon to v2.34.0

---

emoney/chain.json

see this: https://t.me/quokkastake/140, the node is defunct as of now

Remove Quokka Stake e-Money public node

---

sei/assetlist.json

Fix SEI's OIN base denom

---

terra2/chain.json

https://ping.pub/terra2/gov/4785
https://ping.pub/terra2/block/7316000

Upgrade Terra to v2.5

---

stride/chain.json

https://dev.mintscan.io/stride/proposals/220
https://dev.mintscan.io/stride/blocks/5932395

Upgrade Stride to v16

---

haqq/chain.json

https://haqq.explorers.guru/proposal/22
https://haqq.explorers.guru/block/8076500

Upgrade Haqq to v1.6.1

---

neutron/chain.json

Updates neutron gas prices to new recommended values

Update neutron gas price to new value

---

passage/chain.json

https://ping.pub/passage/gov/5
https://ping.pub/passage/block/5288888

Upgrade Passage to v2.2.0

---

sei/chain.json

https://sei.explorers.guru/proposal/42
https://sei.explorers.guru/block/34078260

Upgrade Sei to v3.2.1 (and add v3.1.1)

---

irisnet/chain.json

irisnet: chain upgrade update

---

shentu/chain.json

update with info about shentu v2.8.0

---

archway/chain.json

- Add new endpoints
- Fix versions
- Remove endpoints which are no longer working

chore: Sync with archway-network/networks

---

dydx/chain.json

PR into #3038 to add ECO Stake dYdX APIs

Add ECO Stake APIs to dYdX

---

cosmoshub/chain.json

Emergency upgrade, removed v13.0.0 from compatible

Cosmos Hub v13.0.1 patch

---

testnets/qwoyntestnet/chain.json

This PR updates the chain-id, binary version, ibc version, and explorer links.

update qwoyntestnet chain.json

---

source/assetlist.json
source/chain.json

New Coingecko Listing for Source:
https://www.coingecko.com/en/coins/source

Update Coingecko ID and Gas Prices to Source Mainnet

---

celestia/chain.json

chore: add Celestia staking token utia

---

haqq/chain.json

https://ping.pub/haqq/gov/25
https://ping.pub/haqq/block/8282000

Upgrade Haqq to v1.6.3

---

_IBC/celestia-injective.json

I kind of expected the auto-merge to only go through if it passes the checks...

Fix Celestia <> Injective

---

cronos/chain.json
cryptoorgchain/chain.json

Updating cryptoorgchain to cronosorg provider and updating url endpoints

Update cronosorg provider

---

lumnetwork/chain.json

https://www.mintscan.io/lum/proposals/90
https://www.mintscan.io/lum/block/10027000

Upgrade Lum to v1.6.2

---

kujira/chain.json

https://blue.kujira.network/govern/488

Upgrade Kujira to v0.9.1

---

persistence/chain.json

https://dev.mintscan.io/persistence/proposals/55
https://dev.mintscan.io/persistence/blocks/13870350

Upgrade Persistence to v10

---

composable/chain.json

https://ping.pub/composable/gov/12
https://ping.pub/composable/block/2301070

Upgrade Composable to v6

---

evmos/chain.json

https://evmos.explorers.guru/proposal/240
https://evmos.explorers.guru/block/16946771

Upgrade Evmos to v15.0.0

---

carbon/chain.json

https://scan.carbon.network/governance/proposal/321?net=main
https://scan.carbon.network/block/49398331?net=main

Upgrade Carbon to v2.35.0

---

testnets/_IBC/nobletestnet-osmosistestnet.json

https://www.mintscan.io/osmosis-testnet/tx/17CCF54B1F66EF303F6AC61A383754D5EE3DAEEF2B34DE39CA72CF503EF63438?height=3534234
https://www.mintscan.io/noble-testnet/tx/BDC492C3BE1E3AB50E00ACE7582870B9311A733D2316B06924A0C95E5D130164?height=3793490

The testnet noble osmosis path expired, We created a new path with a longer unbonding time.

---

_IBC/dydx-kujira.json

https://www.mintscan.io/dydx/tx/EBB236140C28C11179722D771438F87186D2B2AFFBE6295D6E784A4B96D93F43?height=739249
https://finder.kujira.network/kaiyo-1/tx/56BB191783B0693BEC95E3C89E6B6BF79D7C44D6DBB97C8950566C5F46F55AAB

add kujira dydx ibc path

---

_IBC/archway-terra2.json

https://github.com/archway-network/networks/pull/246#pullrequestreview-1722099511

Update archway <> terra2 per archway's request

---

_IBC/nois-osmosis.json
osmosis/assetlist.json

channel requested by Osmosis,
maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` nois-osmosis

---

quicksilver/chain.json

https://quicksilver.explorers.guru/proposal/26
https://quicksilver.explorers.guru/block/4530000

Upgrade Quicksilver to v1.2.17

---

carbon/chain.json

https://scan.carbon.network/governance/proposal/323?net=main
https://scan.carbon.network/block/49677971?net=main

Upgrade Carbon to v2.36.0

---

testnets/axelartestnet/assetlist.json

Update Axelar Testnet Assets 
- correct WETH base denom
- remove incorrect coingecko IDs
- remove manual image spec (will become auto linked to correct images)

Update Axelar Testnet Assets

---

likecoin/chain.json

https://www.mintscan.io/likecoin/proposals/74
The likecoin community has pass a proposal that recommend all gas prices to be increased by 1000x

Update likecoin gas price step

---

cosmoshub/chain.json

Source: https://discord.com/channels/669268347736686612/1085152096380260372/1170105719949889536

Update Cosmoshub min gas price

---

akash/assetlist.json
canto/assetlist.json
cronos/assetlist.json
dydx/assetlist.json
evmos/assetlist.json
injective/assetlist.json
kujira/assetlist.json
migaloo/assetlist.json
osmosis/assetlist.json
testnets/xiontestnet/assetlist.json

Fix Paths with Missing Base Denom
present on: akash, canto, cronos, dydx, evmos, injective, kujira, migaloo, osmosis, xiontestnet

Fix Paths with Missing Base Denom

---

migaloo/chain.json

https://migaloo.explorers.guru/proposal/18
https://migaloo.explorers.guru/block/3982667

Upgrade Migaloo to v3.0.2

---

_non-cosmos/ethereum/assetlist.json
gravitybridge/assetlist.json
persistence/assetlist.json

Register pstake to ethereum

---

testnets/_IBC/likecointestnet-osmosistestnet.json
testnets/likecointestnet/assetlist.json
testnets/likecointestnet/chain.json

https://testnet.bigdipper.live/likecoin

Add likecoin testnet

---

gravitybridge/chain.json

proposal: https://www.mintscan.io/gravity-bridge/proposals/200
eta: `UTC: Nov 15th 2023, 17:05:15`

gravitybridge chain upgrade

---

terra2/chain.json

https://terrasco.pe/mainnet/governance/proposal/4792
https://ping.pub/terra2/block/7722000

Upgrade Terra to v2.6

---

aura/chain.json

https://aurascan.io/votings/7
https://ping.pub/aura/block/3666129

Upgrade Aura to v0.7.1

---

_non-cosmos/ethereum/assetlist.json

Update wstETH coingecko id

---

testnets/_IBC/celestiatestnet3-osmosistestnet.json

channel requested by milkyway team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` celestiatestnet3-osmosistestnet

---

injective/chain.json

https://discord.com/channels/739552603322450092/834079457937195018/1175117547901829231

Reduce INJ Minimum gas price

---

archway/chain.json
aura/chain.json
beezee/chain.json
bitsong/chain.json
celestia/chain.json
desmos/chain.json
haqq/chain.json
humans/chain.json
jackal/chain.json
kichain/chain.json
konstellation/chain.json
meme/chain.json
quicksilver/chain.json
realio/chain.json
rebus/chain.json
source/chain.json
stratos/chain.json
umee/chain.json
uptick/chain.json

add [NODERS]TEAM endpoints ARCHWAY.json

---

_IBC/archway-neutron.json

Channel requested by Archway team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` archway-neutron

---

akash/chain.json

https://www.mintscan.io/akash/proposals/237
https://www.mintscan.io/akash/block/13759618

Upgrade Akash to v0.28.0

---

sge/chain.json

https://explorer.tcnetwork.io/sge/proposal/1
https://explorer.tcnetwork.io/sge/block/1097000

Upgrade SGE to v1.1.1

---

cosmoshub/chain.json

Inbloc is a new explorer for Cosmos:
https://inbloc.org

Add Inbloc Explorer

---

_IBC/neutron-nomic.json
neutron/assetlist.json

Channel requested by Neutron builders, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` neutron-nomic

---

cosmoshub/chain.json

https://forum.cosmos.network/t/set-a-minimum-gas-price-of-0-005uatom/11779

Update minimum cosmoshub gas to 0.005uatom

---

celestia/chain.json

Update Celestia min gas price to 0.002utia

---

sei/chain.json

https://sei.explorers.guru/proposal/45
https://sei.explorers.guru/block/40562773

Upgrade Sei to v3.3.0

---

testnets/vincechaintestnet/chain.json

Changed status to Killed to replace https://github.com/cosmos/chain-registry/pull/2433

Kill Vincechain

---

_IBC/osmosis-source.json
_IBC/source-osmosis.json

https://ping.pub/source/ibc/connection/connection-0

Create IBC source-osmosis.json

---

_non-cosmos/ethereum/assetlist.json
kava/assetlist.json
kujira/assetlist.json
osmosis/assetlist.json
sommelier/assetlist.json
stride/assetlist.json

Some from Osmosis, Kava, Kujira, Stride, etc.

Update Token Names

---

cronos/assetlist.json
cryptoorgchain/assetlist.json
osmosis/assetlist.json

Update cronos Image since the two urls weren't pointing to the same image, and added Osmosis' CRO as well

Update cronos Image

---

osmosis/assetlist.json

Add STARS to Osmosis

---

ununifi/chain.json

https://explorer.nodestake.top/ununifi/gov/24
https://explorer.nodestake.top/ununifi/block/8197583

Upgrade Ununifi to v4.0.0

---

desmos/chain.json

https://dev.mintscan.io/desmos/proposals/36
https://dev.mintscan.io/desmos/blocks/11312575

Upgrade Desmos to v6.2.0

---

decentr/chain.json
vidulum/chain.json

Update fees for Vidulum and Decentr

Update fees for Vidulum and Decentr

---

gateway/assetlist.json

Add PYTH to Gateway (Wormhole)
Also removed some images because there should be image_syncs used instead, which will be generated right after merging this

Add PYTH to Gateway

---

gateway/assetlist.json

Fix Gateway's asset traces
Had the wrong capitalization before

Fix Gateway's asset traces

---

testnets/_IBC/osmosistestnet-xiontestnet.json
testnets/xiontestnet/assetlist.json

- Had to recreate IBC transfer between Xion and Osmosis testnets
- Update connection / client /channel info
- Update denom

Update xion-testnet-1 <=> osmo-test-5 IBC 

---

gateway/assetlist.json

Fix PYTH display denom--had a copy paste error before

Fix PYTH display denom

---

juno/assetlist.json

Remove SEASY coingecko id

---

ununifi/chain.json

https://explorer.nodestake.top/ununifi/gov/25
https://explorer.nodestake.top/ununifi/block/8299656

Upgrade Ununifi to v4_0_1

---

_IBC/dydx-neutron.json

Channel requested by Neutron team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` dydx-neutron

---

_IBC/kujira-teritori.json

Updated IBC connection values
Verified via hermes.

fix: Update kujira-teritori.json -> IBC connection values

---

osmosis/assetlist.json

Fix Osmosis' Nois denom. Had the wrong ibc hash before

Fix Osmosis' Nois denom

---

aura/chain.json

https://lcd.aura.network/cosmos/base/node/v1beta1/config

Update gas price for Aura

---

starname/chain.json
tgrade/chain.json

Remove Decommissioned Mintscan Support for Tgrade and Starname

Remove Decommissioned Mintscan Support for Tgrade and Starname

---

testnets/_IBC/axelartestnet-sagatestnet.json

Updating Axelar Saga testnet IBC connection detail

Updating Axelar Saga testnet IBC connection detail

---

akash/chain.json
cosmoshub/chain.json
evmos/chain.json
juno/chain.json
osmosis/chain.json
stride/chain.json

discontinued our rpcs so removing entries for:
evmos
juno
osmosis
cosmoshub
akash
stride

rm ivaldilabs rpcs

---

juno/chain.json

https://dev.mintscan.io/juno/proposals/325
https://dev.mintscan.io/juno/blocks/12265007

Upgrade Juno to v18

---

terra2/chain.json

Remove CryptoCrew Terra2 RPC which was decommed

Remove CryptoCrew Terra2 RPC

---

_IBC/axelar-umee.json
_IBC/kava-umee.json

Add IBC for umee

---

_IBC/chihuahua-neutron.json

Channel requested by Neutron team, maintained by [CryptoCrew](https://ccvalidators.com)

Add `ibc` chihuahua-neutron

---

osmosis/assetlist.json

Add Trace for Osmosis $milkTIA to Celestia $TIA

Add Trace for $milkTIA

---

aura/chain.json

https://ping.pub/aura/gov/8
https://ping.pub/aura/block/4083908

Upgrade Aura to v0.7.2

---

qwoyn/chain.json

https://explorer.kjnodes.com/qwoyn/gov/13
https://explorer.kjnodes.com/qwoyn/blocks/2789768

Upgrade Qwoyn to v5.3.0

---

testnets/celestiatestnet2/chain.json
testnets/celestiatestnet3/chain.json

Matches https://github.com/cosmos/chain-registry/pull/3239

feat: update min gas prices on arabica/mocha

---

osmosis/assetlist.json

This PR aims to correct an invalid IBC asset record

fix: correct invalid exponent of base denom

---

nolus/chain.json

https://explorer.nolus.io/pirin-1/gov/54
https://explorer.nolus.io/pirin-1/blocks/3044000

Upgrade Nolus to v0.4.2

---

sei/chain.json

v3.3.3 broke tendermint monitoring, this patch fixes it

Update Sei recommended version to v3.3.4

---

sge/chain.json

https://ping.pub/sge/gov/3
https://ping.pub/sge/block/1564215

Upgrade SGE Network to v1.2.0

---

comdex/chain.json

https://www.mintscan.io/comdex/proposals/216
https://www.mintscan.io/comdex/block/10981900

Upgrade Comdex to v13.3.0

---

gateway/chain.json

Add new P2P public endpoints for Wormhole Gateway.

Update Wormhole Gateway chain.json with P2P endpoints

---

nomic/chain.json
osmosis/assetlist.json

Added nBTC + NOM to Osmosis assets
Added peer + RPC node to Nomic chain

Add Nomic tokens + node

---

neutron/chain.json

https://www.mintscan.io/neutron/block/5416000
https://governance.neutron.org/proposals/25

Upgrade Neutron to v2.0.0

---

_IBC/haqq-osmosis.json

Add IBC channel between haqq network and osmosis

Add IBC haqq-osmosis IBC

---

osmosis/assetlist.json

I think i've got the right type 'ics20' here

AUTISM on Osmosis

---

haqq/chain.json

https://shell.haqq.network/governance/proposal/26
https://ping.pub/haqq/block/9070000

Upgrade Haqq to v1.6.4

---

chihuahua/chain.json

https://www.mintscan.io/chihuahua/proposals/66
https://www.mintscan.io/chihuahua/block/10666000

Upgrade Chihuahua to v6

---

kujira/chain.json

add Interstellar rest api endpoint for Kujira

Interstellar Lounge rest api for Kujira chain

---

chimba/chain.json
testnets/chimbatestnet/chain.json

replade URLs for the blockchain CHIMBA

change urls blockchain chimba

---

assetlist.schema.json
injective/assetlist.json
terra/assetlist.json

Add Asset Name Character Limit (25)

Add Asset Name Character Limit (25)

---

testnets/quicksilvertestnet/chain.json

Update Quicksilver Testnet to reflect rhye-2 upgrade.

Update Quicksilver Testnet (rhye-2)

---

secretnetwork/chain.json

mintscan.io/secret/proposals/289

Change Secret fee settings

---

terra2/chain.json

update terra to reflect gas price changes

Update Terra Gas Fees

---

sentinel/chain.json

Update Sentinel chain.json with Trinity Validator provider (RPC and API)

Update Sentinel chain.json with Trinity Validator provider

---

_non-cosmos/ethereum/assetlist.json
agoric/assetlist.json
comdex/assetlist.json
injective/assetlist.json
juno/assetlist.json
kujira/assetlist.json
microtick/assetlist.json
neutron/assetlist.json
osmosis/assetlist.json
persistence/assetlist.json
secretnetwork/assetlist.json
stride/assetlist.json
terra2/assetlist.json

This PR updates several `assetlist.json` files with the correct corresponding `coingecko_id` for several assets, manually verified by hand.

Add CoinGecko IDs to several assetlist.json files

---

osmosis/versions.json

`../chain.schema.json` => `../versions.schema.json`

Fix incorrect schema path

---

testnets/_IBC/osmosistestnet-sagatestnet.json

Update IBC info for osmosis<->saga testnet

Update IBC info for osmosis-saga testnet

---

testnets/lavatestnet2/chain.json

fix lava testnet to testnet-2

---

_IBC/noble-teritori.json

teritori-1: transfer/channel-62 --- noble-1: transfer/channel-54

feat(teritori): add noble <> teritori ibc channel

---

coreum/chain.json

Proposal: https://www.mintscan.io/coreum/proposals/8

Upgrade Coreum to v3.0.2

---

sei/chain.json

https://www.mintscan.io/sei/proposals/46
https://www.mintscan.io/sei/block/49519931

Upgrade Sei to v3.5.0

---

likecoin/chain.json

Add Citizen Cosmos RPC to Likecoin

---

irisnet/chain.json

Remove non-public iris endpoints from the chain-registry.

Remove non-public iris endpoints

---

bitsong/chain.json
desmos/chain.json
lumnetwork/chain.json

Removing our nodes from the chains

Update bitsong, desmos & lumnetwork chain.json

---

provenance/chain.json

Removing our nodes from the chain

Update provenance chain.json

---

chain4energy/chain.json
osmosis/chain.json

This commit includes the addition of new endpoints to the chain registry:
- API endpoints
- gRPC endpoints
- RPC endpoints
- Seed nodes
These additions aim to enhance the robustness and diversity of connections within the network. Let's stay strong together!

Add additional Validatus endpoints to the chain registry

---

osmosis/assetlist.json

Adding baddog asset information. wasn't automatically pulled from cosmos registry.

Add $baddog assetlist.json

---

osmosis/assetlist.json

Reverts cosmos/chain-registry#3564
Details are incorrect

Revert "Add $baddog assetlist.json"

---

terra2/chain.json

Remove previous versions from compatible.

Update Terra2 to v2.6.3

---

chihuahua/chain.json

Remove v6 from compatible versions

Upgrade Chihuahua to v6.0.1

---

desmos/chain.json

Remove old version from compatible

Upgrade Desmos to v6.2.1

---

migaloo/chain.json

Remove previous version from compatible

Upgrade Migaloo to v3.0.3

---

beezee/chain.json

Removed 2 outaged explorers from the list

Update BZE chain.json

---

_IBC/axelar-jackal.json

Something went wrong when creating the jackal axelar routes, new clients were made

fixing jackal axelar ibc

---

neutron/chain.json

Remove previous version from compatible

Upgrade Neutron to v2.0.1
