cosmos/chain-registry

emoney/chain.json

The seed nodes provided by validator.network for emoney-3 have changed their addresses.

Update validator.network seed node addresses

---

cryptoorgchain/chain.json

The Crypto.org chain has been successfully upgraded at block height `3,526,800` (see [proposal 6])(https://crypto.org/explorer/proposal/6), in this PR, we have:
- Updated the binary version and the links from `v2.1.2` to `v3.3.3`;
- Added link to [Crypto.org explorer](https://crypto.org/explorer).

Crypto.org Chain DRACO II network upgrade 

---

oraichain/assetlist.json
oraichain/chain.json

Oraichain is the world's first AI Oracle for Blockchains built with Cosmos SDK.

Add Oraichain network info

---

cheqd/chain.json
secretnetwork/chain.json

I'm updating the link for the cheqd network explorer from https://cheqd.didx.co.za to https://explorer.cheqd.io. The previous link does an HTTP 301 redirect to the new link, but I wanted to mention the new link regardless.

Updated explorer link for cheqd network

---

terra/chain.json

Found at [Terra docs](https://docs.terra.money/Reference/endpoints.html).
Although the listed `public-node.terra.dev` does not work, I did not remove any broken (or old) endpoints.

More Terra Chain API Endpoints

---

dig/chain.json

Changed Github release `name` to release `tag_name`.
[`MainNet` is the name of their release tag `v1.0.0`](https://github.com/notional-labs/dig/releases/tag/v1.0.0).

Fix Dig's version inconsistency

---

regen/chain.json

https://github.com/cosmos/chain-registry/blob/6a82418682d3e3196aadb1cba16b233849192a63/regen/chain.json#L15-L19
Very strange that this commit hash doesn't even exist.
I updated the version(s) with [latest release tag on their repo](https://github.com/regen-network/regen-ledger/releases/tag/v2.1.0).

Fix Regen Network versions

---

cosmoshub/chain.json

The transfer.sh URL is returning an error currently, and this is the URL given in https://github.com/cosmos/mainnet. Note the change from .json to .json.gz

Update cosmoshub genesis_url

---

sentinel/chain.json

Update expired transfer.sh URL and use version from [Sentinel docs](https://docs.sentinel.co/sentinelhub/running-a-full-node/). Unfortunately there isn't an extracted genesis available.

Update sentinel genesis.json

---

gravitybridge/chain.json

This patch updates details for gravity-bridge-2 and also updates the rpc endpoints lists to include Althea's gravitychain.io service.

Update for gravity-bridge-2

---

dig/chain.json

Found to be `.dig` while adding to Omnibus https://github.com/ovrclk/cosmos-omnibus/pull/112

Fix dig home directory

---

terra/chain.json

https://github.com/terra-money/core/releases/tag/v0.5.15
Note: Looks that they have dropped a support for arm64 architecture (no oracle_Linux_x86_64.tar.gz anymore in assets)

update terra v0.5.14 -> v0.5.15

---

sifchain/chain.json

I checked the api on port 80 and it doesn't work. So I guess the right port is 443 since it works and is https anyway.

change port from 80 to 443

---

osmosis/chain.json

https://github.com/osmosis-labs/osmosis/releases/tag/v6.3.0
v6.2.0 was skipped for some reason

[osmosis] v6.1.0 -> v6.3.0

---

cronos/assetlist.json
cryptoorgchain/assetlist.json

Updated `CRO` token full name from  `Crypto.org Chain Coin (CRO)` to `Cronos (CRO)`
Ref: [Re-branding announcement](https://twitter.com/cronos_chain/status/1494556389951172617?s=20&t=a2Qyr7FJ_sLEPdi2HCcgrQ)

CRO token renaming

---

carbon/chain.json

- Update carbon binaries to v2.2.0
- Use static IPs for seeds (could previously change)

[carbon] v2.1.0 -> v2.2.0, fix seed IPs

---

bandchain/chain.json
bitcanna/chain.json
dig/chain.json
gravitybridge/chain.json
injective/chain.json
juno/chain.json
osmosis/chain.json
secretnetwork/chain.json
sentinel/chain.json
shentu/chain.json
terra/chain.json

Hi,
While referring to the repository, I came across faulty RPC and REST URLs and removed them. 
p.s. Akash chain was already reviewed #229  so I didn't include it. 
45.138.49.222:26657
http://gravity-rpc.qwoyn.com:26657
http://gravity-rpc.qwoyn.com:1317
http://bitcana.paranorm.pro:26657/
http://bitcanna.stakelab.fr/
https://terra.technofractal.com:443
http://64.227.72.101:26657
http://64.227.72.101:1317
https://api.secretapi.io/
https://rpc.laozi3.bandchain.org:80
https://juno-1.technofractal.com:443
https://lcd.juno-1.technofractal.com/
https://osmosis-1.technofractal.com:443
https://sentinelhub-2.technofractal.com:443
https://rpc-2-dig.notional.ventures
https://api-2-dig.notional.ventures
gravity-bridge-1-08.nodes.amhost.net:26657 -> http://gravity-bridge-1-08.nodes.amhost.net:26657/ …

Removal of faulty RPC and REST URLs

---

akash/chain.json

I think these were removed accidentally in https://github.com/cosmos/chain-registry/pull/229

Re-add ECO Stake Akash APIs

---

irisnet/chain.json

Bump IRIS Version to [v1.3.0](https://github.com/irisnet/irishub/releases/tag/v1.3.0)

Bump IRIS Version

---

osmosis/chain.json

have added the binary section and link to linux/amd64 binary
https://github.com/osmosis-labs/osmosis/releases/tag/v7.2.0

[osmosis] after few versions, binary for Linux is back

---

assetlist.schema.json

I think that these 2 fields are necessary mandatory:
- The "symbol" is used everywhere and can be different from "display" (ex : Graviton)
- The "name" is the representation of the token in front, that can be used on all the sites, and used in particular on info
- Improve the verification process and make them mandatory, some people will not fill them or even forget to fill

Add name & symbol required

---

osmosis/chain.json

Update Osmosis version from v7.2.0 to v7.3.0, and kept the same compatible versions (now including v7.3.0)

Update Osmo to v7.3.0

---

evmos/assetlist.json

..because all other symbols are also uppercase? (consistency) -suggestion only

make EVMOS symbol uppercase

---

likecoin/chain.json

Update verison, binary, and new `like` prefix (old `cosmo` prefix is still supported for tx)

Update likecoin v2.0.0

---

kava/assetlist.json
kava/chain.json

Question: How should I handle `denom_units`?
For HARD and SWP, the native chain unit is `hard`, and `swp`, and they are each equivalent to 1^10-6 of 1 HARD, 1 SWP token.

feat: add additional native Kava assets - HARD and SWP

---

README.md
chain.schema.json

Add chain logo to chain.schema.json, same as is used in assetlist.schema.json.
Also added to README
resolves #265

Add chain logo to chain schema

---

.github/workflows/utility/test_ibcdata.py
.github/workflows/validate_ibcdatajson.yml

This PR adds further validation for json files in the _IBC folder.
Workflow has been tested on a fork.
It performs three validations:
- validates that the json file name has two "strings" separated by a hyphen (-) and ends with ".json"
- validates that chain_1 and chain_2 used in the file name are in alphabetical order
- validates that the chain-name for chain-1 and chain-2 inside the json file match the order used in the file name
Consider merging before https://github.com/cosmos/chain-registry/pull/369 ?

further validation for _IBC data files

---

cryptoorgchain/assetlist.json

Changed in https://github.com/cosmos/chain-registry/pull/399

Fix crypto.org logo URI

---

bostrom/chain.json

According to [Cyberfrey](https://github.com/cybercongress/go-cyber/releases/tag/v0.3.0) release

Updated `recommended_version`

---

kujira/chain.json

This adds LCD and RPC endpoints managed via setten.io (https://twitter.com/TeamKujira/status/1543548547122995201)
It also adds a link to our own finder app https://finder.kujira.app

add kujira endpoints & finder

---

sentinel/chain.json

Update Sentinel CoinType to 118 (was 750). As confirmed by Sentinel Team (Tony Stark)
Resolved #313

Update Sentinel CoinType to 118

---

kava/chain.json

Kava is HD root 459, per [SLIP-44](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)

add SLIP-44 number for kava

---

cryptoorgchain/assetlist.json

"cronos" is not the correct id
https://www.coingecko.com/en/coins/cronos

change coingecko_id for cryptoorgchain

---

crescent/chain.json

Update binary version for crescent 
- from [v1.1.0](https://github.com/crescent-network/crescent/releases/tag/v1.1.0) to [v2.1.0](https://github.com/crescent-network/crescent/releases/tag/v2.1.0)

Update binary version for crescent

---

likecoin/chain.json

We have just upgraded our chain with x/nft support
https://blog.like.co/en/likecoin-chain-upgrade-starferry-overview/

Update LikeCoin to v3.0.0 starferry

---

assetlist.schema.json
chain.schema.json

Now all image URIs will be in the proper format and pointing to the chain registry, and not any other repo

Add check logo uri pattern

---

testnets/pulsar/assetlist.json
testnets/pulsar/chain.json

Chain name need to be unique, see conversation on https://github.com/cosmos/chain-registry/pull/550#issuecomment-1197237757. Used `pulsar` based on Chain ID.
@levackt FYI as you submitted the original chain info, let me know if you want to use anything different.

Update Secret Network testnet name

---

crescent/chain.json

- recommended_version to [`v2.1.1`](https://github.com/crescent-network/crescent/releases/tag/v2.1.1)
- add `v2.1.1` on compatible_versions

Update binary version of Crescent Network

---

ibc_data.schema.json

The `ibc_data.schema.json` file was not structured properly. 
While the old version worked, this update should be closer to standards.

Fix and update ibc_data schema

---

persistence/assetlist.json

because PSTAKE having been bridged from Ethereum via Gravity Bridge, then transferred to Persistence chain, is considered the canonical form of PSTAKE within the Cosmos, as decided by Persistence team.

Add pstake

---

testnets/theta/chain.json

Hi! Our seed nodes are operational so I have removed the entries from the `persistent_peers` list.
Both seed and state sync node entries are now aligned with our published [Ansible inventory file](https://github.com/hyphacoop/cosmos-ansible/blob/main/examples/inventory-theta.yml)
Thanks!
Closes #604

Remove persistent peers from Theta testnet

---

agoric/assetlist.json

Recently, Agoric renamed RUN Protocol to Inter Protocol. As a result, the denom previously referred to as RUN is now IST, short for the Inter Stable Token. This update changes the denom name and descriptions in the asset list to match the new naming conventions. 
A follow up proposal to update the logos is on the way.

Update assetlist.json to reflect IST denom

---

_IBC/agoric-cosmoshub.json
_IBC/agoric-crescent.json
_IBC/agoric-osmosis.json

Agoric recently enabled IBC and today their community coordinated around channel initialization for `Crescent`, `Osmosis`, and `Cosmos Hub`. These are the json files containing the path metadata for each of those new IBC paths.

Add Agoric IBC path metadata

---

nomic/chain.json

- Updated Nomic chain recommended version to "develop". (The branch in git.)
- Updated Nomic chain compatible versions to "develop" (branch) and "v3" (tag).
Nomic had a network upgrade a few weeks ago from their v3 version to whatever was on the develop branch at the time to fix a security/continuity bug. The two versions should be compatible. It's been weeks since this was released but no version was tagged from develop. We must assume that the develop branch is the latest up-to-date source code for the chain.

Nomic version update

---

impacthub/chain.json

- Changed recommended version to 0.18.1
- Changed compatible versions to 0.18.0 and 0.18.1
- Removed one RPC node IP address that does not respond
- Removed invalid links to binaries (kept the keys and made them empty string, so we don't break any automations. Maybe we get binaries at a later date.)

Impacthub version updates

---

_IBC/agoric-osmosis.json

When the path details were initially shared in the Agoric Discord there was a typo for the client-id on Osmosis

fix client id typo for agroic<>osmosis

---

stride/chain.json

Stride's genesis.json is incorrect. Update it to the mainnet genesis.json file.

Update Stride genesis.json

---

testnets/junotestnet/chain.json

Adds the polkachu juno testnet gRPC endpoint to config.
I tested that the gRPC url works, and it also follows the same format as the other Polkachu gRPC urls.

Add juno testnet gRPC endpoint

---

cerberus/chain.json
cosmoshub/chain.json
juno/chain.json
meme/chain.json
sifchain/chain.json

Node definitions added for Cerberus, Cosmos, Juno, Meme, and Sifchain.
This is to fix https://github.com/cosmos/chain-registry/pull/766

Add Kleomedes REST/RPC nodes

---

gravitybridge/assetlist.json

Fix: gravity bridge assetlist.json pstake exponent

---

_IBC/agoric-axelar.json

The clients for the agoric-cosmoshub path expired: `07-tendermint-0` and `07-tendermint-898`, respectively. A new path is linked since there are no assets that need to be recovered due to transfers on channels that used those clients.
Additionally, the agoric-axelar path is now linked and added.

agoric-cosmoshub and agoric-axelar IBC paths

---

README.md

Replace dash `-` with undescore `_` in object keys.

Fix IBC info format in README.md

---

osmosis/chain.json

otther chain.jsons are using the "v" format for version number, see https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json#L29

fix osmosisd version format

---

_IBC/agoric-axelar.json

The existing light clients between Agoric and Axelar were misconfigured so the channels ended up being closed.
This is the updated information.

Update agoric-axelar metadata

---

cosmoshub/assetlist.json

Update cosmos hub asset list to accommodate a [fix to metadata](https://github.com/cosmos/gaia/pull/1800)

Update cosmos hub asset name

---

jackal/assetlist.json

Jackal is now listed on coingecko.
https://www.coingecko.com/en/coins/jackal-protocol

Adding coingecko to Jackal

---

fetchhub/chain.json

Correct the genesis URL in the configuration for Fetchhub to match the version in the official Fetch.ai docs:
https://docs.fetch.ai/ledger_v2/live-networks/#mainnet

Update outdated genesis URL for FetchHub

---

cronos/assetlist.json

Cronos share the same token than cryptoorgchain.

Update Cronos coingecko Id

---

README.md

This PR introduces:
- (fix) The example json schema in the Readme was missing a `:`, rendering the code block invalid.
- (chore): added code block syntax highlighting

Fix: Invalid json in README, code block highlight

---

cerberus/chain.json
chihuahua/chain.json
cosmoshub/chain.json
fetchhub/chain.json
jackal/chain.json
juno/chain.json
kujira/chain.json
meme/chain.json
persistence/chain.json
rebus/chain.json
sifchain/chain.json
teritori/chain.json

Update Kleomedes servers to use new `kleomedes.network` domains, rather than `kleomed.es`.

Update Kleomedes domains

---

persistence/chain.json

Persistence moved to use 118 coin-type
persistence will use v5.0.0 from 24th Nov. 
removed persistence owned explorer.

update persistence versions and coin-type.

---

secretnetwork/chain.json

block: https://www.mintscan.io/secret/blocks/6537300
tag: https://github.com/scrtlabs/SecretNetwork/releases/tag/v1.6.0
date: `Tue Dec 13 2022 00:48:41 GMT-0800`

Upgrade Secret to v1.6

---

crescent/assetlist.json

fix(crescent): correct coingecko_id for ubcre token

---

quicksilver/chain.json

` https://api-terra-ia.cosmosia.notional.ventures/cosmos/base/tendermint/v1beta1/node_info `  return ` "network": "columbus-5",` 
` https://api-quicksilver-ia.cosmosia.notional.ventures/cosmos/base/tendermint/v1beta1/node_info` return ` "network": "quicksilver-1",`

fix REST endpoint address

---

terra2/chain.json

tag: https://github.com/terra-money/core/releases/tag/v2.2.0
expected date: December 21, 2022 11:00 AM
block: 2979805

Upgrade Terra2 to v2.2.0

---

persistence/chain.json

Update Persistence's `chain.json` file to include Cosmonaut Stakes' RPC / REST endpoints and persistent peer.

Update chain.json to include extra RPC/REST/PEERS

---

chain.schema.json

because it had already been used

Adding grpc-web

---

chain.schema.json

Move logo_URIs and keywords to chain schema properties
was erroneously in '$defs'
resolves #1176

Fix chain schema for logo_URIs

---

testnets/osmosistestnet/chain.json

https://docs.osmosis.zone/networks
Thought I'd lean in and add this since it seemed to be missing

Add Osmosis testnet gRPC endpoint from Osmosis docs

---

testnets/stargazetestnet/chain.json

https://docs.stargaze.zone/developers/testnet
Thought I'd lean in and add this since it seemed to be missing

Add Stargaze testnet gRPC endpoints from Stargaze docs

---

lumenx/chain.json

Previous endpoints are not available. Validators have delivered the new ones, which provide access to chain resources.

Update chain rpc and api URL's

---

chain.schema.json

-adds bech32_config object, with 6 optional properties
-bech32_prefix is still required, and the config is for override.
closes #665

Add bech32 config to chain schema

---

kichain/chain.json

Emergency upgrade due to chain halt, no proposal/etc.

Upgrade ki to v4.2.0

---

chain.schema.json

Adding gas costs to fee tokens allows dapps and frontends to craft up to date transaction gas amount data. It can also be used to derive a fixed transaction cost (invariant to gas) based on transaction type.
Currently we see overcharges due to incorrectly high gas cost and sometimes failing transactions due to insufficient gas. 
For example, Carbon charges 1 SWTH per send or per ibc transfer. Combining the gas price (769.24) and gas cost of (130000), we can derive the fee of ~1 SWTH per transaction.

Add Gas Costs to fee_tokens

---

testnets/cosmoshubtestnet/chain.json

* Changed the pretty name to `Cosmos Hub Public Testnet`
* Updated min gas price to `0.0025`
* Updated gaiad recommended version to `v8.0.0-rc5`

Cosmos Hub Testnet: Update Gaia to v8

---

canto/chain.json

Recently Canto passed a proposal to enable CSR and bump feemarket to 10000gwei
https://canto.io/governance/proposal/43
Shortly thereafter, Canto passed a proposal setting the feemarket price to 1000gwei
https://canto.io/governance/proposal/44
This should address: https://github.com/eco-stake/restake/issues/702

Bumping Canto fixed_min_gas_price

---

testnets/junotestnet/chain.json

Chain is currently on v11.0.0, but we are upgrading to v12.0.0-beta.1 tag Wednesday
- updates name to uni-6
- Adds my RPC
- Adds my REST
- Adds my Peer
- [Uses Rhinos seed from our repo for Uni-6](https://github.com/CosmosContracts/testnets/blob/main/uni-6/seeds.txt)
- Updates versions to match v12.0.0-beta.1

Uni-5 -> Uni-6

---

umee/chain.json

Replaces the inactive `barnacle` endpoints with the load-balanced `mainnet` endpoints

Update umee foundation rpc & api endpoints

---

juno/assetlist.json

-was invalid before. Display denom must be one of the defined denom units, which "banana Token" was not.

Fix banana display denom

---

testnets/cosmoshubtestnet/chain.json

Hi!
We upgraded the Cosmos Hub Public Testnet to Gaia `v9.0.0-rc3` on Feb 8, 2023.
https://explorer.theta-testnet.polypore.xyz/proposals/115

Upgrade Cosmos Hub Testnet to v9.0.0-rc3

---

mars/assetlist.json

CoinGecko _finally_ gave us a permanent token ID...

Update CoinGecko ID for Mars token

---

sentinel/chain.json

I'm doing a validator rebrand: https://t.me/quokkastake/100, more PRs with other public nodes domain changes will follow a bit later

Rebranding freak12techno -> Quokka Stake on Sentinel

---

axelar/assetlist.json
carbon/assetlist.json
gravitybridge/assetlist.json
persistence/assetlist.json

The coinGecko ID should reside only with the assets directly referred to by the entity on CoinGecko. E.g., ETH's id applies to the Ethereum asset, but should not be used with bridged forms in this registry. The `traces` information within each unoriginal asset can lead developers from that bridged/transformed variant to its origin asset to derive the CGID if needed.

Remove Incorrect CoinGecko IDs

---

mars/assetlist.json

the longer string works, the shorter one shows a price, but it is incorrect. If you would like to verify it is displayed - https://www.coingecko.com/en/coins/mars-protocol

revert mars-protocol coingecko-id

---

cudos/chain.json

We were contacted about the lack of a node_home variable by an operator that uses the chain data to build their networks.
Please consider this PR for inclusion
Andrew Meredith - Cudo Site Reliability Engineer (Blockchain)

Added "node_home" value

---

README.md
assetlist.schema.json
chain.schema.json
osmosis/chain.json

Each asset and chain will eventually instead use an array of images (but for now it will just be added--not removing the old logo_URIs just yet), and each 'image' object in the array can have 'svg', 'png', and 'theme', where theme contains (for now) 'primary_color_hex'. Theme can be expanded later.
Meant to address issue : https://github.com/cosmos/chain-registry/issues/462

Add Images Array

---

cronos/chain.json

Cronos' latest binary is now v1.0.4.

Update version information for Cronos

---

unification/chain.json

Fix denom for FUND fee tokens

---

agoric/chain.json
cryptoorgchain/chain.json
irisnet/chain.json
kava/chain.json
mars/chain.json
persistence/chain.json
secretnetwork/chain.json
starname/chain.json

IOV, IRIS, SCRT, XPRT, MARS, CRO, BLD, KAVA
mostly adding 118 as a secondary id
as per Keplr Chain Registry

Update alternative slip44s

---

akash/chain.json
axelar/chain.json
cosmoshub/chain.json
evmos/chain.json
juno/chain.json
osmosis/chain.json
stride/chain.json

These were removed in a previous clean-up PR, but wrongly so we believe

Re-add ivaldilabs endpoints

---

testnets/cudostestnet/chain.json

The Cudos public testnet machines have recently been migrated to a new set of platforms and have now been given more generic names for future proofing.

Updated chain database for new node hostnames

---

impacthub/chain.json

ixo upgraded it's chain today with the following changes:
- chain-id from ixo-4 to ixo-5
- codebase -> version change from v0.19.3 to v0.20.0
- genesis url changed

Upgrade from ixo-4 to ixo-5

---

jackal/chain.json

Update version to 1.2.1 and update links to binary downloads for Linux/OSX
Block Height: 2080380
Prop: https://ping.pub/jackal/gov/2

Update version and binary links

---

testnets/cosmoshubtestnet/chain.json

Replaced `v9.0.0-rc3` with `v9.0.1`.

Upgrade Cosmos Hub Testnet to v9.0.1

---

chain.schema.json

This PR would enable (optional) per version binaries in the existing "versions" sections of the chains-schema.json file.
This would allow for the automation of binary downloads particularly in cases where chain upgrade proposals were submitted with incomplete information, or a non-consensus breaking upgrade has occurred.

enable per version binaries

---

quicksilver/chain.json

I don't know exactly how the cosmos.directory RPC proxy works (would love to know, if you care to share!) but I suspect it handles the last two, if it makes more sense to leave them in the config.  For whatever reason, though, the proxy seems to consistently route to the first endpoint below, and because that endpoint requires 25x higher fees than the chain itself, any dApp with hard-coded reliance on the proxy endpoint (e.g. restake.app) deterministically fails.  Apologies for my ignorance if my understanding is somehow off base!
This PR...
- removes the `lesnik | UTSA` RPC endpoint (fee settings appear to be misaligned, causing tx failure)
- removes the `Nodeist` RPC endpoint (all API calls timeout)
- removes the `Forbole` RPC endpoint (the binary, at least, has no idea what to do with …

quicksilver: RPC cleanup

---

regen/assetlist.json

This PR:
- updates `denom_units` of Regen's NCT asset to include proper info for the `display_denom`
- adds a coingecko API id corresponding to NCT (https://www.coingecko.com/en/coins/toucan-protocol-nature-carbon-tonne)

fix: add display_denom details for NCT and update coingecko id

---

testnets/seidevnet3/chain.json

It looks like there might have been an accidental copy/paste error with the `chain_name` field, so I corrected it.
You can see this chain name exists already here: https://github.com/cosmos/chain-registry/blob/aa80cc7a6a0ffe29c727265b8dc2c266b9dceabd/testnets/seitestnet2/chain.json#L3
Also took the RPC, REST, and gRPC endpoints located from the Sei docs:
https://docs.seinetwork.io/nodes-and-validators/public-endpoints
and added them, attributing them to the "Sei Foundation"

Update Sei testnet: devnet3

---

testnets/archwaytestnet/chain.json

Archwaytestnet had hard fork and chain id got bumped to constantine-2

update archwaytestnet to use new constantine-2 chain id

---

noble/chain.json
testnets/_IBC/nobletestnet-osmosistestnet.json
testnets/nobletestnet/chain.json

Version upgrade info was accidentally put in the testnet chain.json file. This moves it to the mainnet chain.json file.
Is also:
Mainnet: 
- Adds explorer info
Testnet:
- Updates the ibc path info between osmosis and noble
- Adds explorer info

mainnet/testnet `noble` update

---

genesisl1/chain.json

Hello,
Chain registry fees for GenesisL1 are incorrect, please change to right one.
Thank you

Set proper fees

---

umee/chain.json

added versions for all umee-1 upgrades.
@JeremyParish69 I'm wondering if the `tag`, `height`, and `next_version_name` keys should appear as in [osmosis/chain.json](https://github.com/cosmos/chain-registry/blob/aa883fb98406e82ca53e70bcdbb156bfba0c83b8/osmosis/chain.json#L63)

Umee historical versions

---

chain.schema.json

"Proposal that will officially signals community acceptance of the upgrade.
A proposal number added to the version object, which can be used by CI to indicate whether to update the 'current' version info.

Add Proposal to Versions

---

agoric/chain.json

From https://staking-explorer.com log file...
15 Apr 01:35:23 ~ we need to check REST API endpoint: https://agoric-lcd.easy2stake.com/
15 Apr 01:35:23 ~ https://agoric-lcd.easy2stake.com/cosmos/base/tendermint/v1beta1/blocks/latest ERROR CHAIN (returns cosmoshub-4 but must be agoric-3)

Del Easy 2 Stake API endpoints due to incorrect chain id

---

migaloo/chain.json
testnets/migalootestnet/chain.json

Existing paths do not exist.  Reached out to white-whale team and they advised it's available on the `v2.0.x` branch and upwards.

Fixing path to genesis file in migaloo.

---

cronos/chain.json

To allow work with custom message types with [support](https://github.com/cosmos/relayer/pull/1048/files#diff-8d7de192d295dddfbcfecb3e5785a1e50a567d7a86e246c7bda327d6a7a0b007) from relayer.

add extra_codecs for cronos

---

testnets/elystestnet/assetlist.json

@JeremyParish69 this is a minor PR to fix a typo in the elys testnet network assetlist file

fix: 🐛 fix minor alias typo

---

chain.schema.json

Ran the schema through `jq` to make it standard. Some Go libraries complain if your schema doesn't look nice.
"additionalProperties" in line 610 was already defined in line 505.

jq . chain.schema.json

---

evmos/chain.json

Reverts cosmos/chain-registry#1986
Hi @JeremyParish69.
Our rest endpoints are indeed REST endpoints. We use caddy to map the path to the cosmos API. There is nothing wrong with it other than we block some features. @staking-explorer should have messaged me rather than get our endpoints removed. Can you please revert this PR.

Revert "Del kingnodes REST endpoint"

---

gravitybridge/chain.json

Adding v1.9.1 as recommended version and under compatible versions for v1.9.x. Even though it's not required for everyone, it is required if your validator is doing ETH relaying so it's probably best to set this as recommended.

Change recommended gravity version to v1.9.1

---

chain.schema.json

@JeremyParish69 this is kind of odd, but currently cosmwasm networks don't have a standard location for where to store their wasm information. This is *100%* necessary to know, as using state sync requires this knowledge. 
A few examples of where networks store their wasm information:
| network | path |
| --- | --- |
| secret | `~/.secretd/.compute/wasm` |
| juno |  `~/.juno/data/wasm` |
| osmosis |  `~/.osmosisd/data/wasm` |
| comdex |  `~/.comdex/wasm` |
That's 3 different paths right there, and I *know* there's at least 1 more, I just can't remember it off-hand.
The ideal answer would be for everyone to just standardize around a single method of wasm storage (`juno`'s would be my preference), but I'm going to lean towards "fat chance."

Add cosmwasm path to chain-registry

---

testnets/coreumtestnet/chain.json

Restake app and restake-service use "chains.testcosmos.directory/:chain_name" and it is not returning any data because currently, the [chain_name](https://github.com/cosmos/chain-registry/blob/88080fec2c1edd1d91ea719532cdb7a13855c834/testnets/coreumtestnet/chain.json#L3) for testnet is `coreum` but it should be `coreumtestnet` as all other testnets have chain_name with testnet added in the end.

Added the correct chain_name for the testnet

---

testnets/neutrontestnet/chain.json

Two of the current RPC endpoints don't resolve:
Added Polkachu's testnet RPC, too, which does resolve.
https://neutron-testnet-rpc.polkachu.com/status

Neutron testnet: remove broken RPC endpoints, add Polkachu's

---

testnets/archwaytestnet/chain.json

As we (CronCat) works on deploying to CosmWasm chains, we noticed the Archway testnet is out of date here.
As you can see from [their website](https://docs.archway.io/resources/networks), `constantine-3` is the only one that appears, due to `constantine-2` being outdated.
I've also changed the explorer URL and added Polkachu's testnet RPC node from https://polkachu.com/testnets/archway under "RPC endpoint"

Update archway testnet to `constantine-3`

---

lumnetwork/chain.json

Chain upgrade v1.4.1 happened at block 7,740,000 per prop 64. https://www.mintscan.io/lum/proposals/64
Chain is being patched currently and v1.4.2 is the recommended version to use. Chain relaunch expected June 5 10:00 UTC per Discord announcements.

Add Lum v1.4.1 upgrade plus 1.4.2 patch

---

likecoin/chain.json

LikeCoin chain was upgraded to v4.0.0 on 5th June
https://www.mintscan.io/likecoin/proposals/65
https://blog.like.co/en/likecoin-chain-upgrade-chungking/

update likecoin to v4.0.0

---

testnets/lavatestnet/chain.json

On line 161 of `chain.json` on peer seed id was incorrect. This could cause issues with anyone using the Lava testnet entry.

Fix breaking typo in Lava Testnet chain.json

---

kyve/chain.json

Barberry patch https://github.com/KYVENetwork/chain/releases/tag/v1.2.2

Fix Kyve to 1.2.2 for Barberry

---

evmos/chain.json

Barberry https://github.com/evmos/evmos/releases/tag/v12.1.5

Fix Evmos to v12.1.5 for Barberry

---

mars/chain.json

Barberry https://github.com/mars-protocol/hub/releases/tag/v1.0.2

Fix Mars to v1.0.2 for Barberry

---

injective/chain.json

Barberry https://github.com/InjectiveLabs/injective-chain-releases/releases/tag/v1.11.3-1686246472

Fix Injective to v1.11.3-1686246472 for Barberry

---

gitopia/chain.json

Barberry https://gitopia.com/Gitopia/gitopia/releases/tag/v2.1.1

Fix Gitopia to 2.1.1 for Barberry

---

cheqd/chain.json

Barberry https://github.com/cheqd/cheqd-node/releases/tag/v1.4.4
In addition I changed the version name for this series to "v1" to match the upgrade name and folder name for Cosmovisor.

Fix cheqd to 1.4.4 for Barberry

---

aura/chain.json

est time: `2023 June 12th, 12pm UTC`

Upgrade Aura to v0.4.5

---

crescent/chain.json

update the latest Crescent binary version to [v4.2.0](https://github.com/crescent-network/crescent/releases/tag/v4.2.0)

fix: update Crescent chain.json for latest version

---

chain.schema.json

Removing the `minItems` attribute from the `properties.images` field for fixing a bug in JSON schema.
Closes cosmos/chain-registry#2352.

fix: :bug: fix bug in JSON schema

---

lumnetwork/chain.json

Pending Prop 71 the network will upgrade to v1.4.5 at height 7,950,600 estimated to be on June 15th.
https://www.mintscan.io/lum/proposals/71
https://www.mintscan.io/lum/blocks/7950600

Upgrade Lum Network to v1.4.5

---

comdex/chain.json

Upgrade Comdex to v11.5.0 per Prop 154 at height 8184000. https://www.mintscan.io/comdex/proposals/154
Worth noting v11.4.0 and v11.5.0 were pushed with the same commit, so building with v11.5.0 might result in still installing v11.4.0. Fix here: https://github.com/comdex-official/networks/blob/main/mainnet/15_v11.5.0_Mainet_Upgrade.md#note-if-comdex-version-shows-v1140

Upgrade Comdex to v11.5.0

---

testnets/cosmoshubtestnet/chain.json

Hi! We have upgraded the Cosmos Hub Public Testnet to Gaia `v10.0.1`:
https://github.com/cosmos/testnets/tree/master/public
Thanks!

Upgrade cosmoshubtestnet to v10.0.1

---

composable/chain.json

Upgrade Composable to Centauri/v3.0.2. This upgrade changes the binary name from banksyd to centaurid, and also changes the address prefix from banksy to centauri.
Prop 3: https://explorers.l0vd.com/composable-mainnet/gov/3
Height: 188500
In addition this commit adds APIs and a seed node for Lavender.Five Nodes.

Upgrade Composable to Centauri/v3.1.0

---

composable/chain.json

Upgrade Composable to v3.1.2. Non-consensus patch. 
https://github.com/notional-labs/composable-centauri/releases/tag/v3.1.2

Upgrade Composable to v3.1.2

---

cryptoorgchain/chain.json

Coinbase Cloud doesn't run crypto.org validators anymore

Remove Coinbase Cloud validators

---

testnets/seitestnet/chain.json

Atlantic-1 is effectively killed although still running with a couple of validators. Removing our APIs

Remove ECOStake APIs from seitestnet

---

injective/chain.json

Patch upgrade for chain halt
https://github.com/InjectiveLabs/injective-chain-releases/releases/tag/v1.11.5-1687535916

Upgrade Injective to v1.11.5

---

testnets/junotestnet/chain.json

high_gas_price was lower than low for some reason. I have made this more realistic in line with our network fees
Also updated the version from 14 to 15

Uni-6: Fix fees and codebase version

---

bitcanna/chain.json

Prop 12
Height 9209420
https://www.mintscan.io/bitcanna/proposals/12
Estimated Target Date:
Thu Jun 29 2023 09:15:24 GMT-0400 (Eastern Daylight Time)
This PR also fixes upgrade names, adds props and heights, and next_versions for the previous two versions.
Sources for name fix:
https://www.mintscan.io/bitcanna/proposals/11
https://www.mintscan.io/bitcanna/proposals/10

Upgrade Bitcanna to v2.0.2 wakeandbake

---

osmosis/chain.json

Security patch info: https://github.com/osmosis-labs/osmosis/releases/tag/v15.2.0

Upgrade Osmosis to 15.2.0

---

agoric/chain.json

Fix incorrect agoric logo uris

---

cosmoshub/chain.json

Non-consensus upgrade for v10.0.2. Upgrades versions for Comet BFT and IBC Go.
Source: https://github.com/cosmos/gaia/releases/tag/v10.0.2

Upgrade Cosmos Hub to v10.0.2

---

composable/chain.json

Prop 4
Height 420000
https://explorers.l0vd.com/composable-mainnet/gov/4 Upgrade time est 2023-07-03 19:52:03 EST
Prop is mistaken in its title (3.1.0), this upgrade is for 3.2.0. Please refer to upgrade description in proposal and this release tag: https://github.com/notional-labs/composable-centauri/releases/tag/v3.2.0

Upgrade Composable to v3.2.0

---

impacthub/chain.json

Non-consensus upgrade that fixes state sync issues with v0.20.0. Ok to push this now.
Source: https://github.com/ixofoundation/ixo-blockchain/releases/tag/v0.20.1

Upgrade impacthub to v0.20.1

---

qwoyn/chain.json

Prop 1
Height 280850
No details for prop at https://explorer.theamsolutions.info/QWOYN-MAIN/gov, please refer to https://commonwealth.im/qwoyn-network/discussion/11774-coho-token-initial-mint-and-internal-lp-integration-qwoyndv510 and https://github.com/cosmic-horizon/QWOYN/releases/tag/v5.1.0. 
Estimated Time: 7/5/2023, 1:54:20 PM EST
This PR also adds APIs for Lavender.Five Nodes

Upgrade QWOYN to v5.1.0

---

osmosis/assetlist.json

because they are used canonincally on Nolus, and this maintains the linked list created by traces.
usdc, stosmo, atom, statom, weth.axl, wbtc.axl

Add Osmosis IBC assets

---

evmos/chain.json

Prop 148
Height 14492000
https://www.mintscan.io/evmos/proposals/149
Wed Jul 12 2023 12:53:29 GMT-0400 (Eastern Daylight Time)
This version also changes to cometbft. Also added prop/height for previous version (v12).

Upgrade Evmos to v13.0.2

---

jackal/chain.json

Prop 8
Height 3503000
Source: https://ping.pub/jackal/gov/8
Est Upgrade Date July 11
This PR also fixes upgrade names for previous versions

Upgrade Jackal to v2.1.0

---

cheqd/chain.json
testnets/cheqdtestnet/chain.json

This updates the recommended low/medium/high gas step values for CHEQ/cheqd network. Many validators run with min-gas 50 (although some go lower), which means in some apps, when selecting the "low" gas value as default, transactions fail.

fix: Update default CHEQ gas values

---

impacthub/chain.json

Found through restake the minimum gas validators tend to allow is `0.025uixo`: https://github.com/eco-stake/restake/blob/master/src/networks.json#L127

Update minimum ixo gas price

---

carbon/chain.json

Prop 307
Height 44688221 
https://scan.carbon.network/governance/proposal/307?net=main
The 2.27.0 is still in "pre-release" but the chain is already live with this version, so this is ok to push now.

Upgrade Carbon to 2.27.0

---

migaloo/chain.json

Prop 9
Height 2311215
https://explorer.silknodes.io/migaloo/gov/9
Estimated Upgrade Time 7/17/2023, 3:30:50 PM EST
Added ibc go version, changed consensus to cometbft

Upgrade Migaloo to v2.2.5

---

chihuahua/chain.json

as per the [Keplr Chain Registry](https://github.com/chainapsis/keplr-chain-registry/blob/6db1a67b377562adf435aa6b9c3d005144962bec/cosmos/chihuahua.json#L41) which has 100, 250, and 500.

Update Chihuahua HUAHUA gas prices

---

nolus/chain.json

Prop 34
Height 941000
https://explorer.nolus.io/pirin-1/gov/34
Est Upgrade Time 2023-07-25 10:18:19 EST
Also fixed up previous version by adding upgrade height.
Also updated consensus to cometbft per 0.4.1's go.mod file

Upgrade Nolus to v0.4.1

---

tenet/chain.json

Prop 2
Height 2,330,000
https://tenet.explorers.guru/proposal/2
Upgrade has already taken place so this is good to push through.

Upgrade Tenet to v11.2.0 ("multichain")

---

provenance/chain.json

House keeping for Provenance chain registry entry:
- Updated recommended versions to match current mainnet (1.16.0).
- Updated Figure seed node address and identifier to match current running instance.
- Removed discontinued BigDipper instance hosted by Provenance

Update Provenance registration to reflect current version 1.16.0

---

neutron/chain.json

Non-consensus upgrade for validators.
Source:
https://github.com/neutron-org/neutron/releases/tag/v1.0.4
https://github.com/neutron-org/mainnet-assets/tree/main/upgrades/v1.0.4

Non-consensus upgrade for Neutron to v1.0.4

---

chain.schema.json

to allow for ICS additions. Goes right below genesis_url

Add ICS CCV url to Chain Schema

---

stride/chain.json

Adding "ccv" for v12 as it is necessary to have in the stride config folder along with the normal genesis when going from v11 to v12.

Add "ccv" for Stride v12 upgrade

---

chain.schema.json

Cosmos Hub now offers a windows/arm64 pre-built binary in their chain assets.

Add "windows/arm64" to schema

---

carbon/chain.json

Carbon had a chain halt and v2.27.3 is a required patch that has already gone live.
Source:
https://github.com/Switcheo/carbon-bootstrap/blob/master/upgrade/v2.27.3.md

Patch Carbon to v2.27.3

---

carbon/chain.json

This upgrade height has already passed and has been patched to v2.28.1
https://scan.carbon.network/governance/proposal/308?net=main

Upgrade Carbon to v2.28.0

---

testnets/cosmoshubtestnet/chain.json

Hi! We have upgraded the Cosmos Hub Public Testnet to Gaia `v11.0.0`:
https://github.com/cosmos/testnets/tree/master/public
- I kept v9 and v10 in the version history array
Thanks!

Upgrade Cosmos Hub testnet to v11.0.0

---

_IBC/coreum-osmosis.json

After discussion with Osmosis team, a new IBC client was created raising the trust treshhold to 2/3 for better security.
We created a new client and new connection so we need to modify this information.

Modify coreum-osmosis IBC information

---

quicksilver/chain.json

Non-consensus upgrade
https://github.com/ingenuity-build/quicksilver/releases/tag/v1.2.16

Upgrade Quicksilver to v1.2.16

---

nomic/chain.json

Nomic stakenet no longer runs off the develop branch, which is now used for testnet. Stakenet is now on the main branch.

Fix Nomic stakenet from 'develop' to 'main'

---

_non-cosmos/ethereum/assetlist.json
axelar/assetlist.json

Axelar Satellite now supports Real Yield Eth from Sommelier being bridged into Cosmos. Provides support inside the Cosmos ecosystem.

Add Real Yield Eth from Sommelier to Axelar Asset List

---

nois/chain.json

Non-consensus upgrade already live.
https://github.com/noislabs/noisd/releases/tag/v1.0.4

Upgrade Nois to v1.0.4

---

passage/chain.json

Non-consensus upgrade, validators urged to upgrade asap.
https://github.com/envadiv/Passage3D/releases/tag/v2.0.1

Upgrade Passage to v2.0.1

---

passage/chain.json

To integrate Passage network on Osmosis UI at least one of the fee token must be defined. This PR adds low, average and high gas prices.

Add gas prices to passage chain

---

testnets/cosmoshubtestnet/chain.json

Hi! We have upgraded the Cosmos Hub Public Testnet to v12:
https://github.com/cosmos/testnets/tree/master/public
I added v12 to the version history array.
Thanks!

Upgrade Cosmos Hub Testnet to v12

---

_memo_keys/ICS20_memo_keys.json

A new IBC middleware was [released last week](https://github.com/cosmos/ibc-go/releases/tag/modules%2Fapps%2Fcallbacks%2Fv0.1.0%2Bibc-go-v7.3) in ibc-go, introducing two new memo field keys! This PR adds these keys to the memo registry.

Added callbacks middleware's memo keys to the ICS-20 memo registry

---

tenet/chain.json

Alliance module patch. Non-consensus. Already live.
https://github.com/tenet-org/tenet-mainnet/releases/tag/v11.2.1

Patch Tenet to v11.2.1

---

testnets/lavatestnet/chain.json

Commit 1: update gas prices on lavatestnet chain.json
- Required gas price is .000000001 across the board
Commit 2: remove bigdipper from lavatestnet chain.json
- Big dipper is no longer supported

Update lavatestnet chain.json

---

juno/chain.json

Non-consensus upgrade, already live.
https://github.com/CosmosContracts/juno/releases/tag/v16.0.2

Fix Juno v16 to v16.0.2

---

testnets/_IBC/cosmoshubtestnet-celestiatestnet3.json

Add an IBC connection between Cosmos hub testnet (`theta-testnet-001`) and Celestia testnet (`mocha-4`). 
I verified that I can use this channel via [this tx](https://explorer.theta-testnet.polypore.xyz/transactions/B9ACC78B86DDA84B9B3263B9EC1A7311A12F88B44F65B21B5520866C292A43FF
):
```
$ ./target/release/hermes tx ft-transfer --timeout-seconds 1000 --dst-chain mocha-4 --src-chain theta-testnet-001 --src-port transfer --src-channel channel-3152 --amount 1 --denom uatom
```
Here is the raw output from creating this channel:
```shell
$ ./target/release/hermes create channel --a-chain theta-testnet-001 --a-connection connection-2727 --a-port transfer --b-port transfer
2023-09-16T19:53:09.813815Z  INFO ThreadId(01) using default configuration from '/Users/rootulp/.hermes/config.toml' …
```

feat: add IBC connection for two testnets

---

oraichain/chain.json

https://github.com/oraichain/orai/releases/tag/v0.41.4

Update oraichain to v0.41.4

---

testnets/entrypointtestnet/assetlist.json
testnets/entrypointtestnet/chain.json

As of #2796 the fee token on the EntryPoint public testnet has been changed to ATOM.
For the record, here's an example of a transaction paid for using ATOM: https://explorer.entrypoint.zone/entrypoint/tx/56D647EE82F479674A8817AC182436C66483CC5F4B5F2D14296130750CEEA332

Update EntryPoint fee token to ATOM

---

desmos/chain.json

Bug fix
Good to push as this is already live and expected to be run by validators 
Source: https://github.com/desmos-labs/desmos/releases/tag/v6.1.1

Bug fix for Desmos - upgrade to v6.1.1

---

canto/chain.json

Prop 113
Height 6055770
Upgrade height is already passed and this is live.
https://dev.mintscan.io/canto/proposals/113
https://dev.mintscan.io/canto/blocks/6055770

Upgrade Canto to v7.0.0

---

unification/assetlist.json

Re-add FUND logo_URIs
They switched to images, which is preferred, but the legacy property logo_URIs should be maintained

Re-add FUND logo_URIs

---

_IBC/archway-bitcanna.json

The previously created client had a misconfiguration, with one of trusting periods being too short. This was picked up before starting to relay transactions, and mitigated by creating a new client, in alignment with the Archway team.
---
`IBC Channel Open Confirm` on [BitCanna Tx 8CAC6901342ACD758AAA1BBEB116FEC9F7DBB199168217C8AB244D7836D30C64](https://explorer.bitcanna.io/transactions/8CAC6901342ACD758AAA1BBEB116FEC9F7DBB199168217C8AB244D7836D30C64).
Updates #2892.

Update archway-bitcanna IBC to new client

---

humans/chain.json

Example failing query: http://humans-rpc.stakeangle.com:41417/cosmos/bank/v1beta1/balances/humans1a2hs6gh8qg50lcgwmycln3tqg6e4wk427uq6fh
```json
{
"code": 3,
"message": "invalid address: invalid Bech32 prefix; expected human, got humans",
"details": [
]
}
```

Update humans chain bech32_prefix

---

testnets/rsprovidertestnet/chain.json

The `provider` chain is running Gaia v13 now.
Thanks!

Update rsprovidertestnet with Gaia v13

---

testnets/cosmoshubtestnet/chain.json

The `theta-testnet-001` chain is running Gaia v13 now.
Thanks!

Update cosmoshubtestnet with Gaia v13

---

osmosis/assetlist.json

Update the USDC symbol for Axelar USDc from "USDC" to "USDC.axl" on Osmosis.
Add Noble USDC as symbol "USDC" with the correct IBC/hash and channel ids for Osmosis and counterparty chain.
Update Kava USDt symbol to uppercase T as "USDT".

Update Osmosis assetlist.json for USDC.axl and USDC native from Noble

---

_IBC/kujira-terra2.json

This path has existed for 470 days, but was not included in the chain registry.  I confirmed the clients, connections and channels were open.

IBC Path kujira <> terra2

---

irisnet/chain.json

there is no alternative_slip44s in IRIShub mainnet, "slip44": 118 only, since genesis time.

Update chain.json for IRIShub v2.0.0

---

.github/workflows/utility/sync_images.mjs

Properly utilizing the image property, so osmosis' USDC could synchronize with noble's USDC, which could synchronize with Ethereum's USDC, so Osmosis would indirectly be using Ethereum's USDC image when showing IBC'd Noble USDC on the Osmosis chain.
This completes step 2 of 3 of the planned image synching capabilities

Images now pull for linked origin images

---

testnets/entrypointtestnet/chain.json

`entrypoint-pubtest-1` (originally introduced in #2796 and updated in #2838) has been deprecated and has now been replaced with `entrypoint-pubtest-2`. This PR also fixes a typo where the REST and RPC APIs were swapped.

Update EntryPoint testnet to entrypoint-pubtest-2

---

_IBC/noble-terra2.json

current one is dead, so it was decided it is not worth the gov proposal since
1. it was needed fast
2. no funds were transferred using the dead one (only 0.001 luna for test https://dev.mintscan.io/terra/txs/DB861BA7510EE26BA2353A755094B62B394629BD33A82E3BC2C00726D80C64EC?height=5010031)
new one is up
https://dev.mintscan.io/terra/relayers/channel-253/noble/channel-30

updated noble-terra2 ibc paths

---

.github/workflows/utility/sync_images.mjs

The image_sync script now updates the logo_URIs property with whatever the top ([0]th) image object (i.e., the default image) has for its image URIs.

Finish image_sync Script

---

coreum/assetlist.json

was $CORE for on-chain referencing before, but team agrees to use $COREUM everywhere

Update $COREUM token symbol

---

jackal/chain.json

Non-consensus upgrade
https://github.com/JackalLabs/canine-chain/releases/tag/v3.0.2

Upgrade Jackal to v3.0.2

---

gravitybridge/chain.json

Non-consensus upgrade
https://github.com/Gravity-Bridge/Gravity-Bridge/releases/tag/v1.10.2

Upgrade Gravity Bridge to v1.10.2

---

testnets/temporaltestnet/chain.json

As pointed out in https://github.com/cosmos/chain-registry/pull/3110 setting the status to killed instead of deleting the files.

Kill Temporal

---

composable/chain.json

Chain halt on upgrade, previous version removed as it is *not* compatible. 
https://github.com/notional-labs/composable-centauri/releases/tag/v6.3.1

Composable v6.3.1 patch

---

akash/chain.json

Non-prop upgrade:
https://github.com/akash-network/node/releases/tag/v0.26.2

Upgrade Akash to v0.26.2

---

qwoyn/chain.json

Updated to the actual raw data link vs the blob link

Update genesis.json link for Qwoyn

---

gateway/assetlist.json
neutron/assetlist.json

The image script (and other automation) needs the pointer's base_denom to have the same capitalization as the base property in the original asset definition. for ethereum contracts, different interfaces seem to capitalize the letters differently to each other, leading to this inconsistency we see.
Correcting for NTRN and wormhole, and hopefully the image sync script with pull the images correctly for them now.
Ethereum had:
0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0
vs
0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
which gateway(wormhole) and neutron had

Fix wstETH base capitalization

---

provenance/chain.json

Updates Provenance Blockchain list of supported versions with information associated with 1.17.0/saffron upgrade.

Update Provenance chain.json with release 1.17.0

---

chain.schema.json

Sei uses their own forked custom modules for consensus, wasm, ibc, etc., In order to properly list "sei-tendermint" with its proper version for sei, we should add this to the chain schema.

Add "sei-tendermint" to chain.schema.json

---

kujira/assetlist.json

Fix the `display` to be the same as in `denom_units`.

fix: kujira assetlist display

---

akash/chain.json
bandchain/chain.json
carbon/chain.json
doravota/chain.json
impacthub/chain.json
konstellation/chain.json
testnets/cosmoshubtestnet/chain.json
testnets/persistencetestnet/chain.json
testnets/persistencetestnet2/chain.json

Update fees for many Chains
'akash', (done, pulled from Leap -- pending PR)
'impacthub', (done, pulled from Leap and Keplr--pending PR--they just needed the fees reordered)
'bandchain', (done, pulled from Keplr -- pending PR)
'konstellation', (done, pulled from Leap -- pending PR)
'carbon', (fixed--pending PR)
'doravota', (done, pulled from Keplr -- pending PR)
'cosmoshubtestnet', (done, pulled from Keplr -- pending PR)
'persistencetestnet2' (done, pulled from Keplr -- pending PR)

Update fees for many Chains

---

osmosis/assetlist.json

ibc/831F0B1BBB1D08A2B75311892876D71565478C532967545476DF4C2D7492E48C
is duplicated at [L572](https://github.com/cosmos/chain-registry/blob/a11f9a6eb14dc23759ccd601280361d41e8a3517/osmosis/assetlist.json#L572) and [L956](https://github.com/cosmos/chain-registry/blob/a11f9a6eb14dc23759ccd601280361d41e8a3517/osmosis/assetlist.json#L956)
so I removed the old (572), keep the new (956)
Diff:
```text
"description": "DYDX on Osmosis",
"name": "DYDX",
```
```text
"description": "The native staking token of dYdX Protocol.",
"name": "dYdX",
```

fix: remove duplicated ibc asset record of osmosis

---

testnets/impacthubtestnet/assetlist.json

Fix ixo testnet Image URLs by removing the image urls and tracing it back to mainnet ixo

Fix ixo testnet Image URLs

---

likecoin/chain.json
testnets/likecointestnet/chain.json

LikeCoin chain was upgraded to v4.1.1 at height 12102100
https://www.mintscan.io/likecoin/proposals/77

Upgrade likecoin to v4.1.1

---

osmosis/assetlist.json

Added Coingecko IDs for IBCX, MBRN, CDT
This should add external incentive display value for Osmosis' CDT pools

Add Coingecko IDs for Osmosis natives

---

chain.schema.json
osmosis/chain.json

Add Chain Images Optional Layout Data
layout -> logo (icon + text), logotype (only text), logomark (only icon)
Not added to assetlist since token logo should never have this.
Added the properties to Osmosis' chain.json to serve as an example.

Add Chain Images Optional Layout Data

---

chain4energy/chain.json

Upgrade Chain4Energy to v1.3.0

---

_IBC/neutron-osmosis.json

I noticed that the client and connection IDs on the Neutron side of the Neutron <> Osmosis transfer channels were wrong. This updates them:
client: `07-tendermint-19`
connection: `connection-18`

Fix neutron-osmosis IBC client and connection IDs

---

chain.schema.json
osmosis/versions.json
versions.schema.json

The idea is that the chain.json file only needs the current version data--not the historical version data.
The Osmosis versions file is just an example until automation can manage the synchronicity between that file and the chain.json file. Once automation is set up, we'll be able to enter future version data that will only be included if and when the referenced block height and proposal passes. It will also be nice if new version data can be added to either 'versions.json' or 'chain.json', and the other file would be updated appropriately.

Add Versions schema + Osmosis versions

---

testnets/rsprovidertestnet/chain.json

The `provider` chain is running Gaia v14 now.
Thanks!

Update rsprovidertestnet with Gaia v14

---

testnets/cosmoshubtestnet/chain.json

The `theta-testnet-001` chain is running Gaia v14 now.
Thanks!

Update cosmoshubtestnet with Gaia v14

---

comdex/chain.json

Removed v13.3.0 as it is no longer compatible due to halt height upgrade for v13.4.0.

Patch Comdex to v13.4.0

---

terra2/assetlist.json

This PR aims to remove a redundant record of `terra10se906awphtccf4vd83m0ulpmpt9v4msuakmpy0pwvmtxmup3kdq25rayn` that probably mistakenly added in #3506 
Legacy record: https://github.com/cosmos/chain-registry/blob/4aa7a0632390ed0b1a875b88dce6866bddfb0857/terra2/assetlist.json#L306-L332
The duplicated one: https://github.com/cosmos/chain-registry/blob/4aa7a0632390ed0b1a875b88dce6866bddfb0857/terra2/assetlist.json#L699-L720

fix: remove a redundant asset record in terra2

---

gateway/assetlist.json

the trace had the wrong base_denom, using capitalization where it's not registered as such

Fix Wormhole WETH

---

chain4energy/chain.json

This commit includes the addition of our RPC, Validatus, to the C4E chain configuration. The address is 'https://rpc.c4e.validatus.com:443'.

Add Validatus RPC to chain configuration

---

terra2/chain.json

Reversion of Gas Prices to Standard Levels on Terra (Phoenix)

---

terra2/chain.json

https://github.com/terra-money/core/releases/tag/v2.6.2

Add Terra2 v2.6.2 as Compatible Version

---

migaloo/chain.json

Previous patch (3.0.3) did not resolve security issue. v3.0.4 is now the correct version.

Upgrade Migaloo to v3.0.4

---

gitopia/chain.json
lumnetwork/chain.json
teritori/chain.json

08 Nov 11:10:10 ~ API_ERROR CHAIN_ID at lumnetwork: https://api-lum.starsquid.io/cosmos/base/tendermint/v1beta1/blocks/latest (returns bitsong-2b but must be lum-network-1)
08 Nov 12:00:42 ~ API_ERROR CHAIN_ID at teritori: https://api-teritori.mms.team/cosmos/base/tendermint/v1beta1/blocks/latest (returns kaiyo-1 but must be teritori-1)
08 Nov 12:21:39 ~ API_ERROR CHAIN_ID at gitopia: https://api-gitopia.mms.team/cosmos/base/tendermint/v1beta1/blocks/latest (returns archway-1 but must be gitopia)
Today the same output...

Remove API-providers: mms.team & starsquid.io from 3 chains

---

source/chain.json

05 Dec 15:37:05 ~ API_ERROR CHAIN_ID at source: https://carbon-mainnet-lcd.autostake.com:443/cosmos/base/tendermint/v1beta1/blocks/latest (returns carbon-1 but must be source-1)

Remove autostake.com from source chain

---

evmos/chain.json

Removed binaries are there are no pre-builds for 16.0.1

Upgrade Evmos to v16.0.1

---

carbon/chain.json

https://github.com/Switcheo/carbon-bootstrap/blob/master/upgrade/v2.36.9.md

Patch Carbon to v2.36.9

---

carbon/chain.json

Remove unregistered Fee assets from Carbon
Not allowed to register fee assets that aren't also registered in its assetlist

Remove unregistered Fee assets from Carbon

---

pundix/assetlist.json

Fix PundiX's assetlist so that ibc denoms are all uppercase, as in: ibc/55367B7B6572631B78A93C66EF9FDFCE87CDE372CC4ED7848DA78C1EB1DCDD78

Fix PUNDIX Assetlist

---

injective/chain.json

https://github.com/InjectiveLabs/injective-chain-releases/blob/master/docs/migration/injective-canonical-chain-12-1.md

Patch Injective to v1.12.1

---

ibc_data.schema.json

There are some IBC configurations that contain an 'operators' field (like https://github.com/cosmos/chain-registry/blob/master/_IBC/archway-jackal.json#L30) that is missing in the IBC schema, this PR is for adding this information.

Fix: add operators inside ibc schema

---

osmosis/chain.json

include `go_version`
update to codebase `v22`

Update osmosis chain.json

---

teritori/chain.json

In the teritori chain configuration file, the codebase information was repeated twice

Fix: remove duplicated info for Teritori

---

juno/assetlist.json

This removes a space in the coingecko ID of the hopers token on juno.

Remove extraneous space

---

testnets/hypersigntestnet/chain.json

This PR intends to update `chain.json` with latest information of the recently launched Hypersign Testnet (Prajna) on 14th December 2023. The Old Testnet (Jagrat) has been shut down.

Update Hypersign Testnet Info

---

evmos/chain.json

This PR updates Evmos binary information to the latest patch release v16.0.03

Update Evmos latest v16.0.3 binary information

---

dymension/assetlist.json

- Adds/Sets the `coingecko_id` field to `dymension` for the `dym` asset on `Dymension`
- Can verify here: https://www.coingecko.com/en/coins/dymension

Add dymension coingecko id

---

osmosis/assetlist.json

Update Osmosis assetlist.json 5
Few tweaks and fixes.
Display property is updated. No longer duplicates keywords or denom_unit aliases.

Update Osmosis assetlist.json 5

---

juno/chain.json

Halt height upgrade for Juno - even though the tag is `v20.0.0` it's still part of the `v19` upgrade handler. Removed old versions from compatible list.

Halt-height upgrade for Juno (v20)

---

testnets/dydxtestnet/assetlist.json
testnets/dydxtestnet/chain.json

The primary token of the dYdX testnet is DV4TNT not DYDX

Fix dYdX Testnet assets

---

nomic/chain.json

Removing previous version from chain history as there is still no clarity for me on how upgrades actually work. Once this is figured out we can consider creating an actual version history.

Upgrade Nomic v8.0.0

---

source/assetlist.json

Fix SCRX denoms
they had 'srcx' as the unit for both 0 and 9 exponent, which is ambiguous

Fix SCRX denoms

---

neutron/chain.json

Remove Neutron Fee Tokens because they aren't registered.

Remove Neutron Fee Tokens

---

stride/chain.json

Remove Fee Tokens from Stride because they are not registered in its assetlist.

Remove Fee Tokens from Stride

---

teritori/assetlist.json

- Added USD Coin asset with denom units and traces for IBC
- Added Secret Network asset with denom units and traces for IBC
Tested with 
> teritorid query ibc-transfer denom-hash transfer/channel-62/uusdc
hash: FE98AAD68F02F03565E9FA39A5E627946699B2B07115889ED812D8BA639576A9
> teritorid query ibc-transfer denom-hash transfer/channel-63/uscrt
hash: F3F6BDEE1A79664B169D742651107BF4E03FA67E931452E27380B75F5917B7E9

feat(teritori-update-assetlist): Add USD Coin and Secret Network assets

---

stride/chain.json

Raises gas prices for stDYDX and stDYM on Stride chain, to reflect the most common config among validators. 
Please let me know if you have any questions!

Update some Stride gas prices to reflect majority of validators' configs

---

_IBC/odin-osmosis.json

I believe this is the correct client.  
cc @Cordtus 
```
osmosisd q ibc connection connections --limit 50000 | jq '.connections[] | select(.id == "connection-1551") | {client_id, counterparty}'
{
"client_id": "07-tendermint-2007",
"counterparty": {
"client_id": "07-tendermint-10",
"connection_id": "connection-9",
"prefix": {
"key_prefix": "aWJj"
}
}
}
```
Also, odin-protocol requested a 2nd channel be created for use by doki.

update odin-osmosis client_id

---

_IBC/akash-persistence.json

The replaced path has expired for years, and no assets have been transferred using the path. The new path created will be actively utilized.
Can be checked here: https://www.mintscan.io/persistence/relayers/channel-5/akash/channel-6

Update akash-persistence.json to new path

---

dydx/chain.json

The PRO Delegators [RPC endpoint](https://github.com/cosmos/chain-registry/blame/master/dydx/chain.json#L184-L187) on is not configured correctly and all of the routes return 404 (i.e. [/health](https://community.nuxian-node.ch:6797/health?)), which impacts third parties that use the chain registry RPC list.
This PR moves it down the RPC list it does not affect parties using the first RPC of the list by default, like the [Squid API](https://github.com/skip-mev/skip-router-sdk/blob/8c426403d5ddd90509abe2c5490191bcc29f8904/packages/core/src/client.ts#L1224).

move pro-delegators dYdX RPC at the end of the list

---

osmosis/assetlist.json

Remove Duplicate Image Objects in Osmosis Assetlist
Artifact from old version of image_sync

Remove Duplicate Image Objects in Osmosis Assetlist

---

.github/workflows/utility/chain_registry.mjs
.github/workflows/utility/chain_registry_local.mjs
.github/workflows/utility/validate_data.mjs

Add Check for Duplicate chain_ids
Killed chains do not count.
Chains without chain.json or underfined chain_id are skipped.

Add Check for Duplicate chain_ids

---

ibc_data.schema.json
versions.schema.json

Added missing type definitions for versions.schema.json and ibc_data.version.json

Feat: add missing schema types

---

.github/workflows/utility/validate_data.mjs
highbury/assetlist.json
juno/assetlist.json
osmosis/assetlist.json
teritori/assetlist.json
terra/assetlist.json
terra2/assetlist.json
testnets/arkeonetworktestnet/assetlist.json
testnets/fetchhubtestnet/assetlist.json
testnets/lavatestnet/chain.json
testnets/permtestnet/chain.json
testnets/quasartestnet/assetlist.json
testnets/ulastestnet/assetlist.json
testnets/uniontestnet/assetlist.json
testnets/wavehashtestnet/chain.json
testnets/xiontestnet/assetlist.json

Specifically, missing base or display unit, that base is 0 exponent, and that ibc hash denoms are all uppercase.
Also, updated some testnet chain-ids, because they had already been taken.
Various denom_unit corrections--there were a number of invalid units specified throughout the registry, and this validation caught many of the issues.

Update Data Validation to find Invalid Units

---

_IBC/nibiru-osmosis.json

Correct the nibiru-osmosis.json IBC connection
Appears the previous value was a copypastypo, while the connection appears to actually be
channel-0

Correct the nibiru-osmosis.json IBC connection

---

dydx/chain.json

Update the order of RPC endpoints so Polkachu is no longer the first on the list.
This is because Polkachu has blocked any usage from a Github Action, which is not desirable when working with something like https://github.com/cosmos/chain-registry/pull/4136.

update dYdX RPC list order

---

juno/assetlist.json

Coingecko listing and migration notice](https://www.coingecko.com/en/coins/fanfury).
A Cw20 version of FURY was initially minted on Juno network but was deprecated later after migration to the native Furya Chain.
The entry resides in [Cosmos registry](https://github.com/cosmos/chain-registry/blob/master/furya/assetlist.json).
Corrections have to be made to reflect the current version of the token to avoid confusion.
This is probably the step one. Any further direction regarding this would also be appreciated.

Update deprecated FURY.legacy CW20 asset

---

_IBC/axelar-bitsong.json

Previous client on the axelar side has expired due to a relayer misconfiguration. The channel was only used for testing. New channels have been created as per request, the config error has been fixed on our side.

Update `ibc` axelar-bitsong

---

_IBC/neutron-sei.json

Old clients between Neutron and Sei were expired - new clients, connections and channels have been created. 
There were [only 2 successful (test) txs on the old channel pair](https://www.mintscan.io/neutron/relayers/channel-19/sei/channel-15), the 2nd tx was by the astroport team

Update `ibc` neutron-sei

---

evmos/chain.json

https://github.com/evmos/evmos/releases/tag/v17.0.0
Non-prop based upgrade, so there is no proposal. Binary on v16 was changed to v16.0.4 before halt-height, new binary v17.0.0 works with cosmovisor as v17.0.0 regardless of there being no prop

Upgrade Evmos to v17.0.0

---

osmosis/chain.json
osmosis/versions.json

Update Osmosis to Version v24
https://github.com/osmosis-labs/osmosis/blob/v24.0.0/CHANGELOG.md
https://github.com/osmosis-labs/osmosis/blob/main/go.mod

Update Osmosis to Version v24

---

_non-cosmos/moonbeam/assetlist.json

Fix Moonbeam's Assets `type_asset`
Had duplicate properties for type_asset
Removed the substrate one on addressed assets--kept as erc20

Fix Moonbeam's Assets `type_asset`

---

terra2/assetlist.json

Remove CGID from Terra2::ASTRO
Belongs only on Neutron's ASTRO

Remove CGID from Terra2::ASTRO

---

neutron/assetlist.json

Fix xASTRO image URL
Due to capitalized letters, the URL did not go to the uploaded image

Fix xASTRO image URL

---

osmosis/assetlist.json

Update Osmosis' Assetlist
As generated from its assetlists repo
Issues noticed:
Existing socials should not be removed (e.g., OSMO's)
Existing extended_descriptions should not be removed.
See if we can merge similar keywords like 'osmosis-unlisted' and 'osmosis_unlisted'
Double check NSTK ibc denom: Confirmed, proposed change is correct. Should be ibc/F7...
Why is heart-dark-mode logoURIs only png, but the image is both png and svg?

Update Osmosis' Assetlist

---

testnets/nobletestnet/chain.json

- Mintscan no longer uses the testnet subdomain and has noble-testnet in the main domain. This PR updates the entry to reflect this.

Remove Noble mintscan testnet subdomain

---

cronos/chain.json

Updating Cronos's chain info after the `v1.2` breaking upgrade.
More details can be found [here](https://blog.cronos.org/p/cronos-mainnet-v12-upgrade-announcing)

Update cronos's chain.json for v1.2 upgrade

---

testnets/osmosistestnet/chain.json

Remove OSL RPC from Osmosis Testnet
it's offline

Remove OSL RPC from Osmosis Testnet

---

assetlist.schema.json
chain.schema.json
ibc_data.schema.json
memo_keys.schema.json
versions.schema.json

The current names break codegen, and are seemingly unmaintained. This upgrade adds/updates schema titles and descriptions to reflect current chain-registry.

update titles of schema definitions

---

likecoin/chain.json

https://www.mintscan.io/likecoin/proposals/81
likecoin chain has just been upgraded to v4.2.0 with ibc 6.3.0

Upgrade likecoin to v4.2.0

---

realio/chain.json

avoid using version **v0.9.0** - node crash.
cc @jiujiteiro

Changed mainnet version to v0.9.2 - Realio

---

testnets/seitestnet2/chain.json

In accordance with the latest Sei governance proposal and to match the other Cosmos chain registries this PR updates the Global Min Gas Price to 0.08 as outlined in the Sei Chain.
https://github.com/sei-protocol/chain-registry/pull/58/files

Sei Testnet (atlantic-2): Update Global min gas price

---

_IBC/conscious-osmosis.json
osmosis/assetlist.json

Hi, due to a problem with the synchronization block of the deployed osmosis node, the tendermint client expired, so we created a new ibc channel.

Update CVN ibc token in osmosis

---

_non-cosmos/0l/assetlist.json
_non-cosmos/aptos/assetlist.json
_non-cosmos/sui/assetlist.json
_non-cosmos/xrpl/assetlist.json
assetlist.schema.json

Add 'unknown' type_asset option for 0l, xrpl, aptos, sui
Meant to be a 'catch-all' type asset classification

Add 'unknown' type_asset option

---

echelon/assetlist.json
juno/assetlist.json
secretnetwork/assetlist.json

Removing Echelon CGID since it no longer exists
and Secret Network $BUTT
and Juno's: MARBLE, HOPE, HOPERS, RAW, SEJUNO, BJUNO (stakeeasy)

Remove Echelon CoinGecko ID

---

_non-cosmos/ethereum/assetlist.json
axelar/assetlist.json
gravitybridge/assetlist.json
noble/assetlist.json

Add CoinGecko IDs for bridged assets
Update 'USD Coin' name to just 'USDC'

Add CoinGecko IDs for bridged assets

---

dydx/chain.json

v4.1.2 is a recommended non-state breaking upgrade: [release notes](https://github.com/dydxprotocol/v4-chain/releases/tag/protocol%2Fv4.1.2)

Add dYdX v4.1.2

---

axelar/assetlist.json
gravitybridge/assetlist.json

This PR simply corrects the CoinGecko IDs for two assets, which were accidentally set to the slug URLs rather than the API IDs.

Correct CoinGecko IDs for USDC.grv and USDT.axl

---

.github/workflows/utility/sync_images.mjs
_non-cosmos/avalanche/assetlist.json
_non-cosmos/composablepolkadot/assetlist.json
_non-cosmos/moonbeam/assetlist.json
_non-cosmos/penumbra/assetlist.json
_non-cosmos/picasso/assetlist.json
_non-cosmos/polkadot/assetlist.json
_non-cosmos/polygon/assetlist.json
_non-cosmos/solana/assetlist.json
axelar/assetlist.json
carbon/assetlist.json
composable/assetlist.json
gravitybridge/assetlist.json
kujira/assetlist.json
migaloo/assetlist.json
noble/assetlist.json
osmosis/assetlist.json
testnets/_non-cosmos/moonbeamtestnet/assetlist.json
testnets/dydxtestnet/assetlist.json
testnets/entrypointtestnet/assetlist.json
testnets/osmosistestnet/assetlist.json

Update Sync Images Code
Notably, doesn't create logo_URIs because it is a legacy property (but it overwrites it if it was already there).
Adds image_sync on images matching its origin Asset's primary image (unless already defined)

Update Sync Images Code

---

canto/chain.json
crescent/chain.json
emoney/chain.json
regen/chain.json

Removes mintscan as explorer for canto, crescent, emoney, and regen networks since support has been deprecated

remove mintscan explorer for deprecated networks

---

testnets/_IBC/axelartestnet-mantrachaintestnet.json

Old client has expired due to a relayer misconfiguration.

Update `ibc` axelartestnet-mantrachaintestnet

---

canto/chain.json

Removes the bigdipper and blockscout explorers for canto which have deprecated support for the chain.

remove deprecated canto explorers

---

cronos/chain.json

Hello Cosmos team, this PR is to bump the `recommended_version` of cronosd to [v1.2.2](https://github.com/crypto-org-chain/cronos/releases/tag/v1.2.2) with rpc bug fixes.

Bump Cronos "recommended_version" to v1.2.2

---

README.md

Updated the link to `DenomMetadata` in cosmos docs 
The link that came before is no longer available

Update README: fix cosmos coin-metadata link

---

evmos/chain.json

This is a non-prop hardfork upgrade. The upgrade_handler for 18.1.0 is staged via the v18.0.1 patch for v18.0.0. Same situation for v17.0.0 to v18.0.0. Old binaries have been removed as the "patched binaries" are required to detect the upgrade_handler.

Upgrade Evmos to v18.1.0 and update version history

---

_non-cosmos/penumbra/assetlist.json

- Remove 'exponent 3' denom
- Re-order denoms [base >> 'exponent 6']
- Add 'circle' property
- Fix logo image URLs

Fix Penumbra logo paths, clean up token denoms

---

onomy/chain.json

Remove logo_URIs from Onomy
There were two duplicate properties for logo_URIs.
We should use `images`. Added svg to images

Remove logo_URIs from Onomy

---

migaloo/assetlist.json
osmosis/assetlist.json

Previously pushed assetlist.json code for shitmos on Migaloo chain, and was asked to remove the "logo_URIs" object because it had been deprecated. I was confused because I could see that many assets use that object. I complied, but this PR reverses that change. The removal of the logo URI object from the osmosis side and migaloo side has made shitmos no longer compatible with skip protocol's IBC Fun, which is crucial infrastructure for shitmos users.
See screenshot of conversation with Skip Protocol dev:

add back logo uri objects for shitmos so skip protocol works

---

chain.schema.json
cosmoshub/chain.json

Fixes #3983.
Added validator_page, proposal_page and block_page into explorer schema, also added these links to all Cosmos Hub pages as a proof of concept.

Add explorer links to chain schema + added Cosmos Hub explorer links

---

evmos/assetlist.json

We are going to transition to a new type of token on the EVMOS chain which will allow us to have a native IBC BERLIN token in the future. Reason why we are deprecating the current BERLIN token into a legacy token.

deprecate BERLIN

---

osmosis/assetlist.json

To get the shitmos asset as a verified asset on osmosis, the following new objects have been added to the cosmos chain-restistry entry for shitmos on the Osmosis blockchain:
- extended description
- socials
- keywords
Thank you!

Add socials, memecoin keyword, and extended description per Osmosis

---

cronos/chain.json
cryptoorgchain/chain.json

Incorrect explorer entry for EZStaking (was for "Cronos POS Chain", not "Cronos EVM Chain"). Removed Yummy explorer from Cronos POS Chain (no longer available)

Fix explorer entries Cronos POS Chain

---

axelar/chain.json

we (axelar-core) have replaced our old seed node, updating the connection string here to reference the new seed.

chore: axelar chain.json - update seed node 

---

juno/chain.json

v22.0.1 is the only compatible version, validators who did not patch led to a chain halt.

Patch Juno to v22.0.1

---

_IBC/archway-doravota.json

Previous channels between archway and doravota weren't used in production, the clients have timed out. CryptoCrew is maintaining the new channels

Update `ibc` archway-doravota

---

README.md
cosmoshub/chain.json
noble/chain.json

These RPCs and explorers are no longer running at Strangelove.

Removing invalid public resources.

---

odin/chain.json

We have upgraded our mainnet to core v0.8.3 which is based on CosmosSDK 0.50.7 and CometBFT 0.38.7 and want to reflect updated versions in chain.json

Update Odin chain.json after successful upgrade

---

_non-cosmos/ethereum/assetlist.json

despite the description claiming that frxETH is a liquid staking derivative, it is definitely NOT--but just a synthetic version.
sfrxETH is the liquid-staked version of frxETH.

Fix Trace types for frxETH and sfrxETH

---

testnets/cosmosicsprovidertestnet/assetlist.json
testnets/cosmosicsprovidertestnet/chain.json

This reflects is new name as of gaia v17. I also upgraded the gaia versions. You can learn more about this testnet [here](https://github.com/cosmos/testnets/tree/master/interchain-security/provider)

Rename the RS provider testnet to Cosmos ICS Provider testnet

---

initia/assetlist.json

- There was an issue in rendering the Initia INIT image URLs when they were lowercase, this PR fixes them to specify the correct URLs in the chain registry

[FIX] Properly capitalize Initia image URLs

---

_non-cosmos/ethereum/assetlist.json

Update wstETH Trace Relationship to Liquid Stake instead of wrapped. Although it's sort of a wrapped stETH, it isn't 1:1 with stETH, but it accumulates value, which is why I think this is better described as a liquid staking relationship. I.E., wstETH is a liquid-staked version of stETH (with 0 unlock duration).

Update wstETH Trace Relationship to Liquid Stake

---

testnets/_IBC/archwaytestnet-osmosistestnet.json
testnets/archwaytestnet/assetlist.json

- Update connections
- Update channels
- Update port id
- Replace wrong base_denom aarch with aconst
Reason: 
The archway testnet channels on cosmos chain registry not active anymore, so I update to "active" ones

Update archway osmosis testnet IBC channels with active channels

---

testnets/archwaytestnet/chain.json

Use correct urls from https://github.com/archway-network/networks/blob/main/testnets/archwaytestnet/chain.json

Use correct urls for Archway testnet

---

juno/assetlist.json
migaloo/assetlist.json

Update Racoon RAC traces
Juno racoon is an additional-mintage of magaloo rac (actualy it's a legacy mintage)

Update Racoon RAC traces

---

testnets/celestiatestnet2/chain.json
testnets/celestiatestnet3/chain.json

Updates to support a range of celestia-app versions on Mocha testnet and Arabica devnet. Based on https://docs.celestia.org/nodes/participate

feat: update celestia-app versions on Mocha and Arabica

---

agoric/chain.json
agoric/versions.json

Update Agoric chain info with details of the latest version.
- Governance Proposal for Update: https://agoric.explorers.guru/proposal/75
- Tested by pushing JSON files through `jq`

Version updates for latest Agoric release

---

8ball/chain.json

Update 8Ball to Killed
All socials are unavailable, all explorers are either unavailable or disconnected, and all RPC/status endpoints are down.
It is reasonable to assume that this chain is killed.

Update 8Ball to Killed

---

bitcanna/chain.json

Update
"kind": "AviaOne Explorer 🟢",
for Bitcanna mainnet chain

Update Bitcanna mainnet chain.json

---

lava/chain.json

Small typo in Lava's guru explorer, the `tx_page` url is missing the `h` in `https`.

Fix missing h in https typo in Lava guru explorer

---

.github/workflows/lint.yml
eslint.config.mjs
package-lock.json
package.json

adding a linter could prevent malformed json from accidentally entering the registry.
the workflow is based on your existing workflows.
the repository currently passes this lint workflow.
this 'recommended' eslint config from eslint-plugin-json would have caught https://github.com/cosmos/chain-registry/issues/5088
as an example, that failure is duplicated in #5102

add eslint-plugin-json and lint workflow

---

testnets/symphonytestnet/chain.json

- add new endpoints from more reliable nodes
- update IPs for persistent peers
- update chain ID to v2

Symphony testnet: update to testnet-2

---

source/chain.json

Security update v3.0.3 . Coordinated upgrade done with the Validator set via Discord.
https://github.com/Source-Protocol-Cosmos/source/releases/tag/v3.0.3

Source Chain Update

---

osmosis/assetlist.json

Was defined as a bridged Tron USDT, but it's actually a synthetic of Ethereum::USDT.

Correct Osmosis' Router USDT

---

_IBC/neutron-penumbra.json

Paths for neutron-penumbra have been re-created after the old clients have expired. When penumbra upgrades relayers have to go through the [same procedure as for genesis restarts as per penumbra docs](https://guide.penumbra.zone/relayers#performing-upgrades).
Old channels weren't used at all (weren't integrated in any frontends), this was confirmed with the Neutron team.

Update IBC `neutron-penumbra`

---

sei/chain.json

Adds:
- "Rhino Stake" RPC/REST/GRPC
- "Seitrace" (blockscout) explorer
Updates:
- Explorer type "seiscan" >> "celatone"
- EVM RPC provider name "Rhino" >> "Rhino Stake"
Removes:
- Explorer "ping.pub" [does not support sei]

Updates Sei chain.json APIs, add explorer, remove unsupported explorer, correct some names

---

.github/workflows/utility/validate_data.mjs
aura/chain.json
axelar/chain.json
celestia/chain.json
cheqd/chain.json
composable/chain.json
desmos/chain.json
dhealth/chain.json
evmos/chain.json
finschia/chain.json
gateway/chain.json
haqq/chain.json
lava/chain.json
neutron/chain.json
noble/chain.json
nolus/chain.json
onomy/chain.json
persistence/chain.json
sge/chain.json
stride/chain.json
terra2/chain.json
testnets/cheqdtestnet/chain.json
testnets/finschiatestnet/chain.json
testnets/neutrontestnet/chain.json
testnets/nibirudevnet3/chain.json
testnets/nibirudevnet4/chain.json
testnets/nobletestnet/chain.json
testnets/persistencetestnet2/chain.json
ununifi/chain.json
xpla/chain.json

```
const replacementPropertiesMap = new Map([
["cosmos_sdk_version", "sdk"],
["ibc_go_version", "ibc"],
["go_version", "language"],
["cosmwasm_version", "cosmwasm"]
]);
```
if cosmos_sdk_version is defined, then the replacement sdk object must exists, with type: cosmos, and version tag, and repo, expacted from the value.

Add Data Validation for Deprecated and Replacement Version Properties

---

cosmoshub/chain.json

added dRPC to the list of RPCs.
https://drpc.org/chainlist/cosmos-hub

Add Cosmos Hub RPC "dRPC"

---

celestia/chain.json

[celestia-app v2.1.2](https://github.com/celestiaorg/celestia-app/releases/tag/v2.1.2) is recommended for Mainnet Beta. Please tag me and @jcstein on future PRs that modify Celestia files.

feat: upgrade celestia to v2.1.2

---

cronos/chain.json

Hello Cosmos team, this PR is to bump the `recommended_version` of cronosd to [v1.3.0](https://github.com/crypto-org-chain/cronos/releases/tag/v1.3.0).

Bump Cronos "recommended_version" to v1.3.0

---

_IBC/pryzm-terra2.json

This PR intends to update the ICA channel for Pryzm delegations on Terra2. The former channel was closed due to timeout as a result of Terra's last night halt.

Update Pryzm-Terra ICA channels

---

pryzm/assetlist.json

The INJ drivatives on Pryzm have an 18 decimal while it was mistakenly set to 6.

Fix INJ derivative decimals on Pryzm

---

dydx/chain.json

Cosmos chain-registry update to reflect dydx release to v6.0.4.
@reversesigh

dYdX Chain-registry update to reflect release to v6.0.4

---

_non-cosmos/base/assetlist.json

Fix cbBTC Trace
updating provider from Base Bridge to Coinbase
(because Base Bridge refers to an Ethereum to Base user-accessible bridge)

Fix cbBTC Trace

---

_non-cosmos/litecoin/assetlist.json

Fix LTC Image URL
was mistakenly pointing at Dogecoin's directory

Fix LTC Image URL

---

atomone/chain.json

```sh
$ grpcurl -plaintext atomone-grpc.allinbits.com:9090 list
atomone.gov.v1.Query
atomone.gov.v1beta1.Query
cosmos.auth.v1beta1.Query
cosmos.authz.v1beta1.Query
cosmos.autocli.v1.Query
cosmos.bank.v1beta1.Query
cosmos.base.node.v1beta1.Service
cosmos.base.reflection.v1beta1.ReflectionService
cosmos.base.reflection.v2alpha1.ReflectionService
cosmos.base.tendermint.v1beta1.Service
cosmos.consensus.v1.Query
cosmos.distribution.v1beta1.Query
cosmos.evidence.v1beta1.Query
cosmos.feegrant.v1beta1.Query
cosmos.mint.v1beta1.Query
cosmos.params.v1beta1.Query
cosmos.reflection.v1.ReflectionService
cosmos.slashing.v1beta1.Query
cosmos.staking.v1beta1.Query
cosmos.tx.v1beta1.Service
cosmos.upgrade.v1beta1.Query
grpc.reflection.v1alpha.ServerReflection …
```

fix(atomone): grpc url

---

bitbadges/chain.json

It has come to my attention via X that using the bech32 prefix "cosmos" has broken some services that depend on this registry. BitBadges is showing up where the Cosmos Hub is expected or causing other problems due to the collision.
To avoid confusion and breaking anything, I would like to remove this line from the registry. I noted that "bech32_prefix" is not required in the schema file, so for the time being, I would like to remove it. 
I think this is a better solution because:
-Collisions are avoided.
-If not having the "bech32_prefix" causes issues, this would only occur for BitBadges and we will handle accordingly (rather than affecting other projects).
-Anyone can still just view the BitBadges documentation to get our Cosmos prefix.
I still plan to migrate to a personal prefix, but …

change "bech32" prefix for bitbadges

---

_IBC/neutron-terra2.json

This channel can be used to transfer `cw20` tokens like ROAR from terra2 to neutron.

Add `ibc` neutron-terra (terra cw20-ics20)

---

neutaro/chain.json

We are moving from neutaro.tech to neutaro.io. The other RPCs will be moved soon.

Neutaro chain.json update

---

microtick/assetlist.json

Remove Microtick CoinGecko ID
It no longer exists: https://api.coingecko.com/api/v3/coins/microtick

Remove Microtick CoinGecko ID

---

acrechain/assetlist.json
comdex/assetlist.json
crescent/assetlist.json
gravitybridge/assetlist.json
imversed/assetlist.json
juno/assetlist.json
kichain/assetlist.json
osmosis/assetlist.json
provenance/assetlist.json
quasar/assetlist.json
qwoyn/assetlist.json
stride/assetlist.json
tgrade/assetlist.json

Remove Deprecated CoinGecko IDs
The following CoinGecko IDs no longer exist
"gravity-bridge-usdc",
"provenance-blockchain",
"tgrade",
"lvn",
"crescent-network",
"imv",
"arable-usd",
"wynd",
"stride-staked-luna",
"stride-staked-evmos",
"harbor-2",
"quasar-2",
"qwoyn",
"sail-dao"

Remove Deprecated CoinGecko IDs

---

shido/chain.json

`256x25.tech` had their RPC and REST entries in the wrong areas.

Fix incorrect RPC/REST endpoints for Shido

---

nim/chain.json

Update RPC urls to switch from Bware to NIM Foundation

Update NIM RPCs

---

osmosis/versions.json

Update Osmosis Versions History (v25-v27)
also cleaned up some deprecated properties (comsos_sdk_version, cosmwasm_version, cosmwasm_enabled)

Update Osmosis Versions History (v25-v27)

---

agoric/versions.json
lava/versions.json
pryzm/versions.json
versions.schema.json

Remove Legacy Properties from Versions.json Files
Agoric
Lava
Pryzm,
and the versions.schema.json

Remove Legacy Properties from Versions.json Files

---

pryzm/assetlist.json

This PR adds the new minted tokens with the maturity of 31Dec2026 to the list of Pryzm assets. It also fixes the decimal of `ystDYDX` tokens.

Add new Pryzm derivatives with new maturity

---

testnets/cosmosicsprovidertestnet/chain.json
testnets/cosmosicsprovidertestnet/versions.json

* Bump v21.0.0 to v21.0.1
* Update endpoint and explorer URLs

Bump Cosmos ICS Testnet to Gaia v21.0.1

---

testnets/xiontestnet/assetlist.json

Remove CoinGecko ID from Testnet $XION
Should only be there for mainnet assets

Remove CoinGecko ID from Testnet $XION

---

kyve/chain.json
testnets/kyvedevnet/chain.json
testnets/kyvetestnet/chain.json

Update the entries for KYVE (https://github.com/KYVENetwork) mainnet, testnet and devnet. 
Changes:
- Update all networks to current binary
- Official KYVE endpoints have slightly changed
- Removed terminated servers and replaced with the current ones (persistent peers)
- Added Viewblock explorer
- Removed incorrect explorer entry for devnet

chore: update KYVE mainnet, testnet and devnet

---

persistence/assetlist.json

Deprecate Persistence pSTAKE Assets
using the deprecated property
Prepended "(Deprecated)" to their Descriptions

 Deprecate Persistence pSTAKE Assets

---

_IBC/archway-migaloo.json
archway/assetlist.json
chihuahua/assetlist.json
injective/assetlist.json
juno/assetlist.json
terra/assetlist.json
terra2/assetlist.json

This PR adds WHALE, Native token of the Migaloo blockchain, to multiple chain assetlists:
Terra2
Terra
Archway
Juno
Chihuahua
Injective
Additionally it also registers migaloo-archway connection in _IBC

Add WHALE and Register migaloo-archway

---

nois/chain.json

A governance proposal passed today to end the blockchain on December 10th:
https://nois.explorers.guru/proposal/11
The last block will be [22777777](https://nois.explorers.guru/block/22777777)
-----------------
For the archive:

Set status of Nois to killed

---

xion/chain.json

Staking Explorer's XION Node was accidentally removed. This is restoring it

Restore XION Explorer

---

cheqd/chain.json
cheqd/versions.json
testnets/cheqdtestnet/chain.json
testnets/cheqdtestnet/versions.json

- Updates cheqd v3 protocol release values.
- Backfills versioning.

fix: CHEQD: Reflect v3 protocol release + versioning

---

testnets/_IBC/axelartestnet-sagatestnet.json
testnets/sagatestnet/chain.json
testnets/sagatestnet/versions.json

This PR is to request an upgrade to the chain ID and IBC settings for SAGA testnet chain.

Upgrading SAGA Testnet chain to ssc-testnet-2

---

testnets/manifesttestnet/chain.json
testnets/manifesttestnet/versions.json

This PR updates the Manifest testnet
- APIs
- Chain ID
- Versions
- Binaries
- Block Explorer
cc @chalabi2

Update Manifest testnet APIs & more

---

pryzm/assetlist.json

This PR adds the new minted tokens with the maturity of 31Mar2025 to the list of Pryzm assets.

Add new Pryzm derivatives with 31Mar2025 maturity

---

osmosis/assetlist.json

On branch add_CHIHUAHUA_coin
Changes to be committed:
Modified:   osmosis/assetlist.json
{
"description": "Chihuahua coin",
"denom_units": [
{
"denom": "ibc/794CF0A448ECA518B9FEAB3356BD283E8762460F8FE87A013E6F9DBA6C53601C",
"exponent": 0,
"aliases": [
"factory/chihuahua1mzcfzh4ufk2cta59pm9a6wdyvv8c4v5epqzj46/Chihuahua"
]
},
{
"denom": "Chihuahua",
"exponent": 6
}
],
"type_asset": "ics20",
"base": "ibc/794CF0A448ECA518B9FEAB3356BD283E8762460F8FE87A013E6F9DBA6C53601C",
"name": "Chihuahua",
"display": "Chihuahua",
"symbol": "CHIHUAHUA",
"traces": [
{
"type": "ibc",
"counterparty": {
"chain_name": "chihuahua",
"base_denom": "factory/chihuahua1mzcfzh4ufk2cta59pm9a6wdyvv8c4v5epqzj46/Chihuahua",
"channel_id": "channel-7"
},
"chain": {
"channel_id": "channel-113",
"path": …

Add $CHIHUAHUA coin on osmosis

---

testnets/manifesttestnet/assetlist.json
testnets/osmosistestnet/assetlist.json

This pr adds the ibc representation of mfx from the manifesttestnet to the osmosistestnet and vice versa

Add ibc assets for manifesttestnet and osmosistestnet

---

pryzm/chain.json
pryzm/versions.json

This PR updates the Pryzm chain version to the latest upgraded version.

Update Pryzm to v0.22

---

osmosis/assetlist.json

A new IBC connection has been setup for AtomOne <-> Osmosis, and PR #5812 has already been merged to reflect the new IBC connection.
Now updating assets on Osmosis, see below the confirmation of the IBC asset denom: 
```bash
$ echo -n transfer/channel-94814/uatone | sha256sum
bc26a7a805ecd6822719472bcb7842a48ef09df206182f8f259b2593eb5d23fb  -
```

Update ATONE asset on Osmosis with new IBC channels & denom

---

osmosis/assetlist.json

Move dTIA to bottom of Osmosis' Assetlist because it was mistakenly added earlier.

Move dTIA to bottom of Osmosis' Assetlist

---

testnets/cosmosicsprovidertestnet/chain.json
testnets/cosmosicsprovidertestnet/versions.json

* Upgraded chain from Gaia `v21.0.1` to Gaia `v22.0.0-rc0`

Upgrade Cosmos ICS Testnet to Gaia v22.0.0-rc0

---

_IBC/neutron-nomic.json

previous paths were not used in production

Update `ibc` neutron-nomic

---

pryzm/chain.json
pryzm/versions.json

This PR updates the Pryzm chain version to the latest upgraded version.

Update Pryzm to v0.24

---

README.md

Fix Typo "repond" to "respond"

Fix Typo "repond"

---

testnets/manifestdevnet/chain.json
testnets/manifesttestnet/chain.json

The average gas price was lower than the low gas price in both manfiesttestnet and manifestdevnet

update manifest average_gas_price

---

atomone/chain.json
atomone/versions.json
testnets/atomonetestnet/chain.json
testnets/atomonetestnet/versions.json

v1.0.1 is the new latest release https://github.com/atomone-hub/atomone/releases/tag/v1.0.1

Update AtomOne version to v1.0.1

---

.github/workflows/utility/chain_registry.mjs
.github/workflows/utility/coingecko_data.mjs
.github/workflows/utility/state/coingecko.json
.github/workflows/utility/validate_data.mjs
coreum/assetlist.json
testnets/_non-cosmos/avalanchetestnet/assetlist.json
testnets/_non-cosmos/binancesmartchaintestnet/assetlist.json
testnets/_non-cosmos/ethereumtestnet/assetlist.json
testnets/_non-cosmos/moonbeamtestnet/assetlist.json
testnets/_non-cosmos/polkadottestnet/assetlist.json
testnets/_non-cosmos/polygontestnet/assetlist.json
testnets/axelartestnet/assetlist.json
testnets/bitcannadevnet/assetlist.json
testnets/bitcannadevnet2/assetlist.json
testnets/cheqdtestnet/assetlist.json
testnets/coreumtestnet/assetlist.json
testnets/fetchhubtestnet/assetlist.json
testnets/impacthubdevnet/assetlist.json
testnets/injectivetestnet/assetlist.json
testnets/osmosistestnet/assetlist.json
testnets/osmosistestnet4/assetlist.json
testnets/persistencetestnet/assetlist.json
testnets/persistencetestnet2/assetlist.json
testnets/quicksilvertestnet/assetlist.json
testnets/secretnetworktestnet/assetlist.json
testnets/stargazetestnet/assetlist.json
testnets/terra2testnet/assetlist.json
testnets/xplatestnet/assetlist.json

Add Validating For CGID Groupings
Ensures that assets with the same coingecko ID are related.
Bulk update of assets (mostly adding test--mintage trace)

Add Validating For CGID Groupings

---

planq/assetlist.json

This commits add the nRide Tokens representation on PlanQ Network to use their Delta-Bridge to Binance Smart Chain

Update planq assetlist-- add nRide Multihop representation

---

_IBC/agoric-noble.json

We discovered a discrepancy between this file and map of zones. This query also points out that the right connection_id is connection-38:
```console
$ agd query ibc connection end connection-72 --node https://agoric-rpc.polkachu.com:443
connection:
client_id: 07-tendermint-77
counterparty:
client_id: 07-tendermint-32
connection_id: connection-38
```
cc @0xpatrickdev @turadg @luqipan

update noble -> agoric connection info for ICA host

---

osmosis/chain.json
osmosis/versions.json

Update Osmosis Version to v28.0.1+
v28.0.1 had an unintentional state-breaking change, and therefore created a new version to patch versions at an beyond v28.0.1 even though it's in the same major version number.

Update Osmosis Version to v28.0.1+

---

_IBC/kopi-noble.json
kopi/assetlist.json

A while ago our client on Noble-chain expired. We reached out to Noble on various channels but have not (yet) received a solid response or any official information on how to get the old client re-instated. Since we want to move on (our main-net release is currently on hold because of this situation), we kindly request this PR is accepted which changes the channel used for Noble.
The funds stuck in the previous channel are limited and are our funds which have been sent for testing: https://rest.kopi.money/cosmos/bank/v1beta1/supply/by_denom?denom=ibc%2F8E27BA2D5493AF5636760E354E46004562C46AB7EC0CC4C1CA14E9E20E2545B5
If at some point the old client gets recovered, we can return those funds back to noble chain.

Changed used channels between Noble and Kopi

---

quicksilver/chain.json
quicksilver/versions.json

Update chain.json and versions.json to reflect Quicksilver v1.7.7 release.

bump quicksilver to v1.7.7

---

testnets/babylontestnet/chain.json

Reverts cosmos/chain-registry#6004
Moves the gas prices to fee_tokens (was incorrectly added to staking tokens)

Revert "chore: Add gas steps on Babylon testnet"

---

testnets/zenrocktestnet/chain.json
zenrock/chain.json

This PR adjusts the gas prices for `gardia` and `diamond` which result from increasing the `min_gas_prices` on both networks.

adjust gas prices for gardia and diamond

---

injective/chain.json

Injective uses a fixed gas price model so have requested all be set to `160000000inj`.

Set all Injective gas prices to 160000000inj

---

_non-cosmos/polygon/assetlist.json

Correct POL and MATIC traces
POL is origin asset now
MATIC is a deprecated legacy-mintage of POL (doesn't even exist on-chain anymore)

Correct POL and MATIC traces

---

pryzm/chain.json
pryzm/versions.json

This PR updates the Pryzm chain version to the latest upgraded version.

Update Pryzm to v0.27

---

_IBC/crescent-mars.json
_IBC/juno-mars.json
_IBC/kujira-mars.json
_IBC/mars-neutron.json
_IBC/mars-osmosis.json
_IBC/mars-terra2.json
mars/assetlist.json
mars/chain.json

Kill Mars Chain
Chain status to killed
All IBC channels to killed
MARS Asset (only the one from Mars Hub--not neutron's) to deprecated: true
as per https://x.com/mars_protocol/status/1902642598013018424

Kill Mars Chain

---

xpla/chain.json

Fix XPLA Explorer mainnet links
When accessing transaction or block information via https://explorer.xpla.io, users encounter a "Page not found" error. This PR updates all explorer links to use the correct format: https://explorer.xpla.io/mainnet
References:
- Correct explorer URL: https://explorer.xpla.io/mainnet
- Chain information: https://chainlist.wtf/chain/37/

Update XPLA Explorer Url

---

dungeon/chain.json

Specify Dungeon Chain Logo.
The png was already in the images directory

Specify Dungeon Chain Logo

---

neutron/versions.json

With Proposal https://governance.neutron.org/proposals/A/65 Neutron Mercury version 6.0.0 came into effect today.

Update Neutron version

---

babylon/assetlist.json

feat: add LBTC to bbn

---

babylon/assetlist.json

feat add solvBTC to bbn

---

_non-cosmos/ethereum/assetlist.json
babylon/assetlist.json

feat: add stBTC to bbn

---

_non-cosmos/ethereum/assetlist.json
babylon/assetlist.json

feat: add pumpBTC to bbn

---

babylon/assetlist.json

feat: add WETH to bbn

---

_IBC/initia-osmosis.json

Previous channels were unused and expired long ago (before public launch)

Update initia-osmosis.json IBC Connection

---

arkeo/chain.json

I didn't add this, but noticed the peer was labeled wrong

use correct peer for arkeo

---

testnets/_IBC/injectivetestnet-xrplevmtestnet.json

---
Adds the newly established **ICS-20 IBC transfer path** between the following testnets:
- **injectivetestnet**
- **xrplevmtestnet**
| Chain              | `client_id`         | `connection_id`     | `channel_id`     | `port_id`  |
|--------------------|---------------------|----------------------|------------------|------------|
| injectivetestnet   | `07-tendermint-321` | `connection-281`     | `channel-77038`  | `transfer` |
| xrplevmtestnet     | `07-tendermint-24`  | `connection-4`       | `channel-4`      | `transfer` |
- **Ordering:** `unordered`  
- **Version:** `ics20-1`  
- **Tags:** `live`, `preferred: true`, `dex: osmosis`
---
```txt
testnets/_IBC/injectivetestnet-xrplevmtestnet.json
```
---
- ✔️ Schema passes `ajv` validation.
- ✔️ Both LCD endpoints return `HTTP 200` for …

**feat(testnets/_IBC): add Injective testnet ↔ XRPL EVM testnet channel (connection-281/4)**

---

_non-cosmos/ethereum/assetlist.json
babylon/assetlist.json

feat: add satSolvBTC.e to babylon

---

_non-cosmos/ethereum/assetlist.json
babylon/assetlist.json

feat: add satLBTC.e to babylon

---

README.md

Replace non-functioning proxy.atomscan.com/directory URL with the working atomscan.com/directory URL in the README.md file. The proxy URL was returning a 404 error, while the direct URL is correctly listed in the Web Interfaces section and is functioning properly. This ensures consistency across the documentation and provides users with a working resource for the Chain Registry.

Fix broken AtomScan directory URL in Web Endpoints section

---

testnets/_IBC/cosmoshubtestnet-wardenprotocoltestnet.json
testnets/wardenprotocoltestnet/assetlist.json
testnets/wardenprotocoltestnet/chain.json
testnets/wardenprotocoltestnet/versions.json

This will update wardenprotocoltestnet to the latest testnet that Warden Protocol has.
Buenavista-1 testnet has been deprecated.

Update wardenprotocoltestnet to latest testnet

---

babylon/assetlist.json

Adds new tokens for Union-bridged assets on Babylon. This PR includes two new CW20 entries for the supported assets (mBTC and eBTC)

feat(babylon): add new CW20 assets to chain registry

---

testnets/sedatestnet/chain.json
testnets/sedatestnet/versions.json

Reflecting the recent upgrade of SEDA Testnet to binary version v1.0.0-rc.2.

Update SEDA testnet to v1.0.0

---

testnets/zenrocktestnet/chain.json

This PR bumps the zenrock gardia testnet chain-id from `gardia-4` to `gardia-5`.

bump: gardia chain-id

---

osmosis/assetlist.json

as per request of the community :), adding the following text:
Bernese Mountain Dog — a simple dog token with a fixed supply of 132M; non-mineable, non-stakeable, no inflation, no community pool, no dev allocation; initial genesis fairdrop was a tribute to stakers and LPs of the three-headed-dog chain before it stopped.

Update assetlist.json - Detailing lore of bernese

---

manifest/chain.json

Align mainnet fees with testnet and devnet.
CC @chalabi2

chore: bump manifest mainnet fees

---

manifest/chain.json
testnets/manifestdevnet/chain.json
testnets/manifesttestnet/chain.json

This pull request updates the blockchain explorer URLs in multiple `chain.json` files to improve functionality by adding support for account-specific pages and refining transaction page URLs.
* [`manifest/chain.json`](diffhunk://#diff-3576371a3e7dfa60a87f4d4c29754b9604b145dd0cda313126bb43c3cc57d4adL74-R76): Updated the mainnet explorer URLs to point to `https://explorer.manifest.network/`, added support for account-specific pages via `account_page`, and refined the transaction page URL to include `${txHash}`.
* [`testnets/manifestdevnet/chain.json`](diffhunk://#diff-0868ee64e25575090ce401ab22480cc5e16494da039b4e1f37076c5660273584L67-R68): Enhanced the devnet explorer configuration by adding an `account_page` URL and refining the transaction page URL to include `${txHash}`.
* …

fix: manifest block explorer urls

---

testnets/xiontestnet2/assetlist.json
testnets/xiontestnet2/chain.json
testnets/xiontestnet2/versions.json
xion/chain.json
xion/versions.json

This pull request updates the asset and chain configuration files for the Xion testnet and mainnet. Key changes include adding a new `coingecko_id` for an asset, updating the version tag and recommended version across multiple files, and replacing outdated binary links with links to the latest release. Additionally, the Chainroot explorer entry has been removed from the mainnet configuration.
* Added a `coingecko_id` field (`xion-2`) to the `type_asset` object in `testnets/xiontestnet2/assetlist.json`.
* Updated version tag and recommended version from `v19.0.1` to `v19.0.2` in `testnets/xiontestnet2/chain.json`, `testnets/xiontestnet2/versions.json`, `xion/chain.json`, and `xion/versions.json`. [[1]](diffhunk://#diff-e2f5d5773a676e60da86fbb479d23f9e87ad4b79abf3b2c8fb2a19a3f190d887L45-R55) …

xion-v19.0.2

---

manifest/assetlist.json
manifest/chain.json
manifest/versions.json

This pull request updates the Manifest project configuration files to include metadata enhancements and support for a new version of the software. The most important changes involve adding a `coingecko_id` to the asset metadata and updating the recommended and compatible versions to include `v1.0.5`.
* [`manifest/assetlist.json`](diffhunk://#diff-812a1fd5341eb35e6dedee91b4a735ddb3de7041d659ffe41973d59562c660a3L36-R37): Added a new `coingecko_id` field with the value `"manifest-2"` to the asset metadata.
* [`manifest/chain.json`](diffhunk://#diff-3576371a3e7dfa60a87f4d4c29754b9604b145dd0cda313126bb43c3cc57d4adL34-R37): Updated the `recommended_version` to `"v1.0.5"` and added `"v1.0.5"` to the `compatible_versions` list. Also updated the binary URL to point to the new version's release.
* …

chore: mfx coin gecko id and version bump

---

_IBC/bitbadges-osmosis.json

There was an initial mixup in the IBC configuration file in this registry. This fixes the configuration here to the actual clients used live (not an experimental one I accidentally created). This is just a registry configuration issue.
As seen with the following link, connection-1 uses 07-tendermint-2 and uses transfer/channel-104311.
https://explorer.bitbadges.io/BitBadges%20Mainnet/ibc/connection/connection-1
Whereas connection-0 isn't even open,
https://explorer.bitbadges.io/BitBadges%20Mainnet/ibc/connection/connection-0

bitbadges: fix IBC client info

---

xion/chain.json
xion/versions.json

This pull request updates the Xion blockchain configuration to reflect the new `v20.0.0` release. The changes include updating version references, binaries, and associated metadata for the new release, as well as adding a new entry for `v20` in the version history.
* **Version and binaries update in `xion/chain.json`:**
- Updated `tag` and `recommended_version` to `v20.0.0`.
- Updated binary URLs and checksums for `darwin/amd64`, `darwin/arm64`, `linux/amd64`, and `linux/arm64` to match the `v20.0.0` release.
- Updated the SDK version to `v0.53.3`.
* **New `v20` entry in `xion/versions.json`:**
- Added metadata for the `v20.0.0` release, including `tag`, `recommended_version`, block `height`, and proposal number.
- Included updated binary URLs, SDK version (`v0.53.3`), consensus version …

xion mainnet release v20

---

osmosis/assetlist.json

Bulk Update of Osmosis Assetlist
Reduces redundant specification of entire traces history (only the latest is needed).
Name and symbol are set to how they're defined for the the source asset on its counterparty chain (ignoring 'canonicalization')

Bulk Update of Osmosis Assetlist

---

lumera/chain.json

This PR adds new archive endpoints to Lumera mainnet, operated by Data Nexus, an active validator on the network.
RPC
https://lumera.archive.data.nexus
REST (LCD)
https://rest.lumera.archive.data.nexus
gRPC
https://grpc.lumera.archive.data.nexus:443

Add Data Nexus archive node to Lumera listing

---

sunrise/chain.json

This PR adds the Infrasingularity RPC endpoint for the Sunrise network to the chain-registry.
- The RPC endpoint URL: https://rpc-sunrise.infrasingularity.com
- Transaction indexing is enabled on this node (tx_index = "on" in configuration).
- CORS (Cross-Origin Resource Sharing) headers are properly configured to allow access.
- This submission complies fully with the Sunrise core team requirements for additional delegation incentives.
- The endpoint is production-grade, reliable, and ready to serve the community.

Add Infrasingularity RPC endpoint for Sunrise
